{
  "hash": "a5927b44d9f33f55dee58aaa03bf9987",
  "result": {
    "markdown": "---\ntitle: '2.2: Introduction to Random Variables'\n#author: 'Adam Spiegler, University of Colorado Denver'\noutput:\n  html_document:\n#    toc: yes\n#    toc_depth: 1\n#    theme: cerulean\n#jupyter:\n#  kernelspec:\n#    display_name: R\n#    language: R\n#    name: ir\n#output:\n#    ipynbdocument::ipynb_document\n---\n\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://githubtocolab.com/CU-Denver-MathStats-OER/Statistical-Theory/blob/main/Chap2/05-Intro-to-Random-Variables.ipynb) <nbsp>\n\n# Randomness in a Music Playlist\n\n---\n\n\n## Importing the Spotify Hits Data Set\n\n---\n\nThe data set *spotify-hits.csv*^[Downloaded from [Kaggle](https://www.kaggle.com/datasets/paradisejoy/top-hits-spotify-from-20002019) May 4, 2023] is stored online and contains audio statistics of the top 2000 tracks on Spotify from 2000-2019. The data is stored in a <span style=\"color:dodgerblue\">**comma separated file (csv)**</span>. \n\n- We can use the function `read.csv()` to import the csv file into an R data frame we call `hits`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhits <- read.csv(\"https://raw.githubusercontent.com/CU-Denver-MathStats-OER/Statistical-Theory/main/Data/spotify-hits.csv\")\n```\n:::\n\n\n\n### Cleaning the Music Data Set\n\n---\n\nIn the code cell below: \n\n- We convert `artist`, `song`, and `genre` to categorical variables using the `factor()` function.\n- Extract the variables `artist`, `song`, `tempo` and `genre` (ignoring the rest).\n- Print the first 6 rows to screen to get a glimpse of the resulting data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhits$artist <- factor(hits$artist)  # artist is categorical\nhits$song <- factor(hits$song)  # song is categorical\nhits$genre <- factor(hits$genre)  # genre is categorical\nhits <- hits[,c(\"artist\", \"song\", \"tempo\", \"genre\")] \nhead(hits)  # display first 6 rows of data frame\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          artist                   song   tempo             genre\n1 Britney Spears Oops!...I Did It Again  95.053               pop\n2      blink-182   All The Small Things 148.726         rock, pop\n3     Faith Hill                Breathe 136.859      pop, country\n4       Bon Jovi           It's My Life 119.992       rock, metal\n5         *NSYNC            Bye Bye Bye 172.656               pop\n6          Sisqo             Thong Song 121.549 hip hop, pop, R&B\n```\n:::\n:::\n\n\n\n## Question 1\n\n---\n\nExplore the data set `hits`. For example: \n\n- How many observations are in the data set?\n- Which artist had the most hits? \n- What is the mean tempo? \n- Create a plot to display the distribution of tempo scores. \n- What genre occurs most frequently?\n\n### Solution to Question 1\n\n---\n\n\n\\ \n\\ \n\\ \n\n\n## Creating a Random Playlist\n\n---\n\nTo create a random playlist of five songs from the `hits` library of songs, we can run the code cell below.\n\n- The `sample()` function below has three inputs:\n  - The \"population\" we will be sampling from.\n    - `nrow(hits)` returns the value 2000, the total number of observations (rows) in the data frame.\n  - The `size` is the number of observations we will select.\n  - The `replace =TRUE` options means we sample with replacement. Each time we pick a song, we place it back into the population and can select it in our playlist again.\n  - Run `?sample` for more information.\n- We save the selected songs to the object called `playlist`.\n- We print the list of songs in `playlist` to the screen\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# index contains the 5 randomly selected songs\nindex <- sample(nrow(hits), size=5, replace = TRUE)\nplaylist <- hits[index,]  # save each song from index to a playlist\nhead(playlist)  # print the playlist\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    artist                                            song\n1047             Timbaland    If We Ever Meet Again (Featuring Katy Perry)\n1643 Fitz and The Tantrums                                        HandClap\n1968                DaBaby                                            Suge\n476            Alicia Keys Diary (feat. Tony! Toni! Tone! & Jermaine Paul)\n738               Fabolous                                  Make Me Better\n       tempo             genre\n1047 126.091 hip hop, pop, R&B\n1643 139.956         pop, rock\n1968  75.445           hip hop\n476  127.932          pop, R&B\n738   86.491 hip hop, pop, R&B\n```\n:::\n:::\n\n\n\n# Random Variables\n\n---\n\n> How likely is it that none of the songs are classified in the genre \"pop\"? \n> How likely is it that at most three songs are classified in the genre \"pop\"?\n\nHow can we connect these questions about our data to the concepts of sample spaces and events to answer these question? The link can be made using <span style=\"color:dodgerblue\">**random variables**</span>!\n\n## Definition of a Random Variable\n\n---\n\nA <span style=\"color:dodgerblue\">**random variable**</span> is a function that maps each outcome $\\omega$ in the sample space $\\Omega$ to a real number $X(\\omega)$.\n\n$$ X: \\Omega \\to \\mathbb{R} $$\n\nIn the music playlist example, each playlist is a different outcome in the sample space. There are a total of $2000^5 = 3.2 \\times 10^{16}$ possible playlists in the sample space.\n\n- We can define random variable $X$ to be the number of songs in the playlist from the pop genre.\n  - For example, we could randomly select 5 songs with genres $\\omega =$ (hip hop, country, pop, rock, pop)\n  - Random variable $X$ is $X(\\omega) = 2$ since there are 2 pop songs in the playlist.\n- The set of possible values for $X$ is the <span style=\"color:dodgerblue\">**discrete**</span> set $\\left\\{ 0, 1, 2, 3, 4, 5 \\right\\}$.\n\n\n### Counting Pop Songs\n\n---\n\nOne potential tricky issue with song genre is many songs are classified in multiple genres. The blink-182 song *All The Small Things* is in both the pop and rock genres. To simplify the analysis here, we will count songs that are only classified in pop genre (and no other genres). We will not count *All The Small Things* as a pop song since it is also classified as rock.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(hits$genre == \"pop\")  # counts number of songs classified as only pop\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 428\n```\n:::\n:::\n\n\n- The `hits` data frame contains 428 pop songs.\n- The proportion of all songs that are pop songs is $\\frac{428}{2000} = 0.214$ or $21.4\\%$.\n\n## Question 2\n\n---\n\nIf $21.4\\%$ of all the songs are classified solely in the genre pop: \n\n- Compute $P(X=0)$, the probability of picking (with replacement) a random playlist of 5 songs that contains no pop songs.\n- Compute $P(X=5)$, the probability of picking (with replacement) a random playlist of 5 songs all of which are pop songs.\n\nYou can use an R code cell to help with the calculation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# P(X = 0)\n\n\n# P(X=5)\n```\n:::\n\n\n### Solution to Question 2\n\n---\n\n\n\\\n\\\n\\\n\n\n# Distributions for Discrete Random Variables\n\n---\n\nIf $X$ is a <span style=\"color:dodgerblue\">**discrete**</span> random variable, we define the probability function or <span style=\"color:dodgerblue\">**probability distribution**</span> or <span style=\"color:dodgerblue\">**probability mass function (pmf)**</span> for $X$ by\n\n$$\\color{dodgerblue}{p(x) = P(X=x)}.$$\n\nIf $X$ is a discrete random variable, we define the <span style=\"color:dodgerblue\">**cumulative distribution function (cdf)**</span> as the function\n\n$$\\color{dodgerblue}{F(x)=P(X \\leq x) = \\sum_{k=\\rm{min \\ value}}^x p(k) }.$$\n\n\n## The PMF and CDF for the Number of Pop Songs\n\n---\n\nIn the case of counting the number of pop songs in a 5 song playlist, we can organize the values of the pmf $p(x)$ in a table.\n\n| $x$    | 0      | 1      | 2      | 3      | 4      | 5      | \n|--------|--------|--------|--------|--------|--------|--------|\n| $p(x)$ | 0.3000 | 0.4084 | 0.2224 | 0.0606 | 0.0082 | 0.0004 |\n\nFrom the pmf table above, we have the corresponding cdf below.\n\n| $x$    | 0      | 1      | 2      | 3      | 4      | 5      | \n|--------|--------|--------|--------|--------|--------|--------|\n| $F(x)$ | 0.3000 | 0.7084 | 0.9308 | 0.9914 | 0.9996 | 1      |\n\n\n## Question 3 \n\n---\n\nInterpret the practical meaning of $p(3) = 0.0606$ and $F(3) = 0.9914$.\n\n### Solution to Question 3\n\n---\n\n\n\\\n\\\n\\\n\n\n## Question 4\n\n---\n\nWhat is the probability of picking a playlist with at least 3 pop songs?\n\n### Solution to Question 4\n\n---\n\n\n\\\n\\\n\\\n\n\n### Plotting Distribution Functions\n\n--- \n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 5  # set number of trials n\np <- 0.241  # prob of success in a trial\nx <- 0:n  # vector from 0 to n=3\n\npar(mfrow=c(1, 2))\nplot(x, dbinom(x, size = n, prob = p), main = \"Graph of pmf\", xlab = \"Number of Pop Songs\", ylab = \"p(x)\")\nplot(x, pbinom(x, size = n, prob = p), type=\"s\", main = \"Graph of cdf\", xlab = \"Number of Pop Songs\", ylab = \"F(x)\")\n```\n\n::: {.cell-output-display}\n![](05-Intro-to-Random-Variables_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1, 1))\n```\n:::\n\n\n\n## Question 5\n\n---\n\nLet $X$ is a discrete random variable with pmf and cdf denoted $p(x)$ and $F(x)$, respectively. Determine if each statement is True or False.\n\na.  $0 \\leq p(x) \\leq 1$ for all $x$.\nb.  $0 \\leq F(x) \\leq 1$ for all $x$.\nc.  $\\displaystyle \\sum_{\\rm{all}\\  x} p(x) = 1$.\nd.  $\\displaystyle \\sum_{\\rm{all}\\  x} F(x) = 1$.\ne.  $\\displaystyle \\lim_{x \\to \\infty} p(x) = 1$.\nf.  $\\displaystyle \\lim_{x \\to \\infty} F(x) = 1$.\ng.  The pmf must be a nondecreasing function.\nh.  The cdf must be a nondecreasing function.\n\n### Solution to Question 5\n\n---\n\nList the properties (a)-(h) that are indeed TRUE.\n\n\n\\\n\\\n\\\n\n\n\n# Continuous Random Variables\n\n---\n\nDiscrete random variables map outcomes in the sample space to integers. In many situations we would like to consider mapping outcomes to a continuous interval of values, not just integers. For example, what is probability that randomly selected song has a tempo less than 82 beats per minute (BPM)?\n\n- The sample space $\\Omega$ consists of the set of all songs in `hits`.\n- $X: \\Omega \\to \\mathbb{R}$  where we map each selected song to its tempo (in BPM).\n- The range is now a continuous interval of real numbers representing the tempos of all songs in `hits`.\n\nUsing modern technology such as music sequencers tempo has become a very precise measurement. Tempo is an important characteristic in electronic dance music where accurate measurement of a tune’s BPM is important to DJ's when mixing music.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(hits$tempo)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  60.02   98.99  120.02  120.12  134.27  210.85 \n```\n:::\n:::\n\n\n- From the summary above, we see tempo is continuous measurement (it has decimal values) from a minimum of $60.02$ BPM to a maximum $210.85$ BPM.\n\n\n## Question 6\n\n---\n\nBelow is a histogram representing the distribution of tempos for the 2000 songs in `hits`. Approximate the value of $P(X < 85)$,  the probability that a randomly selected songs has a tempo less than 85 BPM.\n\n- **Experiment with the number of breaks to improve the accuracy of your approximation!**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a histogram\nhist(hits$tempo,  # vector of tempo measurements\n########################################################\n# Student To-Do: Adjust breaks\n########################################################\n     breaks = 10,  # number of bin ranges to use\n########################################################     \n     labels = TRUE,  # add count labels above each bar\n     xlab = \"Tempo (BPM)\",   # x-axis label\n     xaxt='n',  # turn off default x-axis ticks\n     yaxt='n',  # turn off default y-axis ticks\n     ylab = \"Frequency\",  # y-axis label\n     ylim = c(0,650),  # sets window for y-axis\n     main = \"Distribution of Tempos\",  # main label\n     col = \"steelblue\")  # fill color of bars\naxis(1, at = seq(60, 220, 10))  # set custom ticks on x-axis\naxis(2, at = seq(0, 650, 50))  # set custom ticks on y-axis\n```\n\n::: {.cell-output-display}\n![](05-Intro-to-Random-Variables_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n### Solution to Question 6\n\n---\n\n\n\\\n\\\n\\\n\n\n## Relative Frequency Histograms\n\n---\n\nOur initial frequency histogram of tempos in [Question 6] measured the count or frequency of songs that fall in each bin of the histogram. A <span style=\"color:dodgerblue\">**relative frequency histogram**</span> rescales the vertical axis to units **proportion per unit of $X$**. \n\n- We can create a relative frequency histogram by adding the option `freq = FALSE` in the `hist()` function.\n\n\n## Question 7\n\n---\n\nBased on the relative frequency histogram below, approximate the value of $P(X < 85)$, the probability that a randomly selected songs has a tempo less than 85 BPM.\n\na.  The option `freq = FALSE` is added to the `hist` command below. Run the code cell below and compare the result with the histogram above. What is different about the two histograms? What is similar? What are the units of the horizontal axis?\n\nb.  Using the output from the code cell below, approximate $P(X < 85)$.  *Hint: The area of each bar corresponds to the proportion of songs in `hits` that are in the corresponding bin range of tempos.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a histogram\nhist(hits$tempo,  # vector of tempo measurements\n     freq = FALSE,\n     breaks = 20,  # number of bin ranges to use\n     labels = TRUE,  # add count labels above each bar\n     xlab = \"Tempo (BPM)\",   # x-axis label\n     xaxt='n',  # turn off default x-axis ticks\n     yaxt='n',  # turn off default y-axis ticks\n     ylab = \"Relative Frequency\",  # y-axis label\n     ylim = c(0,0.025),  # sets window for y-axis\n     main = \"Distribution of Tempos\",  # main label\n     col = \"steelblue\")  # fill color of bars\naxis(1, at = seq(60, 220, 10))  # set custom ticks on x-axis\naxis(2, at = seq(0, 0.025, 0.005))  # set custom ticks on y-axis\n```\n\n::: {.cell-output-display}\n![](05-Intro-to-Random-Variables_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n### Solution to Question 7\n\n---\n\n\n\\\n\\\n\\\n\n\n## Density Plots\n\n---\n\n\nA <span style=\"color:dodgerblue\">**density plot**</span> can informally be considered as a relative frequency histogram where we choose incredibly small widths for each bin range. One way to create a density plot in R is to:\n\n1.  First convert the values of a quantitative variable to densities with the `density()` function.\n\n-   For more information, see [density help documentation](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/density).\n\n2.  Use the `plot()` function to plot the densities.\n\n-   For more advanced density plots see <https://r-graph-gallery.com/density-plot.html>.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# approximate densities and then plot\nplot(density(hits$tempo),  # convert to density and then plot\n     ylab = \"density (proportion per BPM)\",  # vertical axis label\n     xlab = \"Tempo (in BPM)\",  # horizontal axis label\n     main = \"Distribution of Song Tempos\")  # main title\n```\n\n::: {.cell-output-display}\n![](05-Intro-to-Random-Variables_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n### Reading a Density Plot\n\n---\n\nIf we want to use a density plot compute $P(X < 85)$, the probability that a random selected song in `hits` has a tempo less than 85 BPM:\n\n- <span style=\"color:dodgerblue\">**We approximate the AREA below the density curve over the interval from 0 to 85 BPM.**</span>\n-   If we have a theoretical model $f(x)$ for the density, <span style=\"color:dodgerblue\">**we can use definite integrals to compute these proportions!**</span>\n- Run the cod cell below to sketch an area corresponding to $P(X<85)$. There is nothing to edit in the code cell.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n###############################\n# Area representing P(X < 85)\n# Run code without editting\n##############################\nden <- density(hits$tempo)\n\nplot(den,  # plot density of tempo\n     ylab = \"density (proportion per BPM)\",  # vertical axis label\n     xlab = \"Tempo (in BPM)\",  # horizontal axis label\n     xaxt = 'n',  # turn off default x-axis ticks\n     main = \"Distribution of Song Tempos\")  # main title\n\n\n# Fill area from 0 to 85 BPM\nvalue <- 85\n\npolygon(c(den$x[den$x <= value ], value),\n        c(den$y[den$x <= value ], 0),\n        col = \"slateblue1\",\n        border = 1)\naxis(1, at = seq(0, value, value))  # set custom ticks on x-axis\n```\n\n::: {.cell-output-display}\n![](05-Intro-to-Random-Variables_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n# Continuous Probability Distributions\n\n----\n\n## Probability Density Function (pdf)\n\n---\n\nIf $X$ is a **continuous** random variable, the <span style=\"color:dodgerblue\">**probability density function (pdf)**</span>, denoted $f(x)$, satisfies the following properties:\n\n-   $f(x) \\geq 0$ for all $x$,\n-   $\\displaystyle \\int_{-\\infty}^{\\infty} f(x) = 1$, and\n-   $\\displaystyle P(a < x < b) = \\int_a^b f(x) \\, dx$\n\n\n## Cumulative Distribution Function (cdf)\n\n---\n\nIf $X$ is a **continuous** random variable, the <span style=\"color:dodgerblue\">**cumulative distribution function (cdf)**</span>, denoted $F(x)$, is\n\n$$\\color{dodgerblue}{F(x) = P(X < x) = \\int_{-\\infty}^x f(t) \\, dt}.$$\n\nThus we have the important relations between a pdf and cdf of a continuous random variable X: \n\n- <span style=\"color:mediumseagreen\">**The cdf $F(x)$ is an antiderivative of the pdf $f$.**</span>\n- <span style=\"color:tomato\">**The pdf $f(x)$ is the derivative of $F(x)$.**</span>\n\n## Question 8\n\n---\n\nThe figure below contains 8 plots of either a probability density function or a cumulative distribution function of a continuous random variable. Match each probability density function shown in (a)-(d) with a corresponding graph of a cumulative distribution function (I)-(IV). Explain how you determined your answers.\n\n\n![Image Credit: Adam Spiegler, \n[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0), via Wikimedia Commons](https://upload.wikimedia.org/wikipedia/commons/6/6e/05fig-match.png){fig-alt=\"Matching graphs of pdfs and cdfs.\"}\n\n\n### Solution to Question 8\n\n---\n\n\n| Graph (a) | Graph (b) | Graph (c) | Graph (d) |\n|-----------|-----------|-----------|-----------|\n| ??        | ??        | ??        | ??        |\n\n\n\n\\\n\\\n\\\n\n\n\n## Properties of Continuous Random Variables \n\n---\n\n## Question 9 \n\n---\n\nLet $X$ is a continuous random variable with pdf and cdf denoted $f(x)$ and $F(x)$, respectively. Determine if each statement is True or False.\n\na.  $0 \\leq f(x) \\leq 1$ for all $x$.\nb.  $0 \\leq F(x) \\leq 1$ for all $x$.\nc.  $\\displaystyle \\int_{\\infty}^{-\\infty} f(x) \\, dx= 1$.\nd.  $\\displaystyle \\int_{\\infty}^{-\\infty} F(x) \\, dx = 1$.\ne.  $\\displaystyle \\lim_{x \\to \\infty} f(x) = 1$.\nf.  $\\displaystyle \\lim_{x \\to \\infty} F(x) = 1$.\ng.  The pdf must be a nondecreasing function.\nh.  The cdf must be a nondecreasing function.\n\n### Solution to Question 9\n\n---\n\nList the properties (a)-(h) that are indeed TRUE.\n\n\n\\\n\\\n\\\n\n\n## Question 10\n\n---\n\nThe probability of a Lithium-ion battery failing at time $x$ (in years) is given by the probability density function below.\n\n$$f(x) = \\left\\{ \\begin{array}{ll}\n\\frac{1}{3}e^{-\\frac{x}{3}} & x \\geq 0 \\\\\n0 & \\mbox{otherwise}\n\\end{array} \\right.$$\n\n\n### Question 10a\n\n---\n\nCompute the probability that a Lithium-ion battery lasts more than 2 years.\n\n\n#### Solution to Question 10a\n\n---\n\n\n\\\n\\\n\\\n\n\n### Question 10b\n\n---\n\nInterpret the meaning of $P(X \\leq 3)$ and $P(X < 3)$.\n\n\n#### Solution to Question 10b\n\n---\n\n\n\\\n\\\n\\\n\n\n---\n\n![Creative Commons License](https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png) <nbsp>\n\n*Statistical Methods: Exploring the Uncertain* by [Adam Spiegler](https://github.com/CU-Denver-MathStats-OER/Statistical-Theory) is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).",
    "supporting": [
      "05-Intro-to-Random-Variables_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}