<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5.3: Bootstrapping Comparitive Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">5.3: Bootstrapping Comparitive Statistics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><a href="https://githubtocolab.com/CU-Denver-MathStats-OER/Statistical-Theory/blob/main/Chap5/18-Bootstrap-Other-Stats.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" class="img-fluid" alt="Open In Colab"></a> <nbsp></nbsp></p>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/5/50/18fig-match.png" class="img-fluid figure-img" style="width:25.0%" alt="Matched Pair Bubble People"></p>
<figcaption class="figure-caption">Credit: Openclipart, CC0, via <a href="https://commons.wikimedia.org/wiki/File:18fig-match.png">Wikimedia Commons</a></figcaption>
</figure>
</div>
<section id="a-recap-of-bootstrapping" class="level1">
<h1>A Recap of Bootstrapping</h1>
<hr>
<p>In this section, we will continue exploring bootstrap distributions. Thus far, we have analyzed statistical questions where bootstrapping different statistics has been constructive, such as a <a href="./16-Bootstrap-Dist.html#sec-jawboot">single sample mean</a> and a <a href="./17-Bootstrap-Confidence-Int.html#sec-bootprop">sample proportion</a>. In many situations, we wish to investigate the possible association between two or more variables. In these cases, comparing two or more sample statistics is more useful than a single mean or a single proportion.</p>
<p>For example, we investigated whether there is an association between the <a href="./17-Bootstrap-Confidence-Int.html#sec-smoking">smoking during pregnancy and birth weight of the baby</a>.</p>
<ul>
<li>A sample of <span class="math inline">\(n=189\)</span> new born babies are selected.</li>
<li>The smoking status of the pregnant parent and the birth weight (in grams) are recorded.
<ul>
<li>Out of the sample <span class="math inline">\(n_{\rm{no}} = 115\)</span> non-smokers, the average birth weight is <span class="math inline">\(\bar{x}_{\rm{no}} = 3055.7\)</span> grams.</li>
<li>Out of the sample <span class="math inline">\(n_{s} = 74\)</span> non-smokers, the average birth weight is <span class="math inline">\(\bar{x}_{s} = 2771.9\)</span> grams.</li>
</ul></li>
<li>Is the observed difference in sample means significant?</li>
</ul>
<p>We used a bootstrap distribution on a <a href="./17-Bootstrap-Confidence-Int.html#sec-bootdiffmean">difference of two independent sample means</a> to construct a bootstrap confidence interval to estimate the difference in mean birth weights to help determine whether a difference of <span class="math inline">\(0\)</span> is plausible or not.</p>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<hr>
<p>The data used in the smoking and birth weight analysis is from an observational study. We determined the observed <a href="./17-Bootstrap-Confidence-Int.html#sec-interpret">difference in sample means is significant</a>, and thus concluded smoking during pregnancy is likely associated with lower baby birth weights. However, with observational studies we should be mindful of confounding variables. Based on our analysis we can conclude smoking is associated with a change in birth weight, but not whether the smoking itself is the cause of the change in birth weight. What are some possible <a href="./01-Intro-to-Inference.html#sec-confounding">confounding variables</a>?</p>
<section id="solution-to-question-1" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-1">Solution to Question 1</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="designing-a-randomized-controlled-experiment" class="level2">
<h2 class="anchored" data-anchor-id="designing-a-randomized-controlled-experiment">Designing a Randomized Controlled Experiment</h2>
<hr>
<p>In order to see whether smoking during pregnancy causes lower birth weights, we could try to design a randomized controlled experiment. Designing such an experiment that is humane in this context might not be possible. For example, here is an example of a highly unethical experiment we would not implement in practice:</p>
<ul>
<li>Collect volunteers early in their pregnancy who agree to the conditions of the experiment.</li>
<li>Randomly assign each pregnant person to a smoking or non-smoking group.
<ul>
<li>Each person in the smoking group is required to smoke 1 pack of cigarettes per day.</li>
<li>Each person in the non-smoking group is forbidden from smoking any tobacco during pregnancy.</li>
</ul></li>
<li>Record the birth weight of each person’s baby.</li>
<li>Compare mean birth weights of the two groups (smokers and non-smokers).</li>
</ul>
<p>Although such an experiment does eliminate the impact of many confounding variables, it is not possible to conduct this experiment due to ethical concerns.</p>
</section>
<section id="collecting-pairs-of-data" class="level2">
<h2 class="anchored" data-anchor-id="collecting-pairs-of-data">Collecting Pairs of Data</h2>
<hr>
<p>Let’s consider one more study that we could use to help determine whether smoking during pregnancy is associated with lower birth weight. In this study, we solicit volunteers that have already given birth to two babies. During one of the pregnancies, the parent smoked. During the other pregnancy, they did not smoke. This study is ethical and controls for some confounding variables though not all. Below is hypothetical data from such a study. A sample of <span class="math inline">\(n=10\)</span> people volunteer to share their data with the researchers from which we have 10 different pairs of birth weights (in grams) summarized in the table below.</p>
<table class="table">
<colgroup>
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No Smoking</td>
<td>2750</td>
<td>2920</td>
<td>3860</td>
<td>3402</td>
<td>2282</td>
<td>3790</td>
<td>3586</td>
<td>3487</td>
<td>2920</td>
<td>2835</td>
</tr>
<tr class="even">
<td>Smoked</td>
<td>1790</td>
<td>2381</td>
<td>3940</td>
<td>3317</td>
<td>2125</td>
<td>2665</td>
<td>3572</td>
<td>3156</td>
<td>2721</td>
<td>2225</td>
</tr>
</tbody>
</table>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<hr>
<p>Using the data from this study, give a possible sample statistic that can be used to determine if smoking is associated with lower birth weight?</p>
<section id="solution-to-question-2" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-2">Solution to Question 2</h3>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data from study</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>no <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2750</span>, <span class="dv">2920</span>, <span class="dv">3860</span>, <span class="dv">3402</span>, <span class="dv">2282</span>, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>        <span class="dv">3790</span>, <span class="dv">3586</span>, <span class="dv">3487</span>, <span class="dv">2920</span>, <span class="dv">2835</span>)  <span class="co"># non-smoking births weights</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>smoker <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1790</span>, <span class="dv">2381</span>, <span class="dv">3940</span>, <span class="dv">3317</span>, <span class="dv">2125</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>            <span class="dv">2665</span>, <span class="dv">3572</span>, <span class="dv">3156</span>, <span class="dv">2721</span>, <span class="dv">2225</span>)  <span class="co"># matching smoking birth weight</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<hr>
<p>Devise a bootstrapping method that could be used to construct a bootstrap distribution for the comparison statistic you identified in <a href="#question-2">Question 2</a>.</p>
<section id="solution-to-question-3" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-3">Solution to Question 3</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
<section id="matched-pairs-design" class="level1">
<h1>Matched Pairs Design</h1>
<hr>
<p>Let’s recap and compare data sets from two different studies investigating potential side-effects of smoking during pregnancy:</p>
<p><span style="color:dodgerblue"><strong>Study A:</strong></span> There is a sample of 189 observations corresponding to 189 different pregnancies. For each observation, we have two values corresponding to smoking status and birth weight of baby. The sample is split based on whether or not the parent smoked during their pregnancy. For any single observation in the non-smoking group, there is no inherent connection to any of the observations in the smoking group. The non-smoker and smoker groups are <span style="color:dodgerblue"><strong>independent samples</strong></span>.</p>
<p><span style="color:dodgerblue"><strong>Study B:</strong></span> There is a sample of <span class="math inline">\(n=10\)</span> observations corresponding to <span class="math inline">\(10\)</span> different people who each gave birth to two children. During one of the pregnancies they smoked, and they did not smoke during the other. For each observation, we have two variables: birth weight of baby when they smoked and the birth weight of the baby during the non-smoking pregnancy. For any single observation in the non-smoker group of birth weights, there is exactly one observation (their sibling) in the smoker group of birth weights that naturally form a pair of observations. This is an example of a <span style="color:dodgerblue"><strong>matched pairs design</strong></span> since observations from each sample are matched based on a key variable. In this case, we pair non-smoking and smoking birth weights based on parent of the baby.</p>
</section>
<section id="boostrapping-with-matched-pairs" class="level1">
<h1>Boostrapping with Matched Pairs</h1>
<hr>
<p><strong>When we bootstrap matched pairs, we do not want to randomness to affect the natural pairing between the two samples!</strong> Below is an algorithm for bootstrapping matched pairs. In order to preserve the pairing of the smoking and non-smoking birth weights, we do a single resample from the original sample of differences as opposed to two resamples from two independent samples.</p>
<p>Given a <span style="color:dodgerblue"><strong>matched pairs sample</strong></span> of size <span class="math inline">\(n\)</span>:</p>
<ol type="1">
<li>For each pair calculate the difference.</li>
</ol>
<table class="table">
<colgroup>
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No Smoking</td>
<td>2750</td>
<td>2920</td>
<td>3860</td>
<td>3402</td>
<td>2282</td>
<td>3790</td>
<td>3586</td>
<td>3487</td>
<td>2920</td>
<td>2835</td>
</tr>
<tr class="even">
<td>Smoked</td>
<td>1790</td>
<td>2381</td>
<td>3940</td>
<td>3317</td>
<td>2125</td>
<td>2665</td>
<td>3572</td>
<td>3156</td>
<td>2721</td>
<td>2225</td>
</tr>
<tr class="odd">
<td><span style="color:tomato">Difference</span></td>
<td><span style="color:tomato">960</span></td>
<td><span style="color:tomato">539</span></td>
<td><span style="color:tomato">-80</span></td>
<td><span style="color:tomato">85</span></td>
<td><span style="color:tomato">157</span></td>
<td><span style="color:tomato">1125</span></td>
<td><span style="color:tomato">14</span></td>
<td><span style="color:tomato">331</span></td>
<td><span style="color:tomato">199</span></td>
<td><span style="color:tomato">610</span></td>
</tr>
</tbody>
</table>
<ol start="2" type="1">
<li><p>Consider the collection of <span class="math inline">\(n\)</span> differences as your original sample. We now focus on this single vector of differences.</p>
<ul>
<li>Our original sample of differences is <span class="math inline">\({\color{tomato}{\mathbf{x} = (960, 539, -80, \ldots , 199, 610)}}\)</span>.</li>
<li>We store the sample of differences in the vector <code>diff</code> in the code cell below.</li>
<li>The sample mean difference between matched pairs for the original data is stored in <code>obs.mean</code>.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>no <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2750</span>, <span class="dv">2920</span>, <span class="dv">3860</span>, <span class="dv">3402</span>, <span class="dv">2282</span>, </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>        <span class="dv">3790</span>, <span class="dv">3586</span>, <span class="dv">3487</span>, <span class="dv">2920</span>, <span class="dv">2835</span>)  <span class="co"># non-smoking birth weights</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>smoker <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1790</span>, <span class="dv">2381</span>, <span class="dv">3940</span>, <span class="dv">3317</span>, <span class="dv">2125</span>, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>            <span class="dv">2665</span>, <span class="dv">3572</span>, <span class="dv">3156</span>, <span class="dv">2721</span>, <span class="dv">2225</span>)  <span class="co"># matching smoking birth weight</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>diff <span class="ot">&lt;-</span> no <span class="sc">-</span> smoker  <span class="co"># storing the original sample of differences</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>obs.mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(diff)  <span class="co"># observed mean difference between matched pairs</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># print observed mean to screen</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>obs.mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 394</code></pre>
</div>
</div>
<ol start="3" type="1">
<li><p>Draw a resample of size <span class="math inline">\(n\)</span> with replacement from the sample of differences.</p>
<ul>
<li>We pick our resample from <code>diff</code>.</li>
<li>Do NOT bootstrap from vectors <code>no</code> or <code>smoker</code>.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>resamp <span class="ot">&lt;-</span> <span class="fu">sample</span>(diff, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>resamp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  199  -80   85  960  960 1125   85   85  610  610</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Compute the mean of the bootstrap resample of the differences between matched pairs.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(resamp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 463.9</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Repeat this many times and construct the bootstrap distribution for the sample mean difference between matched pairs.</li>
</ol>
<section id="question-4" class="level2">
<h2 class="anchored" data-anchor-id="question-4">Question 4</h2>
<hr>
<p>Follow the steps below to generate a bootstrap distribution for the mean difference between matched pairs of smoking and non-smoking birth weights. Then use the bootstrap distribution to obtain a 95% bootstrap percentile confidence interval for the mean difference between all matched pairs in the population.</p>
<section id="question-4a" class="level3">
<h3 class="anchored" data-anchor-id="question-4a">Question 4a</h3>
<hr>
<p>Complete the code cell below to construct a bootstrap distribution for the sample mean difference between matched pairs.</p>
<section id="solution-to-question-4a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4a">Solution to Question 4a</h4>
<hr>
<p>Replace the six <code>??</code> in the code cell below with appropriate code. Then run the completed code to generate a bootstrap distribution and mark the observed mean difference between matched pairs (in red) and the mean of the bootstrap distribution (in blue) with vertical lines.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>  <span class="co"># Number of bootstrap samples</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>boot.matched <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)  <span class="co"># create vector to store bootstrap proportions</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># for loop that creates bootstrap dist</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">sample</span>(??, <span class="at">size =</span> ??, <span class="at">replace =</span> ??)  <span class="co"># pick a bootstrap resample</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  boot.matched[i] <span class="ot">&lt;-</span> ??  <span class="co"># compute sample mean of matched pair differences</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.matched,  </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Sample Mean of Matched Pair Differenes"</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Matched Pairs"</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed mean difference between matched pairs</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ??, <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="co"># blue line at the center of bootstrap dist</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ??, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-4b" class="level3">
<h3 class="anchored" data-anchor-id="question-4b">Question 4b</h3>
<hr>
<p>Complete the code cell below to give a 95% bootstrap percentile confidence interval to estimate the mean difference between all matched pairs in the population. <em>Include units in your answer.</em></p>
<section id="solution-to-question-4b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4b">Solution to Question 4b</h4>
<hr>
<p><strong>Based on the output below, a 95% bootstrap percentile confidence interval is from ?? to ??.</strong></p>
<p><br><br>
<br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find cutoffs for 95% bootstrap CI</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>lower.matched<span class="fl">.95</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find lower cutoff</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>upper.matched<span class="fl">.95</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find upper cutoff</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print to screen</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>lower.matched<span class="fl">.95</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>upper.matched<span class="fl">.95</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-4c" class="level3">
<h3 class="anchored" data-anchor-id="question-4c">Question 4c</h3>
<hr>
<p>Interpret the practical meaning of your interval estimate in <a href="#question-4b">Question 4b</a>. Do you think it is plausible to conclude smoking does have an effect on the weight of a newborn? Explain why or why not.</p>
<section id="solution-to-question-4c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4c">Solution to Question 4c</h4>
<hr>
<p><br><br>
<br> <br></p>
</section>
</section>
</section>
</section>
<section id="bootstrapping-other-statistics" class="level1">
<h1>Bootstrapping Other Statistics</h1>
<hr>
<p>When constructing sampling distributions for with means and proportions, in addition to bootstrapping, we also have a theoretical model available with the Central Limit Theorem (CLT). For example, we when working with golden jackal data, we constructed a <a href="./16-Bootstrap-Dist.html#sec-jawboot">bootstrap distribution</a> to approximate the sampling distribution for the sample mean mandible length. Then we compared the bootstrap results to those obtained using the <a href="./16-Bootstrap-Dist.html#sec-jawclt">CLT for means</a>. However, not all statistics have a Central Limit Theorem or formulas we can use to model a sampling distribution.</p>
<ul>
<li>The bootstrap procedure may be used with a wide variety of other statistics, such as medians, variances, trimmed means, and ratios.</li>
<li><strong>We can construct a bootstrap distribution to estimate the sampling distribution for any statistic, even if there is no Central Limit Theorem.</strong></li>
</ul>
<section id="question-5" class="level2">
<h2 class="anchored" data-anchor-id="question-5">Question 5</h2>
<hr>
<p>A random sample of <span class="math inline">\(n=20\)</span> mandible jaw lengths (in mm) of golden jackals is stored in the vector <code>jaw.sample</code>. Run the code cell below to load the sample data, and then answer the questions that follow.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>jaw.sample <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">120</span>, <span class="dv">107</span>, <span class="dv">110</span>, <span class="dv">116</span>, <span class="dv">114</span>, <span class="dv">111</span>, <span class="dv">113</span>, <span class="dv">117</span>, <span class="dv">114</span>, <span class="dv">112</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                <span class="dv">110</span>, <span class="dv">111</span>, <span class="dv">107</span>, <span class="dv">108</span>, <span class="dv">110</span>, <span class="dv">105</span>, <span class="dv">107</span>, <span class="dv">106</span>, <span class="dv">111</span>, <span class="dv">111</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="question-5a" class="level3">
<h3 class="anchored" data-anchor-id="question-5a">Question 5a</h3>
<hr>
<p>Below is <a href="./16-Bootstrap-Dist.html#sec-jawboot">code we previously used</a> to create bootstrap distribution for the <strong>sample mean</strong> mandible length. Adjust the code to create a bootstrap distribution for the <strong>sample median</strong> mandible length. Then run the updated code cell to store the bootstrap medians in the vector named <code>boot.dist</code>. <em>No output will printed to the screen since the output is being stored in <code>boot.dist</code>.</em></p>
<section id="solution-to-question-5a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-5a">Solution to Question 5a</h4>
<hr>
<p>Adjust the code cell below to create a bootstrap distribution for the sample median.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>  <span class="co"># Number of bootstrap samples</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>boot.dist <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)  <span class="co"># create vector to store bootstrap stats</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># for loop that creates bootstrap dist</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">sample</span>(jaw.sample, <span class="dv">20</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)  <span class="co"># pick a bootstrap resample</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  boot.dist[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)  <span class="co"># compute mean of bootstrap resample</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-5b" class="level3">
<h3 class="anchored" data-anchor-id="question-5b">Question 5b</h3>
<hr>
<p>Using the bootstrap distribution <code>boot.dist</code> created in <a href="#question-5a">Question 5a</a>, give a 90% bootstrap percentile confidence interval for the median mandible length of all golden jackals. <em>Include units in your answer.</em></p>
<section id="solution-to-question-5b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-5b">Solution to Question 5b</h4>
<hr>
<p>Replace all four <code>??</code> in the code cell below with appropriate code. Then run the completed code to compute lower and upper cutoffs for a 90% bootstrap percentile confidence interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find cutoffs for 90% bootstrap CI</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>lower.median<span class="fl">.90</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find lower cutoff</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>upper.median<span class="fl">.90</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find upper cutoff</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print to screen</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>lower.median<span class="fl">.90</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>upper.median<span class="fl">.90</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Based on the output above, a 90% bootstrap percentile confidence interval for the median is from ?? to ??.</strong></p>
<p><br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="bootstrapping-ratios" class="level1">
<h1>Bootstrapping Ratios</h1>
<hr>
<p>When investigating the possible effect of smoking during pregnancy on birth weight, we initially used the <code>birthwt</code> data frame in the <code>MASS</code> package to construct a bootstrap distribution for the <span style="color:dodgerblue"><strong>difference of means (DoM)</strong></span>. From the bootstrap distribution, we obtained a confidence interval to estimate the difference in the mean birth weights between children of those that smoked and those that did not smoke during pregnancy. One possible 95% bootstrap percentile confidence interval for the difference of means is <span class="math inline">\(80 \mbox{ g} &lt; \mu_{\rm{non}} - \mu_{s} &lt; 486 \mbox{g }\)</span>.</p>
<ul>
<li>Since <span class="math inline">\(0\)</span> is not inside the interval estimate, it is not plausible that <span class="math inline">\(\mu_{\rm{non}} - \mu_{s} =0\)</span> g.</li>
<li>We can conclude that there is a difference in the mean birth weights of babies of smokers and non-smokers.</li>
</ul>
<p>Another comparative analysis we can do is compare the <span style="color:dodgerblue"><strong>ratio of means (RoM)</strong></span> instead of the difference of means. Let <span class="math inline">\(R = \dfrac{\mu_{\rm{non}}}{\mu_{\rm{s}}}\)</span> denote the ratio of population means. <span class="math inline">\(R\)</span> is unknown population parameter that we can analyze as follows:</p>
<ul>
<li>If <span class="math inline">\(R = \dfrac{\mu_{\rm{non}}}{\mu_{\rm{s}}} &gt; 1\)</span>, then <span class="math inline">\(\mu_{\rm{non}} &gt; \mu_{\rm{s}}\)</span>.</li>
<li>If <span class="math inline">\(R = \dfrac{\mu_{\rm{non}}}{\mu_{\rm{s}}} &lt; 1\)</span>, then <span class="math inline">\(\mu_{\rm{non}} &lt; \mu_{\rm{s}}\)</span>.</li>
<li>If <span class="math inline">\(R = \dfrac{\mu_{\rm{non}}}{\mu_{\rm{s}}} = 1\)</span>, then <span class="math inline">\(\mu_{\rm{non}} = \mu_{\rm{s}}\)</span>.</li>
</ul>
<p>Whether we use a difference or ratio of means can highlight or minimize certain characteristics of the data. With ratios, we generally get sample ratios close 1. With differences, we can get a large spread of values in the differences of sample means. Thus, one potentially nice outcome of using ratios is the magnitude of the sample statistics will be smaller and easier to compare with other ratios from other contexts that will also have values close to 1. Another nice advantage is the results are independent of the units we choose to measure birth weight. If we choose to measure birth weights in pounds instead of grams, birth weights will be closer to 7, 8, 9 pounds as opposed to values such as 2000 or 3000 grams. We get different confidence intervals for the difference in mean birth weights depending on whether we use grams or pounds. The bootstrap confidence intervals we get for a ratio of means will be the same regardless of the units for weight.</p>
</section>
<section id="sec-smoking" class="level1">
<h1>Case Study: Smoking and Birth Weights</h1>
<hr>
<p>Recall the data set <code>birthwt</code> from the <code>MASS</code> package we <a href="./17-Bootstrap-Confidence-Int.html#sec-smoking">worked with earlier</a>. In the code cell below, we load and clean the data in <code>birthwt</code>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you receive an error message when running the code cell below, then you do not have the <code>MASS</code> package installed.</p>
<ul>
<li>In the R console, run the command <code>install.packages("MASS")</code>.</li>
<li>Then rerun the code cell below.</li>
</ul>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)  <span class="co"># load MASS package</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>birthwt<span class="sc">$</span>smoke[birthwt<span class="sc">$</span>smoke <span class="sc">==</span> <span class="dv">0</span>]  <span class="ot">&lt;-</span> <span class="st">"no"</span>  <span class="co"># non-smokers assigned "no"</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>birthwt<span class="sc">$</span>smoke[birthwt<span class="sc">$</span>smoke <span class="sc">==</span> <span class="dv">1</span>]  <span class="ot">&lt;-</span> <span class="st">"smoker"</span>  <span class="co"># smokers assigned "smoker"</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>birthwt<span class="sc">$</span>smoke <span class="ot">&lt;-</span> <span class="fu">factor</span>(birthwt<span class="sc">$</span>smoke)  <span class="co"># convert smoke variable to categorical factor</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(birthwt<span class="sc">$</span>smoke)  <span class="co"># summary of data frame</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    no smoker 
   115     74 </code></pre>
</div>
</div>
<p>Before we can bootstrap, we next subset the original sample into two independent samples based on smoking status. <em>The output is stored in data frames <code>non</code> and <code>smoker</code>, and no output will be printed to the screen.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subset the sample into two independent samples</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>non <span class="ot">&lt;-</span> <span class="fu">subset</span>(birthwt, smoke <span class="sc">==</span> <span class="st">"no"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>smoker <span class="ot">&lt;-</span> <span class="fu">subset</span>(birthwt, smoke <span class="sc">==</span> <span class="st">"smoker"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="question-6" class="level2">
<h2 class="anchored" data-anchor-id="question-6">Question 6</h2>
<hr>
<p>Calculate the observed ratio of sample mean birth weights of smokers and non-smokers and store the value as <code>obs.ratio</code>.</p>
<section id="solution-to-question-6" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-6">Solution to Question 6</h3>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>obs.ratio <span class="ot">&lt;-</span> ??  <span class="co"># calculate the observed ratio of sample means</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>obs.ratio  <span class="co"># print observed ratio to screen  </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-7" class="level2">
<h2 class="anchored" data-anchor-id="question-7">Question 7</h2>
<hr>
<p>Follow the steps below to generate a bootstrap distribution for the <strong>ratio of sample mean birth weights</strong> for babies born to non-smokers compared to babies born to smokers. Then use the bootstrap distribution to obtain a 95% bootstrap percentile confidence interval to estimate the ratio in population means.</p>
<section id="question-7a" class="level3">
<h3 class="anchored" data-anchor-id="question-7a">Question 7a</h3>
<hr>
<p>Complete the code cell below to construct a bootstrap distribution for the ratio of the sample mean birth weights of babies born to non-smokers compared to babies born to smokers.</p>
<section id="solution-to-question-7a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-7a">Solution to Question 7a</h4>
<hr>
<p>Replace all nine <code>??</code> in the code cell below with appropriate code. Then run the completed code to generate a bootstrap distribution and mark the observed ratio of sample means (in red) and the mean of the bootstrap distribution (in blue) with vertical lines.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>  <span class="co"># Number of bootstrap samples</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>boot.rom <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)  <span class="co"># create vector to store bootstrap proportions</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># for loop that creates bootstrap dist</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  x.non <span class="ot">&lt;-</span> <span class="fu">sample</span>(??, <span class="at">size =</span> ??, <span class="at">replace =</span> ??)  <span class="co"># pick a bootstrap resample of non-smokers</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  x.smoker <span class="ot">&lt;-</span> <span class="fu">sample</span>(??, <span class="at">size =</span> ??, <span class="at">replace =</span> ??)  <span class="co"># pick a bootstrap resample of smokers</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  boot.rom[i] <span class="ot">&lt;-</span> ??  <span class="co"># compute ratio of sample means</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.rom,  </span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Ratio = x.bar.non/x.bar.smoker"</span>,</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Ratio of Means"</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed  difference in sample means</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ??, <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a><span class="co"># blue line at the center of bootstrap dist</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ??, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-7b" class="level3">
<h3 class="anchored" data-anchor-id="question-7b">Question 7b</h3>
<hr>
<p>Complete the code cell below to give a 95% bootstrap percentile confidence interval to estimate the ratio of the mean birth weight of all babies born to non-smokers compared the to mean birth of all babies born to smokers.</p>
<section id="solution-to-question-7b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-7b">Solution to Question 7b</h4>
<hr>
<p><strong>Based on the output below, a 95% bootstrap percentile confidence interval is from ?? to ??.</strong></p>
<p><br><br>
<br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find cutoffs for 95% bootstrap CI</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>lower.rom<span class="fl">.95</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find lower cutoff</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>upper.rom<span class="fl">.95</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find upper cutoff</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print to screen</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>lower.rom<span class="fl">.95</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>upper.rom<span class="fl">.95</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-7c" class="level3">
<h3 class="anchored" data-anchor-id="question-7c">Question 7c</h3>
<hr>
<p>Interpret the practical meaning of your interval estimate in <a href="#question-7b">Question 7b</a>. Do you think it is plausible to conclude smoking does have an effect on the weight of a newborn? Explain why or why not.</p>
<section id="solution-to-question-7c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-7c">Solution to Question 7c</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-7d" class="level3">
<h3 class="anchored" data-anchor-id="question-7d">Question 7d</h3>
<hr>
<p>Is the shape of the bootstrap distribution for the ratio of means normal? Create a QQ-Plot to compare the bootstrap distribution to a standard normal distribution.</p>
<section id="solution-to-question-7d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-7d">Solution to Question 7d</h4>
<hr>
<p>Replace each <code>??</code> with appropriate code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(??)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(??)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interpret-the-plot-above-to-answer-the-question." class="level4">
<h4 class="anchored" data-anchor-id="interpret-the-plot-above-to-answer-the-question.">Interpret the plot above to answer the question.</h4>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="comparing-the-bias-of-bootstrap-estimators" class="level1">
<h1>Comparing the Bias of Bootstrap Estimators</h1>
<hr>
<p>Recall if <span class="math inline">\(\widehat{\theta}\)</span> is an estimator for a parameter <span class="math inline">\(\theta\)</span>, then we define the <strong>bias</strong> of the estimator as</p>
<p><span class="math display">\[\mbox{Bias}(\widehat{\theta}) = (\mbox{Estimated Value}) - (\mbox{Actual Value}) = \widehat{\theta} - \theta.\]</span></p>
<p><strong>In the case of bootstrapping, we used the following estimate:</strong></p>
<ul>
<li>We use the <span style="color:dodgerblue">center of the bootstrap distribution</span>, <span class="math inline">\({\color{dodgerblue}{\hat{\theta}_{\rm{boot}}}}\)</span>, as the <span style="color:dodgerblue">bootstrap estimator</span>.</li>
<li>We plug-in the <span style="color:tomato">statistic from the original sample</span> in place of the <span style="color:tomato">unknown parameter <span class="math inline">\(\theta\)</span></span>.</li>
<li>The <span style="color:dodgerblue"><strong>bootstrap estimate of bias</strong></span> is</li>
</ul>
<p><span class="math display">\[\mbox{Bias}_{\rm{boot}} \big( \hat{\theta}_{\rm{boot}} \big) = {\color{dodgerblue}{\hat{\theta}_{\rm{boot}}}} - {\color{tomato}{(\mbox{observed statistic})}}.\]</span></p>
<section id="question-8" class="level2">
<h2 class="anchored" data-anchor-id="question-8">Question 8</h2>
<hr>
<p>The code cell below constructs a bootstrap distribution for the sample mean from the sample data stored in <code>jaw.sample</code>. The corresponding bootstrap sample means are stored in the vector <code>boot.dist</code>.</p>
<ul>
<li>Read the code cell below.</li>
<li>After interpreting the code, run the code cell. No edits are needed.</li>
<li>In the code cell provided in the solution space, calculate the bootstrap estimate of bias.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the case of bootstrap estimate for a mean, we have <span class="math inline">\({\displaystyle \mbox{Bias}_{\rm{boot}} \big( \hat{\mu}_{\rm{boot}} \big) = {\color{dodgerblue}{\hat{\mu}_{\rm{boot}}}} - {\color{tomato}{\bar{x}}}}\)</span>. Use the output from the code below to identify the values of <span class="math inline">\({\color{dodgerblue}{\hat{\mu}_{\rm{boot}}}}\)</span> and <span class="math inline">\({\color{tomato}{\bar{x}}}\)</span>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">##############################</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># no edits needed</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># read and run the code</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="do">#############################</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>jaw.sample <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">120</span>, <span class="dv">107</span>, <span class="dv">110</span>, <span class="dv">116</span>, <span class="dv">114</span>, <span class="dv">111</span>, <span class="dv">113</span>, <span class="dv">117</span>, <span class="dv">114</span>, <span class="dv">112</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>                <span class="dv">110</span>, <span class="dv">111</span>, <span class="dv">107</span>, <span class="dv">108</span>, <span class="dv">110</span>, <span class="dv">105</span>, <span class="dv">107</span>, <span class="dv">106</span>, <span class="dv">111</span>, <span class="dv">111</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>  <span class="co"># Number of bootstrap samples</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>boot.dist <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)  <span class="co"># create vector to store bootstrap stats</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co"># for loop that creates bootstrap dist</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">sample</span>(jaw.sample, <span class="dv">20</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)  <span class="co"># pick a bootstrap resample</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  boot.dist[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)  <span class="co"># compute mean of bootstrap resample</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.dist,  </span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"x-bar, mandible length (in mm)"</span>,</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Sample Mean (n=20)"</span>)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="co"># bootstrap mean and standard error</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>boot.dist.mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(boot.dist)  <span class="co"># mean of bootstrap dist</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>boot.dist.se <span class="ot">&lt;-</span> <span class="fu">sd</span>(boot.dist)  <span class="co"># SE of bootstrap dist</span></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed sample mean</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">mean</span>(jaw.sample), <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a><span class="co"># blue line at the center of bootstrap dist</span></span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> boot.dist.mean, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="18-Bootstrap-Other-Stats_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="solution-to-question-8" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-8">Solution to Question 8</h3>
<hr>
<p>Replace the <code>??</code> in the code cell below to calculate and store bootstrap estimate of bias to <code>bias.jaw</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate bootstrap estimate of bias</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>bias.jaw <span class="ot">&lt;-</span> ?? </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>bias.jaw  <span class="co"># print to screen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-9" class="level2">
<h2 class="anchored" data-anchor-id="question-9">Question 9</h2>
<hr>
<p>Recall the data set <code>environmental</code> from the <code>lattice</code> package we <a href="./17-Bootstrap-Confidence-Int.html#sec-ozone">worked with earlier</a> to estimate the proportion of all time in New York City when the ozone concentration exceeds 70 ppb. In the code cell below, we load the <code>lattice</code> package and store the sample of ozone concentrations to a vector named <code>nyc.oz</code>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you receive an error message when running the code cell below, then you do not have the <code>lattice</code> package installed.</p>
<ul>
<li>In the R console, run the command <code>install.packages("lattice")</code>.</li>
<li>Then rerun the code cell below.</li>
</ul>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># be sure you have already installed the lattice package</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)  <span class="co"># loading lattice package</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>nyc.oz <span class="ot">&lt;-</span> environmental<span class="sc">$</span>ozone  <span class="co"># store ozone data to a vector</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code cell below constructs a bootstrap distribution for the sample proportion of time the ozone concentration exceeds 70 ppb using the original sample <code>nyc.oz</code>. The corresponding bootstrap sample proportions are stored in the vector <code>boot.prop</code>.</p>
<ul>
<li>Read the code cell below.</li>
<li>After interpreting the code, run the code cell. No edits are needed.</li>
<li>In the code cell provided in the solution space, calculate the bootstrap estimate of bias.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the case of bootstrap estimate for a proportion, we have <span class="math inline">\({\displaystyle\mbox{Bias}_{\rm{boot}} \big( \hat{p}_{\rm{boot}} \big) = {\color{dodgerblue}{\hat{p}_{\rm{boot}}}} - {\color{tomato}{\hat{p}}}}\)</span>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="do">##############################</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># no edits needed</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># read and run the code</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="do">#############################</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>  <span class="co"># Number of bootstrap samples</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>boot.prop <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)  <span class="co"># create vector to store bootstrap proportions</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>n.oz <span class="ot">&lt;-</span> <span class="fu">length</span>(nyc.oz)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co"># for loop that creates bootstrap dist</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">sample</span>(nyc.oz, <span class="at">size =</span> n.oz, <span class="at">replace =</span> <span class="cn">TRUE</span>)  <span class="co"># pick a bootstrap resample</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  boot.prop[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(x <span class="sc">&gt;</span> <span class="dv">70</span>)<span class="sc">/</span>n.oz  <span class="co"># compute bootstrap sample proportion</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.prop,  </span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"p-hat, sample proportion"</span>,</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Sample Proportion"</span>)</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="co"># bootstrap mean and standard error</span></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>boot.prop.mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(boot.prop)  <span class="co"># mean of bootstrap dist</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>boot.prop.se <span class="ot">&lt;-</span> <span class="fu">sd</span>(boot.prop)  <span class="co"># SE of bootstrap dist</span></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed sample proportion</span></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">sum</span>(nyc.oz <span class="sc">&gt;</span> <span class="dv">70</span>)<span class="sc">/</span>n.oz, <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a><span class="co"># blue line at the center of bootstrap dist</span></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> boot.prop.mean, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="18-Bootstrap-Other-Stats_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="solution-to-question-9" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-9">Solution to Question 9</h3>
<hr>
<p>Replace the <code>??</code> in the code cell below to calculate and store bootstrap estimate of bias to <code>bias.ozone</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate bootstrap estimate of bias</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>bias.ozone <span class="ot">&lt;-</span> ??</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>bias.ozone  <span class="co"># print to screen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-10" class="level2">
<h2 class="anchored" data-anchor-id="question-10">Question 10</h2>
<hr>
<p>Recall the data set <code>birthwt</code> from the <code>MASS</code> package we <a href="./17-Bootstrap-Confidence-Int.html#sec-smoking">worked with earlier</a>. In the code cell below, we load and clean the data in <code>birthwt</code>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you receive an error message when running the code cell below, then you do not have the <code>MASS</code> package installed.</p>
<ul>
<li>In the R console, run the command <code>install.packages("MASS")</code>.</li>
<li>Then rerun the code cell below.</li>
</ul>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)  <span class="co"># load MASS package</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>birthwt<span class="sc">$</span>smoke[birthwt<span class="sc">$</span>smoke <span class="sc">==</span> <span class="dv">0</span>]  <span class="ot">&lt;-</span> <span class="st">"no"</span>  <span class="co"># non-smokers assigned "no"</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>birthwt<span class="sc">$</span>smoke[birthwt<span class="sc">$</span>smoke <span class="sc">==</span> <span class="dv">1</span>]  <span class="ot">&lt;-</span> <span class="st">"smoker"</span>  <span class="co"># smokers assigned "smoker"</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>birthwt<span class="sc">$</span>smoke <span class="ot">&lt;-</span> <span class="fu">factor</span>(birthwt<span class="sc">$</span>smoke)  <span class="co"># convert smoke variable to categorical factor</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># subset the sample into two independent samples</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>non <span class="ot">&lt;-</span> <span class="fu">subset</span>(birthwt, smoke <span class="sc">==</span> <span class="st">"no"</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>smoker <span class="ot">&lt;-</span> <span class="fu">subset</span>(birthwt, smoke <span class="sc">==</span> <span class="st">"smoker"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code cell below constructs a bootstrap distribution for the difference in two sample means using the independent samples stored in the data frames <code>non</code> and <code>smoker</code>. The corresponding bootstrap difference in sample means are stored in the vector <code>boot.dom</code>.</p>
<ul>
<li>Read the code cell below.</li>
<li>After interpreting the code, run the code cell. No edits are needed.</li>
<li>In the code cell provided in the solution space, calculate the bootstrap estimate of bias.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="do">##############################</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># no edits needed</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># read and run the code</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="do">#############################</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>  <span class="co"># Number of bootstrap samples</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>boot.dom <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)  <span class="co"># create vector to store bootstrap proportions</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>m.non <span class="ot">&lt;-</span> <span class="fu">length</span>(non<span class="sc">$</span>bwt)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>n.smoker <span class="ot">&lt;-</span> <span class="fu">length</span>(smoker<span class="sc">$</span>bwt)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="co"># for loop that creates bootstrap dist</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  x.non <span class="ot">&lt;-</span> <span class="fu">sample</span>(non<span class="sc">$</span>bwt, <span class="at">size =</span> m.non, <span class="at">replace =</span> <span class="cn">TRUE</span>)  <span class="co"># pick a bootstrap resample</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>  x.smoker <span class="ot">&lt;-</span> <span class="fu">sample</span>(smoker<span class="sc">$</span>bwt, <span class="at">size =</span> n.smoker, <span class="at">replace =</span> <span class="cn">TRUE</span>)  <span class="co"># pick a bootstrap resample</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>  boot.dom[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(x.non) <span class="sc">-</span> <span class="fu">mean</span>(x.smoker)  <span class="co"># compute difference in sample means</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.dom,  </span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"x.bar.non - x.bar.smoker (in grams)"</span>,</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Difference in Means"</span>)</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a><span class="co"># bootstrap mean and standard error</span></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>boot.dom.mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(boot.dom)  <span class="co"># mean of bootstrap dist</span></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>boot.dom.se <span class="ot">&lt;-</span> <span class="fu">sd</span>(boot.dom)  <span class="co"># SE of bootstrap dist</span></span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed  difference in sample means</span></span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">mean</span>(non<span class="sc">$</span>bwt) <span class="sc">-</span> <span class="fu">mean</span>(smoker<span class="sc">$</span>bwt), <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a><span class="co"># blue line at the center of bootstrap dist</span></span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> boot.dom.mean, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="18-Bootstrap-Other-Stats_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="solution-to-question-10" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-10">Solution to Question 10</h3>
<hr>
<p>Replace the <code>??</code> in the code cell below to calculate and store bootstrap estimate of bias to <code>bias.smoke</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate bootstrap estimate of bias</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>bias.smoke <span class="ot">&lt;-</span> ??</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>bias.smoke  <span class="co"># print to screen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-11" class="level2">
<h2 class="anchored" data-anchor-id="question-11">Question 11</h2>
<hr>
<p>Out of the three bootstrap estimates of bias in <a href="#question-8">Question 8</a>, <a href="#question-9">Question 9</a>, and <a href="#question-10">Question 10</a>, which bias is the most extreme?</p>
<section id="solution-to-question-11" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-11">Solution to Question 11</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="rule-of-thumb-for-acceptable-bias" class="level2">
<h2 class="anchored" data-anchor-id="rule-of-thumb-for-acceptable-bias">Rule of Thumb for Acceptable Bias</h2>
<hr>
<p>What is a significant amount of bias? The answer to this question does not depend on the bootstrap estimate of bias alone. We need to consider how much bias is present relative to the overall variability in sample statistics. For example:</p>
<ul>
<li>If the bootstrap estimate of bias is <span class="math inline">\(5\)</span> and <span class="math inline">\(\mbox{SE}_{\rm{boot}} = 5,\!000\)</span>, then relatively speaking the bias is quite small.</li>
<li>If the bootstrap estimate of bias is <span class="math inline">\(-0.1\)</span> and <span class="math inline">\(\mbox{SE}_{\rm{boot}} = 2\)</span>, then relatively speaking the bias is much larger.</li>
<li>We compare the value of the bootstrap estimate of bias <strong>relative to the bootstrap standard error</strong>.
<ul>
<li>In the first example, we have the ratio <span class="math inline">\(\frac{5}{5000} = 0.001\)</span>.</li>
<li>In the second example, we have a ratio <span class="math inline">\(\frac{-0.1}{2} = -0.05\)</span></li>
</ul></li>
<li>In general, we use the ratio of the bootstrap bias to the bootstrap standard error to measure how significant is the bias.</li>
</ul>
<p><span class="math display">\[{\color{dodgerblue}{\boxed{ \mbox{Relative Bootstrap Bias} = \dfrac{\mbox{Bootstrap Bias}}{\mbox{Bootstrap SE}}}}}\]</span></p>
<section id="rule-of-thumb-for-bootstrap-bias" class="level4">
<h4 class="anchored" data-anchor-id="rule-of-thumb-for-bootstrap-bias"><span style="color:dodgerblue"><strong>Rule of Thumb for Bootstrap Bias</strong></span></h4>
<hr>
<p><span style="color:dodgerblue">If either </span></p>
<p><span class="math display">\[{\color{dodgerblue}{\frac{\mbox{Bootstrap Bias}}{\mbox{Bootstrap SE}}  &gt; 0.02 \qquad \mbox{or} \qquad \frac{\mbox{Bootstrap Bias}}{\mbox{Bootstrap SE}}  &lt; -0.02,}}\]</span></p>
<p><span style="color:dodgerblue">then the bias is large enough to have a substantial effect on the accuracy of the estimate.</span></p>
</section>
</section>
<section id="question-12" class="level2">
<h2 class="anchored" data-anchor-id="question-12">Question 12</h2>
<hr>
<p>Determine whether the jackal mandible bootstrap distribution in <a href="#question-8">Question 8</a>, the ozone concentration bootstrap distribution for sample proportion in <a href="#question-9">Question 9</a>, or the bootstrap distribution for the difference in mean birth weights <a href="#question-10">Question 10</a> exceed the 0.02 rule of thumb? Relatively speaking, which of the three biases is most extreme?</p>
<section id="solution-to-question-12" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-12">Solution to Question 12</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
<hr>
<p><img src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" class="img-fluid" alt="Creative Commons License"> <nbsp></nbsp></p>
<p><em>Statistical Methods: Exploring the Uncertain</em> by <a href="https://github.com/CU-Denver-MathStats-OER/Statistical-Theory">Adam Spiegler</a> is licensed under a <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>