<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Methods: Exploring the Uncertain - 5.4: Parametric Confidence Intervals for Means</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./20-Parametric-CI-Proportions.html" rel="next">
<link href="./18-Bootstrap-Other-Stats.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./16-Bootstrap-Dist.html">Chapter 5: Interval Estimates</a></li><li class="breadcrumb-item"><a href="./19-Parametric-CI-Means.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">5.4: Parametric Confidence Intervals for Means</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Methods: Exploring the Uncertain</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Chapter 1: Exploring Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Intro-to-Inference.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.1: Introduction to Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-EDA-Categorical.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2: Exploring Categorical Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-EDA-Quantitative.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.3: Exploring Quantitative Data</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Chapter 2: Probability Essentials</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Overview-of-Probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.1: An Overview of Probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Intro-to-Random-Variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.2: Introduction to Random Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Expected-Value-and-Variance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.3: Expected Value and Variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Common-Discrete-RandVar.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.4: Common Discrete Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-Common-Continuous-Distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.5: Common Continuous Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Joint-Distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.6: Joint Distributions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Chapter 3: Sampling Distributions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-Sampling-Dist-Mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.1: Sampling Distribution of Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-Sampling-Dist-Prop.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.2: Sampling Distributions for Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-Sampling-Dist-Other.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.3: Sampling Distributions of Other Statistics</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Chapter 4: Estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Estimation-MLE.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.1: Maximum Likelihood Estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-Estimation-MOM.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.2: Method of Moments Estimates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-Properties-Estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.3: Properties of Estimators</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Chapter 5: Interval Estimates</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-Bootstrap-Dist.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.1: Bootstrap Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-Bootstrap-Confidence-Int.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.2: Bootstrap Confidence Intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-Bootstrap-Other-Stats.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.3: Bootstrapping Comparitive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-Parametric-CI-Means.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">5.4: Parametric Confidence Intervals for Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-Parametric-CI-Proportions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.5: Parametric Confidence Intervals for Proportions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Chapter 6: Hypothesis Tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-Intro-Hypothesis-Tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.1: Introduction to Hypothesis Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-Permutation-Tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.2: Permutation Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-Hypothesis-Single-Population.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.3: Parametric Hypothesis Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-Hypothesis-Comparing-Two.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.4: Parametric Tests for Two Populations</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Installing-R-and-RStudio.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Installing R and RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Intro-to-Vectors-Dataframes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fundamentals of Working with Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Overview-of-Plots.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">An Overview of Plotting Data in R</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#parametric-and-non-parametric-methods" id="toc-parametric-and-non-parametric-methods" class="nav-link active" data-scroll-target="#parametric-and-non-parametric-methods">Parametric and Non-Parametric Methods</a></li>
  <li><a href="#sec-storm" id="toc-sec-storm" class="nav-link" data-scroll-target="#sec-storm">Case Study: Average Wind Speed of Storms</a>
  <ul class="collapse">
  <li><a href="#loading-storms-data" id="toc-loading-storms-data" class="nav-link" data-scroll-target="#loading-storms-data">Loading Storms Data</a></li>
  <li><a href="#picking-a-random-sample-of-storms" id="toc-picking-a-random-sample-of-storms" class="nav-link" data-scroll-target="#picking-a-random-sample-of-storms">Picking a Random Sample of Storms</a></li>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a>
  <ul class="collapse">
  <li><a href="#solution-to-question-1" id="toc-solution-to-question-1" class="nav-link" data-scroll-target="#solution-to-question-1">Solution to Question 1</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a>
  <ul class="collapse">
  <li><a href="#solution-to-question-2" id="toc-solution-to-question-2" class="nav-link" data-scroll-target="#solution-to-question-2">Solution to Question 2</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#a-bootstrap-confidence-interval" id="toc-a-bootstrap-confidence-interval" class="nav-link" data-scroll-target="#a-bootstrap-confidence-interval">A Bootstrap Confidence Interval</a></li>
  <li><a href="#sec-param" id="toc-sec-param" class="nav-link" data-scroll-target="#sec-param">A Parametric Method for Interval Estimates</a>
  <ul class="collapse">
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a>
  <ul class="collapse">
  <li><a href="#question-3a" id="toc-question-3a" class="nav-link" data-scroll-target="#question-3a">Question 3a</a></li>
  <li><a href="#question-3b" id="toc-question-3b" class="nav-link" data-scroll-target="#question-3b">Question 3b</a></li>
  <li><a href="#question-3c" id="toc-question-3c" class="nav-link" data-scroll-target="#question-3c">Question 3c</a></li>
  <li><a href="#question-3d" id="toc-question-3d" class="nav-link" data-scroll-target="#question-3d">Question 3d</a></li>
  </ul></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a>
  <ul class="collapse">
  <li><a href="#question-4a" id="toc-question-4a" class="nav-link" data-scroll-target="#question-4a">Question 4a</a></li>
  <li><a href="#question-4b" id="toc-question-4b" class="nav-link" data-scroll-target="#question-4b">Question 4b</a></li>
  <li><a href="#question-4c" id="toc-question-4c" class="nav-link" data-scroll-target="#question-4c">Question 4c</a></li>
  <li><a href="#question-4d" id="toc-question-4d" class="nav-link" data-scroll-target="#question-4d">Question 4d</a></li>
  <li><a href="#question-4e" id="toc-question-4e" class="nav-link" data-scroll-target="#question-4e">Question 4e</a></li>
  <li><a href="#question-4f" id="toc-question-4f" class="nav-link" data-scroll-target="#question-4f">Question 4f</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#confidence-interval-for-a-mean" id="toc-confidence-interval-for-a-mean" class="nav-link" data-scroll-target="#confidence-interval-for-a-mean">95% Confidence Interval for a Mean</a>
  <ul class="collapse">
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a>
  <ul class="collapse">
  <li><a href="#question-5a" id="toc-question-5a" class="nav-link" data-scroll-target="#question-5a">Question 5a</a></li>
  <li><a href="#question-5b" id="toc-question-5b" class="nav-link" data-scroll-target="#question-5b">Question 5b</a></li>
  <li><a href="#question-5c" id="toc-question-5c" class="nav-link" data-scroll-target="#question-5c">Question 5c</a></li>
  <li><a href="#question-5d" id="toc-question-5d" class="nav-link" data-scroll-target="#question-5d">Question 5d</a></li>
  <li><a href="#question-5e" id="toc-question-5e" class="nav-link" data-scroll-target="#question-5e">Question 5e</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#what-is-uncertain-and-what-is-unknown" id="toc-what-is-uncertain-and-what-is-unknown" class="nav-link" data-scroll-target="#what-is-uncertain-and-what-is-unknown">What is Uncertain and What is Unknown?</a></li>
  <li><a href="#interpreting-confidence-intervals" id="toc-interpreting-confidence-intervals" class="nav-link" data-scroll-target="#interpreting-confidence-intervals">Interpreting Confidence Intervals</a>
  <ul class="collapse">
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6">Question 6</a>
  <ul class="collapse">
  <li><a href="#question-6a" id="toc-question-6a" class="nav-link" data-scroll-target="#question-6a">Question 6a</a></li>
  <li><a href="#question-6b" id="toc-question-6b" class="nav-link" data-scroll-target="#question-6b">Question 6b</a></li>
  <li><a href="#question-6c" id="toc-question-6c" class="nav-link" data-scroll-target="#question-6c">Question 6c</a></li>
  <li><a href="#question-6d" id="toc-question-6d" class="nav-link" data-scroll-target="#question-6d">Question 6d</a></li>
  <li><a href="#question-6e" id="toc-question-6e" class="nav-link" data-scroll-target="#question-6e">Question 6e</a></li>
  </ul></li>
  <li><a href="#attaching-uncertainty-to-the-intervals" id="toc-attaching-uncertainty-to-the-intervals" class="nav-link" data-scroll-target="#attaching-uncertainty-to-the-intervals">Attaching Uncertainty to the Intervals</a></li>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7">Question 7</a>
  <ul class="collapse">
  <li><a href="#solution-to-question-7" id="toc-solution-to-question-7" class="nav-link" data-scroll-target="#solution-to-question-7">Solution to Question 7</a></li>
  </ul></li>
  <li><a href="#question-8" id="toc-question-8" class="nav-link" data-scroll-target="#question-8">Question 8</a>
  <ul class="collapse">
  <li><a href="#question-8a" id="toc-question-8a" class="nav-link" data-scroll-target="#question-8a">Question 8a</a></li>
  <li><a href="#question-8b" id="toc-question-8b" class="nav-link" data-scroll-target="#question-8b">Question 8b</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#changing-the-confidence-level" id="toc-changing-the-confidence-level" class="nav-link" data-scroll-target="#changing-the-confidence-level">Changing the Confidence Level</a></li>
  <li><a href="#confidence-intervals-when-the-variance-is-unknown" id="toc-confidence-intervals-when-the-variance-is-unknown" class="nav-link" data-scroll-target="#confidence-intervals-when-the-variance-is-unknown">Confidence Intervals When the Variance Is Unknown</a>
  <ul class="collapse">
  <li><a href="#the-t-distribution" id="toc-the-t-distribution" class="nav-link" data-scroll-target="#the-t-distribution">The <span class="math inline">\(t\)</span>-Distribution</a></li>
  <li><a href="#using-a-t-distribution-when-variance-is-unknown" id="toc-using-a-t-distribution-when-variance-is-unknown" class="nav-link" data-scroll-target="#using-a-t-distribution-when-variance-is-unknown">Using a <span class="math inline">\(t\)</span>-Distribution When Variance is Unknown</a></li>
  <li><a href="#question-9" id="toc-question-9" class="nav-link" data-scroll-target="#question-9">Question 9</a>
  <ul class="collapse">
  <li><a href="#question-9a" id="toc-question-9a" class="nav-link" data-scroll-target="#question-9a">Question 9a</a></li>
  <li><a href="#question-9b" id="toc-question-9b" class="nav-link" data-scroll-target="#question-9b">Question 9b</a></li>
  <li><a href="#question-9c" id="toc-question-9c" class="nav-link" data-scroll-target="#question-9c">Question 9c</a></li>
  </ul></li>
  <li><a href="#different-methods-for-t-distribution-confidence-intervals" id="toc-different-methods-for-t-distribution-confidence-intervals" class="nav-link" data-scroll-target="#different-methods-for-t-distribution-confidence-intervals">Different Methods for <span class="math inline">\(t\)</span>-Distribution Confidence Intervals</a></li>
  <li><a href="#question-10" id="toc-question-10" class="nav-link" data-scroll-target="#question-10">Question 10</a>
  <ul class="collapse">
  <li><a href="#solution-to-question-10" id="toc-solution-to-question-10" class="nav-link" data-scroll-target="#solution-to-question-10">Solution to Question 10</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#confidence-interval-for-a-difference-in-two-means" id="toc-confidence-interval-for-a-difference-in-two-means" class="nav-link" data-scroll-target="#confidence-interval-for-a-difference-in-two-means">Confidence Interval for a Difference in Two Means</a>
  <ul class="collapse">
  <li><a href="#sec-clt-diff-means" id="toc-sec-clt-diff-means" class="nav-link" data-scroll-target="#sec-clt-diff-means">Question 11</a>
  <ul class="collapse">
  <li><a href="#solution-to-question-11" id="toc-solution-to-question-11" class="nav-link" data-scroll-target="#solution-to-question-11">Solution to Question 11</a></li>
  </ul></li>
  <li><a href="#sec-informal" id="toc-sec-informal" class="nav-link" data-scroll-target="#sec-informal">Confidence Intervals for a Difference in Means</a></li>
  </ul></li>
  <li><a href="#which-month-has-the-strongest-storms" id="toc-which-month-has-the-strongest-storms" class="nav-link" data-scroll-target="#which-month-has-the-strongest-storms">Which Month Has the Strongest Storms?</a>
  <ul class="collapse">
  <li><a href="#question-12" id="toc-question-12" class="nav-link" data-scroll-target="#question-12">Question 12</a>
  <ul class="collapse">
  <li><a href="#solution-to-question-12" id="toc-solution-to-question-12" class="nav-link" data-scroll-target="#solution-to-question-12">Solution to Question 12</a></li>
  </ul></li>
  <li><a href="#refining-our-question" id="toc-refining-our-question" class="nav-link" data-scroll-target="#refining-our-question">Refining Our Question</a></li>
  <li><a href="#subsetting-into-two-independent-samples" id="toc-subsetting-into-two-independent-samples" class="nav-link" data-scroll-target="#subsetting-into-two-independent-samples">Subsetting into Two Independent Samples</a></li>
  <li><a href="#question-13" id="toc-question-13" class="nav-link" data-scroll-target="#question-13">Question 13</a>
  <ul class="collapse">
  <li><a href="#question-13a" id="toc-question-13a" class="nav-link" data-scroll-target="#question-13a">Question 13a</a></li>
  <li><a href="#question-13b" id="toc-question-13b" class="nav-link" data-scroll-target="#question-13b">Question 13b</a></li>
  <li><a href="#question-13c" id="toc-question-13c" class="nav-link" data-scroll-target="#question-13c">Question 13c</a></li>
  <li><a href="#question-13d" id="toc-question-13d" class="nav-link" data-scroll-target="#question-13d">Question 13d</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#using-t.test-for-a-difference-in-means" id="toc-using-t.test-for-a-difference-in-means" class="nav-link" data-scroll-target="#using-t.test-for-a-difference-in-means">Using <code>t.test()</code> for a Difference in Means</a>
  <ul class="collapse">
  <li><a href="#question-14" id="toc-question-14" class="nav-link" data-scroll-target="#question-14">Question 14</a>
  <ul class="collapse">
  <li><a href="#solution-to-question-14" id="toc-solution-to-question-14" class="nav-link" data-scroll-target="#solution-to-question-14">Solution to Question 14</a></li>
  </ul></li>
  <li><a href="#subsetting-with-t.test" id="toc-subsetting-with-t.test" class="nav-link" data-scroll-target="#subsetting-with-t.test">Subsetting with <code>t.test</code></a></li>
  <li><a href="#question-15" id="toc-question-15" class="nav-link" data-scroll-target="#question-15">Question 15</a>
  <ul class="collapse">
  <li><a href="#solution-to-question-15" id="toc-solution-to-question-15" class="nav-link" data-scroll-target="#solution-to-question-15">Solution to Question 15</a></li>
  </ul></li>
  <li><a href="#caution-using-t.test-for-a-difference-in-two-means" id="toc-caution-using-t.test-for-a-difference-in-two-means" class="nav-link" data-scroll-target="#caution-using-t.test-for-a-difference-in-two-means">Caution Using <code>t.test()</code> for a Difference in Two Means</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">5.4: Parametric Confidence Intervals for Means</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><a href="https://githubtocolab.com/CU-Denver-MathStats-OER/Statistical-Theory/blob/main/Chap5/19-Parametric-CI-Means.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" class="img-fluid" alt="Open In Colab"></a> <nbsp></nbsp></p>
<section id="parametric-and-non-parametric-methods" class="level1">
<h1>Parametric and Non-Parametric Methods</h1>
<hr>
<p>We have been investigating <a href="./16-Bootstrap-Dist.html">resampling methods</a> as a tool to estimate the variability in sample statistics. Statistics such as means and proportions are linear combinations of random variables, and using <a href="./06-Expected-Value-and-Variance.html#sec-prop-exp">theory from probability</a>, we are able the derive the <a href="./10-Sampling-Dist-Mean.html#sec-cltmeans">Central Limit Theorem (CLT) formulas</a> to model sampling distributions for means and proportions. In this section we will construct confidence intervals by applying a <em>parametric</em> approach that uses formulas from the CLT to measure the uncertainty (standard error) in our estimate.</p>
<ul>
<li>With <span style="color:dodgerblue"><strong>parametric methods</strong></span>, we perform inference using formulas derived from theory.</li>
<li>Monte Carlo methods such as bootstrap resampling are non-parametric.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For statistics that are not linear combinations of independent random variables (such as medians, variances, and ratios of means) deriving formulas to model the sampling distribution is more complicated or not even possible. We can try <a href="./18-Bootstrap-Other-Stats.html">bootstrapping in these situations</a> instead!</p>
</div>
</div>
</section>
<section id="sec-storm" class="level1">
<h1>Case Study: Average Wind Speed of Storms</h1>
<hr>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="https://cdn.pixabay.com/photo/2012/09/26/17/26/winter-storm-58025_1280.jpg" class="img-fluid figure-img" style="width:45.0%" alt="Satellite Image of Hurricane"></p>
<figcaption class="figure-caption">Credit: WikiImages, CC0 via <a href="https://pixabay.com/photos/hurricane-cyclone-typhoon-wind-58025/">Pixabay</a></figcaption>
</figure>
</div>
<p>Suppose a climatologist has contacted us for help estimating the average wind speed of all storms in the North Atlantic. They have collected a random sample of <span class="math inline">\(n=36\)</span> wind speeds from North Atlantic storms over the past 5 years.</p>
<section id="loading-storms-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-storms-data">Loading Storms Data</h2>
<hr>
<p>When practicing <a href="./03-EDA-Quantitative.html#sec-storms">exploratory data analysis earlier</a>, we accessed the <code>dplyr</code> package that contains a data set from the <a href="https://www.nhc.noaa.gov/data/#hurdat">NOAA Hurricane Best Track Data</a>, called <code>storms</code>, with data on many different storm attributes. We will begin analyzing the variable <code>wind</code> that gives the wind speed in knots. Run the code cell below to:</p>
<ul>
<li>Load the <code>dplyr</code> package (which should already be installed), and</li>
<li>Store the wind speeds to a new vector called <code>population</code>.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you receive an error message when running the code cell below, then you may not have the <code>dplyr</code> package installed.</p>
<ul>
<li>In the R console, run the command <code>install.packages("dplyr")</code>.</li>
<li>Then rerun the code cell below.</li>
</ul>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>population <span class="ot">&lt;-</span> storms<span class="sc">$</span>wind</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="picking-a-random-sample-of-storms" class="level2">
<h2 class="anchored" data-anchor-id="picking-a-random-sample-of-storms">Picking a Random Sample of Storms</h2>
<hr>
<p>When performing statistical inference, we do not have complete data from the entire population. We typically have data from one sample picked randomly from the population. Based on the sample data, we try to estimate unknown parameters for the population. To begin our exploration of confidence intervals, suppose the 19066 wind speeds in the <code>population</code> data represents the full population of all storms at all times in the North Atlantic. We investigate the following statistical question:</p>
<blockquote class="blockquote">
<p><span style="color:dodgerblue">What is the average wind speed of all storms in the North Atlantic, <span class="math inline">\(\mu_{\rm{wind}}\)</span>?</span></p>
</blockquote>
<ul>
<li>Assume we do not have access to all the <code>population</code> data and cannot directly calculate <span class="math inline">\(\mu_{\rm{wind}}\)</span>.</li>
<li>We will pick one random sample of 36 wind speeds from the <code>population</code>.</li>
<li>We will use our sample to estimate the mean wind speed of all storms in the North Atlantic.</li>
</ul>
</section>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<hr>
<p>Pick a random sample of <span class="math inline">\(n=36\)</span> wind speeds from the <code>population</code>. In picking your original sample, sample without replacement. Store your sample to a vector named <code>my.sample</code>.</p>
<section id="solution-to-question-1" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-1">Solution to Question 1</h3>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pick one random sample of 36 wind speeds without replacement</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>my.sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(??, <span class="at">size =</span> ??, <span class="at">replace =</span> ??)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<hr>
<p>Using the random sample <code>my.sample</code>, give a possible point estimate for <span class="math inline">\(\mu_{\rm{wind}}\)</span>, the mean wind speed of all storms in the North Atlantic. The parameter <span class="math inline">\(\mu_{\rm{wind}}\)</span> is unknown since we assume the full <code>population</code> data is not available.</p>
<section id="solution-to-question-2" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-2">Solution to Question 2</h3>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use your sample to give a point estimate</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
</section>
<section id="a-bootstrap-confidence-interval" class="level1">
<h1>A Bootstrap Confidence Interval</h1>
<hr>
<p>Before introducing parametric methods for constructing a confidence interval estimate, we first review resampling methods to construct a <a href="./16-Bootstrap-Dist.html">bootstrap distribution</a> from the sample <code>my.sample</code> that we can use to construct a <a href="./17-Bootstrap-Confidence-Int.html">bootstrap confidence interval</a>. The code below uses the original sample <code>my.sample</code> to generate a bootstrap distribution for the sample mean wind speed (with <span class="math inline">\(n=36\)</span>) that is stored in <code>boot.wind</code> for the next step.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you are not familiar with bootstrapping methods, but you would like to learn more about parametric methods, feel free to jump to the next section on <a href="#sec-param">parametric methods</a>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>  <span class="co"># Number of bootstrap samples</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>boot.wind <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)  <span class="co"># create vector to store bootstrap means</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">36</span>  <span class="co"># sample size</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># for loop that creates bootstrap dist</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">sample</span>(my.sample, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)  <span class="co"># pick a bootstrap resample</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  boot.wind[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)  <span class="co"># compute bootstrap sample mean</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>boot.wind.est <span class="ot">&lt;-</span> <span class="fu">mean</span>(boot.wind)  <span class="co"># mean of bootstrap dist</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>boot.wind.se <span class="ot">&lt;-</span> <span class="fu">sd</span>(boot.wind)  <span class="co"># bootstrap standard error</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>my.mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(my.sample)  <span class="co"># original sample mean</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the code cell below, we use the bootstrap sample means (stored in <code>boot.wind</code> above) to construct a 95% bootstrap percentile confidence interval estimate for the mean wind speed of all North Atlantic storms.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lower.boot.wind <span class="ot">&lt;-</span> <span class="fu">quantile</span>(boot.wind, <span class="fl">0.025</span>)  <span class="co"># lower 95% cutoff</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>upper.boot.wind <span class="ot">&lt;-</span> <span class="fu">quantile</span>(boot.wind, <span class="fl">0.975</span>)  <span class="co"># upper 95% cutoff</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># print to screen</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>lower.boot.wind   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 2.5% 
51.25 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>upper.boot.wind</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   97.5% 
72.36111 </code></pre>
</div>
</div>
<p>Based on the output from the previous code cell, we have a 95% bootstrap percentile confidence interval for the mean wind speed of all North Atlantic storms, namely from 51.25 knots to 72.36 knots. <em>Note the interval estimates may vary, so you likely have a slightly different interval estimate if you are working with a different sample.</em></p>
<p>In the code cell below, we plot the bootstrap distribution with the <span style="color:tomato">original sample mean</span> of <code>my.sample</code> marked with a red vertical line and the <span style="color:dodgerblue">cutoffs for the confidence interval</span> marked with blue vertical lines.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">#################################</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># code is ready to run!</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># no need to edit the code cell</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="do">#################################</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.wind,  </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"x.bar, sample mean wind speed (in knots)"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Sample Mean"</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed sample proportion</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> my.mean, <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co"># blue lines marking cutoffs</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> lower.boot.wind, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> upper.boot.wind, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="19-Parametric-CI-Means_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="sec-param" class="level1">
<h1>A Parametric Method for Interval Estimates</h1>
<hr>
<p>Recall the <a href="./08-Common-Continuous-Distributions.html#sec-empirical">68%-95%-99.7% empirical rule</a> for normal distributions that states approximately:</p>
<ul>
<li>68% of all values fall within one standard deviation (both above and below) from the mean.</li>
<li>95% of all values fall within two standard deviations of the mean.</li>
<li>99.7% of all values fall within three standard deviations of the mean.</li>
</ul>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<hr>
<p>Check the accuracy of the empirical rule for normal distributions.</p>
<section id="question-3a" class="level3">
<h3 class="anchored" data-anchor-id="question-3a">Question 3a</h3>
<hr>
<p>Using the R code cell below, check the accuracy of the approximation that 68% of the data is within <span class="math inline">\(\pm 1\)</span> standard deviation from the mean.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the standard normal distribution <span class="math inline">\(Z \sim N(0,1)\)</span>, compute <span class="math inline">\(P(-1 &lt; Z &lt; 1)\)</span>.</p>
</div>
</div>
<section id="solution-to-question-3a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3a">Solution to Question 3a</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># how much data is within +/- 1 standard deviation?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-3b" class="level3">
<h3 class="anchored" data-anchor-id="question-3b">Question 3b</h3>
<hr>
<p>Using the R code cell below, check the accuracy of the approximation that 95% of the data is within <span class="math inline">\(\pm 2\)</span> standard deviation from the mean.</p>
<section id="solution-to-question-3b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3b">Solution to Question 3b</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># how much data is within +/- 2 standard deviations?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-3c" class="level3">
<h3 class="anchored" data-anchor-id="question-3c">Question 3c</h3>
<hr>
<p>Using the R code cell below, check the accuracy of the approximation that <span class="math inline">\(99.7\)</span>% of the data is within <span class="math inline">\(\pm 3\)</span> standard deviation from the mean.</p>
<section id="solution-to-question-3c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3c">Solution to Question 3c</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># how much data is within +/- 3 standard deviations?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-3d" class="level3">
<h3 class="anchored" data-anchor-id="question-3d">Question 3d</h3>
<hr>
<p>Let’s improve the approximation that 95% of the data is withing <span class="math inline">\(\pm 2\)</span> standard deviations from the mean. Find a more accurate approximation for <span class="math inline">\(z^*\)</span> such that <span class="math inline">\(P( -z^* &lt; Z &lt; z^* ) = 0.95\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sketch a picture to help determine how much area is in the left tail below <span class="math inline">\(-z^*\)</span> if 95% of the area is between <span class="math inline">\(-z^*\)</span> and <span class="math inline">\(z^*\)</span>. Then use the <code>qnorm()</code> command.</p>
</div>
</div>
<section id="solution-to-question-3d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3d">Solution to Question 3d</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find more accurate cutoffs for the middle 95%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(??, <span class="dv">0</span>, <span class="dv">1</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
</section>
<section id="question-4" class="level2">
<h2 class="anchored" data-anchor-id="question-4">Question 4</h2>
<hr>
<p>Let <span class="math inline">\(X\)</span> denote the wind speed of a randomly selected North Atlantic storm. We use <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> to denote the mean and standard deviation, respectively, of the wind speed of the population of all storms in the North Atlantic. Answer the questions below to investigate a different approach to constructing an interval estimate for <span class="math inline">\(\mu\)</span>.</p>
<section id="question-4a" class="level3">
<h3 class="anchored" data-anchor-id="question-4a">Question 4a</h3>
<hr>
<p>Let <span class="math inline">\(\overline{X}\)</span> denote the distribution of sample means for samples size <span class="math inline">\(n\)</span>. Recall we denote the mean and standard error of the sampling distribution as <span class="math inline">\(\mu_{\overline{X}}\)</span> and <span class="math inline">\(\sigma_{\overline{X}}\)</span>, respectively.</p>
<p>Justify each of the steps below.</p>
<p><span class="math display">\[\begin{aligned}
0.95 &amp;= P \left( -1.96 &lt; Z &lt; 1.96 \right) &amp; \mbox{from Question 3d}\\
0.95   &amp;= P \left( -1.96 &lt; \frac{\overline{X} - \mu_{\overline{X}}}{\sigma_{\overline{X}}} &lt; 1.96 \right) &amp; \mbox{Explanation 1}\\
0.95   &amp;=  P \left( -1.96 &lt; \frac{\overline{X} - \mu}{\frac{\sigma}{\sqrt{n}}} &lt; 1.96 \right) &amp; \mbox{Explanation 2}\\
0.95   &amp;= P \left( -1.96 \cdot \frac{\sigma}{\sqrt{n}} &lt; - \mu &lt;  1.96 \cdot \frac{\sigma}{\sqrt{n}} \right) &amp; \mbox{Explanation 3} \\
0.95   &amp;= P \left( - \overline{X} -1.96 \cdot \frac{\sigma}{\sqrt{n}} &lt; - \mu &lt;  - \overline{X} + 1.96 \cdot \frac{\sigma}{\sqrt{n}} \right) &amp; \mbox{Explanation 4} \\
0.95   &amp;= P \left( \overline{X} - 1.96 \cdot \frac{\sigma}{\sqrt{n}} &lt; \mu &lt; \overline{X}+1.96 \cdot \frac{\sigma}{\sqrt{n}} \right) &amp; \mbox{Explanation 5}\\
\end{aligned}\]</span></p>
<section id="solution-to-question-4a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4a">Solution to Question 4a</h4>
<hr>
<p>Explanation 1:</p>
<p><br></p>
<p>Explanation 2:</p>
<p><br></p>
<p>Explanation 3:</p>
<p><br></p>
<p>Explanation 4:</p>
<p><br></p>
<p>Explanation 5:</p>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-4b" class="level3">
<h3 class="anchored" data-anchor-id="question-4b">Question 4b</h3>
<hr>
<p>Let <span class="math inline">\(\mu_{\rm{wind}}\)</span> denote the mean wind speed of all North Atlantic storms which we assume is unknown. How can we use the result that <span class="math inline">\(P \left( \overline{X} - 1.96\cdot \sigma_{\overline{X}} &lt; \mu_{\rm{wind}} &lt; \overline{X}+1.96 \cdot \sigma_{\overline{X}} \right)=0.95\)</span> to help construct a confidence interval for <span class="math inline">\(\mu_{\rm{wind}}\)</span>?</p>
<section id="solution-to-question-4b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4b">Solution to Question 4b</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-4c" class="level3">
<h3 class="anchored" data-anchor-id="question-4c">Question 4c</h3>
<hr>
<p>You will use the original random sample of <span class="math inline">\(n=36\)</span> wind speeds stored in <code>my.sample</code> in <a href="#question-1">Question 1</a> to construct an interval estimate using the result from <a href="#question-4b">Question 4b</a>. If you have not already loaded the <code>population</code> data and created a sample size <span class="math inline">\(n=36\)</span> stored in <code>my.sample</code>, be sure to answer <a href="#question-1">Question 1</a> before continuing. Create a histogram to display the wind speeds in <code>my.sample</code>.</p>
<section id="solution-to-question-4c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4c">Solution to Question 4c</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Enter code to create a histogram to display your sample</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-4d" class="level3">
<h3 class="anchored" data-anchor-id="question-4d">Question 4d</h3>
<hr>
<p>Are the assumptions for the CLT for means satisfied by the data in <code>my.sample</code>? Explain why or why not.</p>
<section id="solution-to-question-4d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4d">Solution to Question 4d</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-4e" class="level3">
<h3 class="anchored" data-anchor-id="question-4e">Question 4e</h3>
<hr>
<p>We assume the <code>population</code> data is unknown and we do not know the actual value of the parameter <span class="math inline">\(\mu_{\rm{wind}}\)</span>. However, <strong>suppose we do know the population variance</strong> <span class="math inline">\(\mbox{Var}(X) = \sigma^2_{\rm{wind}} = 650\)</span> square knots. Using the CLT for means, what is the value of <span class="math inline">\(\sigma_{\overline{X}}\)</span>, the standard error of the sampling distribution for <span class="math inline">\(\overline{X}\)</span>? Show your work below either doing calculations by hand or in R. <em>Tip: In R, the square root function is <code>sqrt()</code>.</em></p>
<section id="solution-to-question-4e" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4e">Solution to Question 4e</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute standard error using CLT</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-4f" class="level3">
<h3 class="anchored" data-anchor-id="question-4f">Question 4f</h3>
<hr>
<p>Give an interval of values <span class="math inline">\(?? &lt; \mu_{\rm{wind}} &lt; ??\)</span> that has a 95% chance of containing the actual value of <span class="math inline">\(\mu_{\rm{wind}}\)</span>. Include supporting work/code to explain how you determined your answer.</p>
<section id="solution-to-question-4f" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4f">Solution to Question 4f</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute upper and lower cutoffs for interval estimate</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="confidence-interval-for-a-mean" class="level1">
<h1>95% Confidence Interval for a Mean</h1>
<hr>
<p>For a sample of size <span class="math inline">\(n\)</span> randomly picked from a normal distribution with unknown <span class="math inline">\(\mu\)</span> and known <span class="math inline">\(\mbox{Var}(X)=\sigma^2\)</span>, a <span style="color:dodgerblue"><strong>95% confidence interval for the mean</strong></span> is</p>
<p><span class="math display">\[{\color{dodgerblue}{\boxed{ \large \overline{X} - 1.96 \frac{\sigma}{\sqrt{n}} &lt; \mu &lt;  \overline{X} + 1.96 \frac{\sigma}{\sqrt{n}}}}}.\]</span></p>
<p>If we draw 1000’s of random samples each size <span class="math inline">\(n\)</span> from a normal distribution with parameters <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span> and compute a 95% confidence interval from each sample, then <span style="color:dodgerblue"><strong>about 95% of the intervals would successfully contain</strong> <span class="math inline">\(\mu\)</span></span>. The 95% is the <span style="color:dodgerblue"><strong>confidence level</strong></span> of the interval and gives the success rate of the interval estimate.</p>
<section id="question-5" class="level2">
<h2 class="anchored" data-anchor-id="question-5">Question 5</h2>
<hr>
<p>A another climatologist collects their own random sample of <span class="math inline">\(n=36\)</span> wind speeds of North Atlantic storms.</p>
<section id="question-5a" class="level3">
<h3 class="anchored" data-anchor-id="question-5a">Question 5a</h3>
<hr>
<p>Pick their random sample (without replacement) of <span class="math inline">\(n=36\)</span> wind speeds from the <code>population</code>. Store the other sample to a vector named <code>their.sample</code>.</p>
<section id="solution-to-question-5a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-5a">Solution to Question 5a</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pick another random sample of 36 wind speeds without replacement</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">their.sample</span>(??, <span class="at">size =</span> ??, <span class="at">replace =</span> ??)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-5b" class="level3">
<h3 class="anchored" data-anchor-id="question-5b">Question 5b</h3>
<hr>
<p>Using the random sample <code>their.sample</code>, give a possible point estimate for <span class="math inline">\(\mu_{\rm{wind}}\)</span>, the mean wind speed of all storms in <code>population</code>.</p>
<section id="solution-to-question-5b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-5b">Solution to Question 5b</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use their sample to give another point estimate</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-5c" class="level3">
<h3 class="anchored" data-anchor-id="question-5c">Question 5c</h3>
<hr>
<p>Are the two point estimates in <a href="#question-2">Question 2</a> and <a href="#question-5b">Question 5b</a> equal?</p>
<section id="solution-to-question-5c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-5c">Solution to Question 5c</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-5d" class="level3">
<h3 class="anchored" data-anchor-id="question-5d">Question 5d</h3>
<hr>
<p>Are the true values of the population parameter different or the same for both climatologists?</p>
<section id="solution-to-question-5d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-5d">Solution to Question 5d</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-5e" class="level3">
<h3 class="anchored" data-anchor-id="question-5e">Question 5e</h3>
<hr>
<p>Without checking, which point estimate (<a href="#question-2">Question 2</a> or <a href="#question-5b">Question 5b</a>) do you believe is “better”?</p>
<section id="solution-to-question-5e" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-5e">Solution to Question 5e</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="what-is-uncertain-and-what-is-unknown" class="level1">
<h1>What is Uncertain and What is Unknown?</h1>
<hr>
<p>It can be easy to confuse the terms <em>uncertain</em> and <em>unknown</em>. In a less formal setting, people may use these terms interchangeably. In statistical inference, there is a clear distinction in their meaning that is important to clarify:</p>
<ul>
<li>Each <span style="color:dodgerblue"><strong>sample statistic is a known value that is uncertain</strong></span> due to sampling.
<ul>
<li>Each climatologist has a different sample.</li>
<li>The sample means will be different for different researchers.</li>
</ul></li>
<li>The <span style="color:dodgerblue"><strong>population parameter is an unknown value that is certain</strong></span> (not variable).
<ul>
<li>The parameter we are trying to estimate is a fixed (certain) value.</li>
<li>The value of the parameter is however unknown.</li>
</ul></li>
<li>Each climatologist has a different estimate but both are trying to hit the same fixed target.</li>
<li>We cannot be certain whether our estimate is successful or not if <span class="math inline">\(\mu_{\rm{wind}}\)</span> is unknown!</li>
</ul>
</section>
<section id="interpreting-confidence-intervals" class="level1">
<h1>Interpreting Confidence Intervals</h1>
<hr>
<section id="question-6" class="level2">
<h2 class="anchored" data-anchor-id="question-6">Question 6</h2>
<hr>
<p>A researcher collects a random sample size <span class="math inline">\(n=36\)</span> of wind speeds for storms in the North Atlantic and calculates a 95% confidence interval for the mean wind speed that is from <span class="math inline">\(48.75\)</span> knots to <span class="math inline">\(65.41\)</span> knots. <strong>For each statement, determine whether the interpretation is correct or not. If not, explain why not.</strong></p>
<section id="question-6a" class="level3">
<h3 class="anchored" data-anchor-id="question-6a">Question 6a</h3>
<hr>
<p>There is a 95% chance that a randomly selected storm in the North Atlantic has a wind speed between <span class="math inline">\(48.75\)</span> and <span class="math inline">\(65.41\)</span> knots.</p>
<section id="solution-to-question-6a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-6a">Solution to Question 6a</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-6b" class="level3">
<h3 class="anchored" data-anchor-id="question-6b">Question 6b</h3>
<hr>
<p>There is a 95% chance that the mean wind speed of all storms in the North Atlantic is between <span class="math inline">\(48.75\)</span> and <span class="math inline">\(65.41\)</span> knots.</p>
<section id="solution-to-question-6b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-6b">Solution to Question 6b</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-6c" class="level3">
<h3 class="anchored" data-anchor-id="question-6c">Question 6c</h3>
<hr>
<p>There is a 95% chance the interval from <span class="math inline">\(48.75\)</span> to <span class="math inline">\(65.41\)</span> knots contains the mean wind speed of all storms in the North Atlantic.</p>
<section id="solution-to-question-6c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-6c">Solution to Question 6c</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-6d" class="level3">
<h3 class="anchored" data-anchor-id="question-6d">Question 6d</h3>
<hr>
<p>95% of all random samples of size <span class="math inline">\(n=36\)</span> North Atlantic storms have a sample mean wind speed between <span class="math inline">\(48.75\)</span> and <span class="math inline">\(65.41\)</span> knots.</p>
<section id="solution-to-question-6d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-6d">Solution to Question 6d</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-6e" class="level3">
<h3 class="anchored" data-anchor-id="question-6e">Question 6e</h3>
<hr>
<p>There is a 95% chance the interval from <span class="math inline">\(48.75\)</span> to <span class="math inline">\(65.41\)</span> knots contains the mean wind speed of a random sample of <span class="math inline">\(n=36\)</span> storms.</p>
<section id="solution-to-question-6e" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-6e">Solution to Question 6e</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
<section id="attaching-uncertainty-to-the-intervals" class="level2">
<h2 class="anchored" data-anchor-id="attaching-uncertainty-to-the-intervals">Attaching Uncertainty to the Intervals</h2>
<hr>
<p>The plot shows 100 different confidence intervals based on 100 different random samples each size <span class="math inline">\(n=36\)</span> storms selected from the <code>population</code>. For each sample mean <span class="math inline">\(\overline{X}\)</span>, we follow the same process of constructing a 95% confidence interval using:</p>
<p><span class="math display">\[\overline{X} - 1.96 \frac{\sigma}{\sqrt{n}} &lt; \mu_{\rm{wind}} &lt;  \overline{X} + 1.96 \frac{\sigma}{\sqrt{n}}.\]</span></p>
<ul>
<li>Each sample results is a different interval estimate (all with the same width).</li>
<li>The true population mean is marked with a blue vertical line at <span class="math inline">\(\mu_{\rm{wind}} = 50.02\)</span> knots.</li>
<li>The goal of each interval is to contain the same, fixed value of the population parameter.
<ul>
<li>The confidence intervals that <span style="color:mediumseagreen">successfully contain <span class="math inline">\(\mu_{\rm{wind}} = 50.02\)</span></span> are marked in green.</li>
<li>The unsuccessful confidence intervals that <span style="color:tomato">do not contain <span class="math inline">\(\mu_{\rm{wind}} = 50.02\)</span></span> are marked in red.
<ul>
<li><span style="color:tomato">2 out of the 100 interval estimates are underestimates.</span></li>
<li><span style="color:tomato">2 out of the 100 interval estimates are overestimates.</span></li>
</ul></li>
<li><span style="color:mediumseagreen">We have a success rate of 96 out of 100 in this simulation.</span></li>
</ul></li>
<li>If we ran this simulation many more times, the success rate would converge to 95%.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-success" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="19-Parametric-CI-Means_files/figure-html/fig-success-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;26.1: Results of 100 randomly generated 95% confidence intervals.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="question-7" class="level2">
<h2 class="anchored" data-anchor-id="question-7">Question 7</h2>
<hr>
<p>What are some warnings to keep in mind when interpreting confidence intervals?</p>
<section id="solution-to-question-7" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-7">Solution to Question 7</h3>
<hr>
<p>Warning 1:</p>
<p><br></p>
<p>Warning 2:</p>
<p><br></p>
<p>Warning 3:</p>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-8" class="level2">
<h2 class="anchored" data-anchor-id="question-8">Question 8</h2>
<hr>
<p>You will use the original random sample of <span class="math inline">\(n=36\)</span> wind speeds stored in <code>my.sample</code> in <a href="#question-1">Question 1</a> to construct a new confidence interval estimate for the mean wind speed of all North Atlantic storms. If you have not already loaded the <code>population</code> data and created a sample size <span class="math inline">\(n=36\)</span> stored in <code>my.sample</code>, be sure to answer <a href="#question-1">Question 1</a> before continuing.</p>
<section id="question-8a" class="level3">
<h3 class="anchored" data-anchor-id="question-8a">Question 8a</h3>
<hr>
<p>Based on your sample data in <code>my.sample</code>, give a <strong>90% confidence interval</strong> for the mean wind speed of all North Atlantic storms using the parametric method. As with earlier, suppose we know population variance is <span class="math inline">\(\sigma^2_X = 650\)</span>. <strong>Interpret the practical meaning of your 90% confidence interval in the context of this example.</strong></p>
<section id="solution-to-question-8a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-8a">Solution to Question 8a</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>new.z <span class="ot">&lt;-</span> ??  <span class="co"># Enter a command to calculate z value for 90% Conf Level</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>wind.lowe90 <span class="ot">&lt;-</span> ??   <span class="co"># Enter a command to calculate the lower limit</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>wind.upper90 <span class="ot">&lt;-</span> ??   <span class="co"># Enter a command to calculate the upper limit</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print your answers</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>wind.lower90</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>wind.upper90</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
<p><strong>Practical interpretation of your 90% confidence interval:</strong></p>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-8b" class="level3">
<h3 class="anchored" data-anchor-id="question-8b">Question 8b</h3>
<hr>
<p>As we <strong>decrease the confidence level of the interval</strong> from 95% in <a href="#question-4f">Question 4f</a> to 90% in <a href="#question-8a">Question 8a</a>, what happened to the width of the interval estimate?</p>
<section id="solution-to-question-8b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-8b">Solution to Question 8b</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="changing-the-confidence-level" class="level1">
<h1>Changing the Confidence Level</h1>
<hr>
<p>For a sample of size <span class="math inline">\(n\)</span> randomly picked from a normal distribution with unknown <span class="math inline">\(\mu\)</span> and known <span class="math inline">\(\mbox{Var}(X)=\sigma^2\)</span>, then a <span style="color:dodgerblue"><strong>confidence interval for the mean</strong></span> is given by</p>
<p><span class="math display">\[\boxed{ \large \overline{X} - {\color{tomato}{z_{\alpha/2}}} \cdot \frac{\sigma}{\sqrt{n}} &lt; \mu &lt; \overline{X} + {\color{tomato}{z_{\alpha/2}}} \cdot \frac{\sigma}{\sqrt{n}}},\]</span></p>
<p>where the area under <span class="math inline">\(N(0,1)\)</span> between <span class="math inline">\(\pm z_{\alpha/2}\)</span> is equal to the <span style="color:dodgerblue"><strong>confidence level</strong></span> of the estimate.</p>
<ul>
<li>The confidence level is the success rate of the estimate.</li>
<li>The distance <span class="math inline">\({\color{dodgerblue}{\mbox{MoE} = z_{\alpha/2} \cdot \frac{\sigma}{\sqrt{n}}}}\)</span> is called the <span style="color:dodgerblue"><strong>Margin of Error (MoE)</strong></span> of the confidence interval.</li>
</ul>
<p><span class="math display">\[\boxed{ \large  \mu \approx  \overline{X} \pm {\color{dodgerblue}{\mbox{MoE}}}}\]</span></p>
<p>Let <span style="color:dodgerblue"><strong>CL</strong></span> denote a selected <span style="color:dodgerblue"><strong>confidence level</strong></span> that is the proportion of <span style="color:dodgerblue"><strong>area in the middle</strong></span>.</p>
<ul>
<li>We have <span class="math inline">\({\color{mediumseagreen}{\alpha = 1 - CL}}\)</span> is the <span style="color:mediumseagreen"><strong>area in the two tails</strong></span>.</li>
<li>The <span style="color:tomato"><strong>area in each tail</strong></span> is therefore <span class="math inline">\(\color{tomato}{\dfrac{\alpha}{2}}\)</span>.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cutoffs" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="19-Parametric-CI-Means_files/figure-html/fig-cutoffs-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;27.1: Identifying Z Values for Confidence Interval</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="confidence-intervals-when-the-variance-is-unknown" class="level1">
<h1>Confidence Intervals When the Variance Is Unknown</h1>
<hr>
<p>When estimating a population mean, in addition to <span class="math inline">\(\mu\)</span> being unknown, we often <strong>do not know the population variance, <span class="math inline">\(\sigma^2\)</span>, either.</strong> We pick a random sample size <span class="math inline">\(n\)</span>, and we can plug-in the sample mean <span class="math inline">\(\bar{x}\)</span> as our point estimate for <span class="math inline">\(\mu\)</span>. How can we find the margin of error if <span class="math inline">\(\sigma\)</span> is unknown?</p>
<ul>
<li>We can use the <span style="color:tomato"><strong>sample standard deviation</strong></span> <span class="math inline">\(\color{tomato}{s}\)</span> in place of <span class="math inline">\(\sigma\)</span>.</li>
</ul>
<p>From the CLT for means, as long as the sample is normally distributed or if <span class="math inline">\(n \geq 30\)</span>, then we know the distribution of sample means <span class="math inline">\(\overline{X}\)</span> is normally distributed with mean <span class="math inline">\({\color{mediumseagreen}{\mu_{\overline{X}} = \mu_X}}\)</span> and standard error <span class="math inline">\({\color{dodgerblue}{\sigma_{\overline{X}} = \frac{\sigma}{\sqrt{n}}}}\)</span>. Thus, the standardized distribution of <span class="math inline">\(z\)</span>-scores corresponding the sampling distribution for the sample mean <span class="math inline">\(\overline{X}\)</span> is normal:</p>
<p><span class="math display">\[Z = \frac{\overline{X} - \color{mediumseagreen}{\mu_{\overline{X}}}}{{\color{dodgerblue}{\sigma_{\overline{X}}}}} = \frac{\overline{X} - \color{mediumseagreen}{\mu_{X}}}{{\color{dodgerblue}{\sigma_{X}/\sqrt{n}}}} \sim N(0,1).\]</span></p>
<p>Let’s apply our <span style="color:tomato">substitution of <span class="math inline">\(s\)</span> in place of <span class="math inline">\(\sigma_{X}\)</span></span> and consider the resulting distribution of standardized statistics denoted <span class="math inline">\(W\)</span>:</p>
<p><span class="math display">\[Z = \frac{\overline{X} - \mu_{X}}{{\color{tomato}{\sigma_{X}}}/\sqrt{n}} \quad \xrightarrow{\text{plug-in } {\color{tomato}{s}} \text{ for } {\color{tomato}{\sigma_{X}}}}  \quad W = \frac{\overline{X}-\mu_X}{{\color{tomato}{s}}/\sqrt{n}} \sim \mbox{ ?}\]</span></p>
<ul>
<li>The plot on the left gives a histogram for the standardized sampling distribution <span class="math inline">\(W\)</span>.</li>
<li>The plot on the right is a QQ-plot comparing the distribution of <span class="math inline">\(W\)</span> to <span class="math inline">\(Z \sim N(0,1)\)</span>.</li>
</ul>
<div id="fig-qqplot" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-qqplot-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="19-Parametric-CI-Means_files/figure-html/fig-qqplot-1.png" class="img-fluid figure-img" data-ref-parent="fig-qqplot" width="672"></p>
<figcaption class="figure-caption">(a) Distribution of Standardized Statistics.</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-qqplot-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="19-Parametric-CI-Means_files/figure-html/fig-qqplot-2.png" class="img-fluid figure-img" data-ref-parent="fig-qqplot" width="672"></p>
<figcaption class="figure-caption">(b) QQ-plot comparing W to N(0,1).</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;28.1: Standardized Distribution When Variance Unknown.</figcaption><p></p>
</figure>
</div>
<p>The distribution <span class="math inline">\(W\)</span> is symmetric and bell-shaped. From the QQ-plot, we see <span class="math inline">\(W\)</span> is approximately normal in the middle of the distribution. However, the tails of distribution <span class="math inline">\(W\)</span> are not similar to tails of a normal distribution. Distribution <span class="math inline">\(W\)</span> has <strong>fatter tails</strong> than a normal distribution.</p>
<ul>
<li>The fatter tails are due to the <strong>added uncertainty</strong> with using <span class="math inline">\(s\)</span> to estimate the value of <span class="math inline">\(\sigma\)</span>.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tdist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="19-Parametric-CI-Means_files/figure-html/fig-tdist-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;28.2: Plots of t-distributions with different degrees of freedom</figcaption>
</figure>
</div>
</div>
</div>
<section id="the-t-distribution" class="level2">
<h2 class="anchored" data-anchor-id="the-t-distribution">The <span class="math inline">\(t\)</span>-Distribution</h2>
<hr>
<p>When the population is known to be normally distributed, the distribution <span class="math inline">\(W\)</span> is a <span style="color:dodgerblue"><strong><span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-1\)</span> degrees of freedom</strong></span>, where <span class="math inline">\(n\)</span> denotes the sample size. If the underlying population is known to be symmetric (but not necessarily normal), a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-1\)</span> degrees of freedom is still a good estimate.</p>
<ul>
<li>The larger our sample size <span class="math inline">\(n\)</span>, the better (less biased) the estimate <span class="math inline">\(s\)</span> is for <span class="math inline">\(\sigma\)</span>.</li>
<li>The larger the sample size <span class="math inline">\(n\)</span>, the closer the <span class="math inline">\(t\)</span>-distribution is to <span class="math inline">\(Z \sim N(0,1)\)</span>.</li>
</ul>
<p>If a random sample of data is skewed, then the population is likely skewed. The more skewed the population is, the less accurate a <span class="math inline">\(t\)</span>-distribution is to estimate the distribution of the standardized statistic <span class="math inline">\(W\)</span>.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>In cases where the sample is small (<span class="math inline">\(n &lt; 30\)</span>) and skewed, a bootstrap confidence interval is typically preferred to using a <span class="math inline">\(t\)</span>-distribution to approximate the margin of error.</p>
</div>
</div>
</section>
<section id="using-a-t-distribution-when-variance-is-unknown" class="level2">
<h2 class="anchored" data-anchor-id="using-a-t-distribution-when-variance-is-unknown">Using a <span class="math inline">\(t\)</span>-Distribution When Variance is Unknown</h2>
<hr>
<p>For a sample of size <span class="math inline">\(n\)</span> randomly picked from a normal distribution with unknown <span class="math inline">\(\mu\)</span> and unknown <span class="math inline">\(\mbox{Var}(X)=\sigma^2\)</span>, we construct a confidence interval for <span class="math inline">\(\mu\)</span> using:</p>
<ul>
<li>The <span style="color:tomato">sample standard deviation <span class="math inline">\(s\)</span></span> in place of <span class="math inline">\(\sigma\)</span>, and<br>
</li>
<li>A <span style="color:dodgerblue"><span class="math inline">\(t\)</span>-distribution to find <span class="math inline">\(t_{\alpha/2}\)</span></span> instead of using <span class="math inline">\(N(0,1)\)</span> to find <span class="math inline">\(z_{\alpha/2}\)</span></li>
</ul>
<p>A corresponding <span class="math inline">\(t\)</span>-distribution confidence interval is given by</p>
<p><span class="math display">\[{\large \boxed{ \overline{X} - {\color{dodgerblue}{t_{\alpha/2}}} \cdot \frac{{\color{tomato}{s}}}{\sqrt{n}} &lt; \mu &lt; \overline{X} + {\color{dodgerblue}{t_{\alpha/2}}} \cdot \frac{{\color{tomato}{s}}}{\sqrt{n}}}},\]</span></p>
<p>where the area under the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-1\)</span> degrees of freedom between <span class="math inline">\({\color{dodgerblue}{\pm t_{\alpha/2}}}\)</span> is equal to the confidence level.</p>
</section>
<section id="question-9" class="level2">
<h2 class="anchored" data-anchor-id="question-9">Question 9</h2>
<hr>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Komodo_dragon_%28Varanus_komodoensis%29_2.jpg" class="img-fluid figure-img" style="width:40.0%" alt="Komodo dragon (Varanus_komodoensis)"></p>
<figcaption class="figure-caption">Credit: Charles J. Sharp, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>, via Wikimedia Commons</figcaption>
</figure>
</div>
<p>Researchers want to estimate the average length of all adult female Komodo dragons. The pick a random sample of <span class="math inline">\(n=8\)</span> adult female Komodo dragons with the following weights (in pounds). They believe the distribution in weights will by normally distributed, but otherwise, the population variance is unknown.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dragon.wt <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">145</span>, <span class="dv">178</span>, <span class="dv">142</span>, <span class="dv">139</span>, <span class="dv">160</span>, <span class="dv">190</span>, <span class="dv">168</span>, <span class="dv">122</span>)  <span class="co"># load sample of weights  </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>dragon.wt  <span class="co"># print to screen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 145 178 142 139 160 190 168 122</code></pre>
</div>
</div>
<section id="question-9a" class="level3">
<h3 class="anchored" data-anchor-id="question-9a">Question 9a</h3>
<hr>
<p>Use the R code cell below to construct a 95% confidence interval for mean weight of all female Komodo dragons using the sample weights in <code>dragon.wt</code>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the data in <code>dragon.wt</code>, calculate the statistics <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(s\)</span>. To find <span class="math inline">\(t_{\alpha/2}\)</span>, use the <code>qt()</code> function similar to how you use the <code>qnorm()</code> to calculate <span class="math inline">\(z_{\alpha/2}\)</span>. For more help using the <code>qt()</code> function, run <code>?qt()</code>.</p>
</div>
</div>
<section id="solution-to-question-9a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-9a">Solution to Question 9a</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># construct a 95% confidence interval</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-9b" class="level3">
<h3 class="anchored" data-anchor-id="question-9b">Question 9b</h3>
<hr>
<p>Interpret the practical meaning of the confidence interval in <a href="#question-9a">Question 9a</a> in this context.</p>
<section id="solution-to-question-9b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-9b">Solution to Question 9b</h4>
<hr>
<p><br><br>
<br> <br></p>
</section>
</section>
<section id="question-9c" class="level3">
<h3 class="anchored" data-anchor-id="question-9c">Question 9c</h3>
<hr>
<p>Use the R code cell below to construct a 99% confidence interval for mean weight of all female Komodo dragons using the sample weights in <code>dragon.wt</code>.</p>
<section id="solution-to-question-9c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-9c">Solution to Question 9c</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># construct a 99% confidence interval</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
</section>
<section id="different-methods-for-t-distribution-confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="different-methods-for-t-distribution-confidence-intervals">Different Methods for <span class="math inline">\(t\)</span>-Distribution Confidence Intervals</h2>
<hr>
<ul>
<li><p>Use the formula <span class="math inline">\(\displaystyle \overline{X} - {\color{dodgerblue}{t_{\alpha/2}}} \cdot \frac{{\color{tomato}{s}}}{\sqrt{n}} &lt; \mu &lt; \overline{X} + {\color{dodgerblue}{t_{\alpha/2}}} \cdot \frac{{\color{tomato}{s}}}{\sqrt{n}}\)</span>.</p>
<ul>
<li>Use the <code>qt()</code> function in R to find the value of <span class="math inline">\(t_{\alpha/2}\)</span>, or</li>
<li>Use a <a href="https://www.sjsu.edu/faculty/gerstman/StatPrimer/t-table.pdf"><span class="math inline">\(t\)</span>-distribution table</a> to estimate values for <span class="math inline">\(t_{\alpha/2}\)</span>.</li>
</ul></li>
<li><p>Use the R function <code>t.test(x, conf.level)$conf.int</code>.</p>
<ul>
<li><code>x</code> is the vector of sample data.</li>
<li>Set the confidence level with the <code>conf.level</code> option.</li>
<li>Open the help manual with <code>?t.test</code> for further information.</li>
</ul></li>
</ul>
</section>
<section id="question-10" class="level2">
<h2 class="anchored" data-anchor-id="question-10">Question 10</h2>
<hr>
<p>Using the Komodo dragon sample data in <code>dragon.wt</code> and the <code>t.test()</code> function, find a 95% confidence interval. Compare the results with the 95% confidence interval from <a href="#question-9a">Question 9a</a>.</p>
<section id="solution-to-question-10" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-10">Solution to Question 10</h3>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(??, <span class="at">conf.level =</span> ??)<span class="sc">$</span>conf.int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="confidence-interval-for-a-difference-in-two-means" class="level1">
<h1>Confidence Interval for a Difference in Two Means</h1>
<hr>
<section id="sec-clt-diff-means" class="level2">
<h2 class="anchored" data-anchor-id="sec-clt-diff-means">Question 11</h2>
<hr>
<p>Let <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> be independent random variables with <span class="math inline">\(X \sim N(\mu_1, \sigma_1)\)</span> and <span class="math inline">\(Y \sim N(\mu_2, \sigma_2)\)</span>. Using <a href="./06-Expected-Value-and-Variance.html#sec-prop-exp">properties of expected value</a> and <a href="./06-Expected-Value-and-Variance.html#sec-prop-var">variance</a>, show for sample sizes <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span>, respectively, that</p>
<p><span class="math display">\[E(\overline{X}-\overline{Y}) = \mu_1-\mu_2 \qquad \mbox{and} \qquad \mbox{Var}(\overline{X}-\overline{Y}) = \frac{\sigma_1^2}{n_1} +  \frac{\sigma_2^2}{n_2}.\]</span></p>
<section id="solution-to-question-11" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-11">Solution to Question 11</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="sec-informal" class="level2">
<h2 class="anchored" data-anchor-id="sec-informal">Confidence Intervals for a Difference in Means</h2>
<hr>
<p>Let <span class="math inline">\(X_1, X_2, \ldots , X_{n_1}\)</span> be independent and identically distributed (i.i.d.) random variables picked from <span class="math inline">\(X \sim N(\mu_1, \sigma_1^2)\)</span> and let <span class="math inline">\(Y_1, Y_2, \ldots , Y_{n_2}\)</span> be i.i.d. random variables picked from <span class="math inline">\(Y \sim N(\mu_2, \sigma_1^2)\)</span>. An approximate confidence interval for the difference in means <span class="math inline">\(\mu_1 - \mu_2\)</span> is given by:</p>
<p><span class="math display">\[{\large \boxed{ {\color{mediumseagreen}{(\overline{X} - \overline{Y})}} -  {\color{tomato}{t_{\alpha/2}}} \cdot  {\color{dodgerblue}{\sqrt{\frac{s_1^2}{n_1} +  \frac{s_2^2}{n_2}}}} &lt; \mu_1 - \mu_2 &lt; {\color{mediumseagreen}{(\overline{X} - \overline{Y})}} +  {\color{tomato}{t_{\alpha/2}}} \cdot  {\color{dodgerblue}{\sqrt{\frac{s_1^2}{n_1} +  \frac{s_2^2}{n_2}}}}}}. \]</span></p>
<ul>
<li><span style="color:mediumseagreen">Use <span class="math inline">\(\bar{x} - \bar{y}\)</span> as the point estimate for <span class="math inline">\(\mu_1 - \mu_2\)</span>.</span></li>
<li><span style="color:dodgerblue">Approximate the standard error using <span class="math inline">\(s_1\)</span> and <span class="math inline">\(s_2\)</span> in place of unknown standard deviations <span class="math inline">\(\sigma_1\)</span> and <span class="math inline">\(\sigma_2\)</span>.</span></li>
<li><span style="color:tomato">The area under the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df\)</span> degrees of freedom between <span class="math inline">\(\pm t_{\alpha/2}\)</span> is equal to the confidence level.</span>
<ul>
<li>Informally, we can use the smaller of <span class="math inline">\(n_1-1\)</span> and <span class="math inline">\(n_2-1\)</span> as the degrees of freedom.</li>
<li>Many R functions use the more accurate <em>Welch’s approximation</em> for the degrees of freedom,</li>
</ul>
<span class="math display">\[ df = \dfrac{\left( \dfrac{s_1^2}{n_1}+ \dfrac{s_2^2}{n_2} \right)^2}{ \dfrac{(s_1^2/n_1)^2}{n_1-1} + \dfrac{(s_2^2/n_2)^2}{n_2-1}}.\]</span>
<ul>
<li>We do not need to memorize Welch’s approximation since <code>t.test()</code> uses this method.</li>
</ul></li>
</ul>
</section>
</section>
<section id="which-month-has-the-strongest-storms" class="level1">
<h1>Which Month Has the Strongest Storms?</h1>
<hr>
<p>In our analysis of <a href="#sec-storm">North Atlantic storm wind speeds</a>, we used data stored in the <code>storms</code> data frame in the <code>dplyr</code> package. In our initial analysis, we assumed the data in <code>storms</code> represented the population, and we did not have access to the population data in <code>storms</code>. <strong>The data in <code>storms</code> is actually a sample</strong> of 19066 storm observations taken for North Atlantic storms that are measured every six hours during the lifetime of the storm. The population of interest is all storms that occur at all times in the North Atlantic.</p>
<ul>
<li>Consider data in <code>storms</code> as a random sample of 19066 observations picked from the population.</li>
<li>We have access to the sample <code>storms</code> that we will use estimate parameters for the population.</li>
<li>Below, we load <code>dplyr</code> and generate side-by-side box plots of the distribution of wind speeds in the <code>storms</code> sample by month.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>storms<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">factor</span>(storms<span class="sc">$</span>month)  <span class="co"># convert month to categorical factor</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(wind <span class="sc">~</span> month, </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> storms,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Distribution of Wind Speeds by Month"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Month"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Wind speed (in knots)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="19-Parametric-CI-Means_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="question-12" class="level2">
<h2 class="anchored" data-anchor-id="question-12">Question 12</h2>
<hr>
<p>Based on the plots in the figure above, in which month do you suspect storms have the greatest wind speed? Explain how you determined your answer.</p>
<section id="solution-to-question-12" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-12">Solution to Question 12</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="refining-our-question" class="level2">
<h2 class="anchored" data-anchor-id="refining-our-question">Refining Our Question</h2>
<hr>
<p>There are different statistics for assessing “greatest wind speed”. From the box plots, we have a good visual comparison of medians. With storms, outliers are typically the most important observations we do want to emphasize in our analysis. Thus, we use the <em>mean</em> as our measurement of center instead of a median or trimmed mean.</p>
<p>Side-by-side box plots give a nice graphical summary of the distribution of winds speeds by month. As we might suspect, from this first plot we rule out some months from this analysis. Some months appear to have very similar distributions upon inspection of box plots. We dig a little into the sample data to determine which months have the greatest sample mean wind speeds.</p>
<ul>
<li>We use the <code>tapply()</code> function below to calculate and compare sample mean wind speeds by month.</li>
<li>Here is a <a href="https://www.statology.org/tapply-r/">nice introduction</a> to the <code>tapply()</code> function.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(storms<span class="sc">$</span>wind, storms<span class="sc">$</span>month, mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        4        5        6        7        8        9       10 
49.85714 38.86364 35.17413 35.32092 41.39426 48.14414 54.56013 51.58109 
      11       12 
49.42741 45.54245 </code></pre>
</div>
</div>
<p>Notice September (9) and October (10) are the two months with the highest mean wind speeds of <span class="math inline">\(54.56\)</span> knots and <span class="math inline">\(51.58\)</span> knots, respectively. The two means are close, and we only have a subset of population data. Is the observed difference in sample means greater than the margin of error we can expect due to the uncertainty of sampling? We can use a confidence interval to answer this question!</p>
<blockquote class="blockquote">
<p><span style="color:dodgerblue">Give a 95% confidence interval to estimate the difference in the mean wind speed of storms in September compared to October?</span></p>
</blockquote>
</section>
<section id="subsetting-into-two-independent-samples" class="level2">
<h2 class="anchored" data-anchor-id="subsetting-into-two-independent-samples">Subsetting into Two Independent Samples</h2>
<hr>
<p>Run the code cell below to create two data frames, <code>sep.wind</code> and <code>oct.wind</code>, containing separate samples of wind speeds for North Atlantic storms in September and October, respectively. Both <code>sep.wind</code> and <code>oct.wind</code> are data frames with just one variable, <code>wind</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a vector of sep wind</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>sep.wind <span class="ot">&lt;-</span> <span class="fu">subset</span>(storms, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>              month <span class="sc">==</span> <span class="st">"9"</span>, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">select =</span> wind)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co"># create a vector of oct wind</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>oct.wind <span class="ot">&lt;-</span> <span class="fu">subset</span>(storms, </span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>              month <span class="sc">==</span> <span class="st">"10"</span>, </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">select =</span> wind)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="question-13" class="level2">
<h2 class="anchored" data-anchor-id="question-13">Question 13</h2>
<hr>
<p>Answer the questions below to construct a 95% confidence interval for the difference in mean wind speeds of North Atlantic storms in September compared to October.</p>
<section id="question-13a" class="level3">
<h3 class="anchored" data-anchor-id="question-13a">Question 13a</h3>
<hr>
<p>Calculate <span class="math inline">\(n_s\)</span> and <span class="math inline">\(n_o\)</span>, the number of observations in September and October samples, respectively. Store the results in <code>n.s</code> and <code>n.o</code>.</p>
<section id="solution-to-question-13a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-13a">Solution to Question 13a</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate n_s</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>n.s <span class="ot">&lt;-</span> ??</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate n_o</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>n.o <span class="ot">&lt;-</span> ??</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># print to screen</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>n.s</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>n.o</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-13b" class="level3">
<h3 class="anchored" data-anchor-id="question-13b">Question 13b</h3>
<hr>
<p>Using the sample data in <code>sep.wind</code> and <code>oct.wind</code>, give a point estimate for the difference in population means, <span class="math inline">\(\mu_s - \mu_o\)</span>. Store the result to <code>point.est</code></p>
<section id="solution-to-question-13b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-13b">Solution to Question 13b</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate point estimate</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>point.est <span class="ot">&lt;-</span> ??</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>point.est  <span class="co"># print to screen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-13c" class="level3">
<h3 class="anchored" data-anchor-id="question-13c">Question 13c</h3>
<hr>
<p>Using a <span class="math inline">\(t\)</span>-distribution, calculate the margin of error of a 95% confidence interval for the difference in means.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use the <code>sd()</code> function to calculate each sample standard deviation. Use the <code>qt()</code> function to identify <span class="math inline">\(t_{\alpha/2}\)</span> using the <a href="#sec-informal">informal count</a> for the degrees of freedom.</p>
</div>
</div>
<section id="solution-to-question-13c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-13c">Solution to Question 13c</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use code cell to construct a 95% confidence interval</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<p><strong>Based on the output above, a 95% confidence interval is from ?? to ??</strong>.</p>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-13d" class="level3">
<h3 class="anchored" data-anchor-id="question-13d">Question 13d</h3>
<hr>
<p>Interpret the meaning of your interval in <a href="#question-13c">Question 13c</a>. In particular, can we conclude that wind speeds are on average greater in one month or the other?</p>
<section id="solution-to-question-13d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-13d">Solution to Question 13d</h4>
<hr>
<p><br><br>
<br> <br></p>
</section>
</section>
</section>
</section>
<section id="using-t.test-for-a-difference-in-means" class="level1">
<h1>Using <code>t.test()</code> for a Difference in Means</h1>
<hr>
<p>The <code>t.test()</code> function in R can used to construct a confidence interval for a difference in means from two independent populations using a <span class="math inline">\(t\)</span>-distribution with Welch’s approximation for the degree’s for freedom. Let <code>x</code> and <code>y</code> denote vectors containing data from each of the two independent samples.</p>
<ul>
<li>The command <code>t.test(x, y, conf.level = 0.95)$conf.int</code> will give a 95% confidence level for the difference in means using Welch’s approximation.</li>
</ul>
<section id="question-14" class="level2">
<h2 class="anchored" data-anchor-id="question-14">Question 14</h2>
<hr>
<p>Use the <code>t.test()</code> function with the samples <code>sep.wind</code> and <code>oct.wind</code> to construct a 95% confidence interval for the difference in mean wind speeds of North Atlantic storms in September compared to October. How does your answer compare to your confidence interval in <a href="#question-13c">Question 13c</a>? If the two answers are different, which confidence interval do you believe is more accurate?</p>
<section id="solution-to-question-14" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-14">Solution to Question 14</h3>
<hr>
<p>Complete the command below and then compare result to answer in <a href="#question-13c">Question 13c</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(??, ??, <span class="at">conf.level =</span> ??)<span class="sc">$</span>conf.int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="subsetting-with-t.test" class="level2">
<h2 class="anchored" data-anchor-id="subsetting-with-t.test">Subsetting with <code>t.test</code></h2>
<hr>
<p>Frequently, we would like to compare the distributions of a quantitative variable, denoted <code>quant</code>, for two different groups based on a categorical variable in the data set, denoted <code>categorical</code>. If our sample data is stored in a data frame called <code>data.name</code> with this structure, we can use <code>t.test()</code> without having to first split the sample into independent samples according to category group. <code>t.test()</code> can subset the data into independent samples for us and construct a confidence interval for the difference in two means. Using the <code>t.test()</code> function</p>
<center>
<code>t.test(quant ~ categorical, data = data.name, conf.level = 0.95)$conf.int</code>
</center>
<p><br> will give a 95% confidence level for the difference in means of a specified quantitative variable between the two different groups of the categorical variable.</p>
</section>
<section id="question-15" class="level2">
<h2 class="anchored" data-anchor-id="question-15">Question 15</h2>
<hr>
<p>The code cell below subsets the sample data for all months in <code>storms</code> to a new data frame named <code>pooled</code> that:</p>
<ul>
<li>Includes only storm observations from September or October.</li>
<li>Selects only two variables, <code>wind</code> and <code>month</code>, to keep from <code>storms</code>.</li>
<li>The first six rows of the data frame <code>pooled</code> are printed to the screen with <code>head(pooled)</code>.</li>
<li>Run the code cell below and inspect the first six rows of <code>pooled</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>pooled <span class="ot">&lt;-</span> <span class="fu">subset</span>(storms,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>               month <span class="sc">==</span> <span class="st">"9"</span> <span class="sc">|</span> month <span class="sc">==</span> <span class="st">"10"</span>,   <span class="co"># month is 9 OR month is 10</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">select =</span> <span class="fu">c</span>(wind, month))  <span class="co"># select wind and month variables</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pooled)  <span class="co"># print first 6 rows of pooled to screen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
   wind month
  &lt;int&gt; &lt;fct&gt;
1    30 9    
2    20 9    
3    20 9    
4    75 9    
5    75 9    
6    75 9    </code></pre>
</div>
</div>
<p>Use the <code>t.test()</code> function with the pooled sample <code>pooled</code> to construct a 95% confidence interval for the difference in mean wind speeds of North Atlantic storms in September compared to October. How does your answer compare to your confidence intervals in <a href="#question-13c">Question 13c</a> and <a href="#question-14">Question 14</a>? If the intervals are different, which confidence interval do you believe is most accurate?</p>
<section id="solution-to-question-15" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-15">Solution to Question 15</h3>
<hr>
<p>Complete the command below and then compare the result to your answers in <a href="#question-13c">Question 13c</a> and <a href="#question-14">Question 14</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(?? <span class="sc">~</span> ??, <span class="at">data =</span> ??, <span class="at">conf.level =</span> ??)<span class="sc">$</span>conf.int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="caution-using-t.test-for-a-difference-in-two-means" class="level2">
<h2 class="anchored" data-anchor-id="caution-using-t.test-for-a-difference-in-two-means">Caution Using <code>t.test()</code> for a Difference in Two Means</h2>
<hr>
<p>The variable <code>month</code> in the original sample <code>storms</code> has observations from <strong>10 different months</strong>. If you try running the command <code>t.test(wind ~ month, data = storms, conf.level = 0.95)$conf.int</code> you will receive an error since the categorical variable <code>month</code> has more than two classes. <span style="color:dodgerblue"><strong>The categorical variable used to split the data must have exactly 2 different classes</strong></span>. In solving <a href="#question-15">Question 15</a> we avoided this error by:</p>
<ul>
<li>First creating the <code>pooled</code> sample that included only two months, September and October.</li>
<li>Then using <code>t.test()</code> with the <code>pooled</code> sample instead of the full <code>storms</code> data set.</li>
</ul>
<p>Otherwise, we can split the original sample into two independent samples <code>x</code> and <code>y</code> and use the <code>t.test()</code> function as we did in <a href="#question-14">Question 14</a> with independent wind speed samples <code>sep.wind</code> and <code>oct.wind</code>.</p>
<hr>
<p><img src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" class="img-fluid" alt="Creative Commons License"> <nbsp></nbsp></p>
<p><em>Statistical Methods: Exploring the Uncertain</em> by <a href="https://github.com/CU-Denver-MathStats-OER/Statistical-Theory">Adam Spiegler</a> is licensed under a <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./18-Bootstrap-Other-Stats.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">5.3: Bootstrapping Comparitive Statistics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./20-Parametric-CI-Proportions.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-title">5.5: Parametric Confidence Intervals for Proportions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Statistical Methods: Exploring the Uncertain by Adam Spiegler</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right"><img src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" class="img-fluid" alt="Creative Commons License"> <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-N-SA 4.0</a></div>
  </div>
</footer>



</body></html>