<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6.2: Permutation Tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">6.2: Permutation Tests</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><a href="https://githubtocolab.com/CU-Denver-MathStats-OER/Statistical-Theory/blob/main/Chap6/22-Permutation-Tests.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" class="img-fluid" alt="Open In Colab"></a> <nbsp></nbsp></p>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/b/b3/Permutation_generation_algorithms.svg" class="img-fluid figure-img" style="width:55.0%" alt="Permutation Illustration"></p>
<figcaption class="figure-caption">Credit: Torsten Mütze, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>, via Wikimedia Commons</figcaption>
</figure>
</div>
<section id="a-summary-of-hypothesis-testing" class="level1">
<h1>A Summary of Hypothesis Testing</h1>
<hr>
<p>In the section <a href="./21-Intro-Hypothesis-Tests.html">Introduction to Hypothesis Tests</a>, we walked through the process of performing a statistical hypothesis test:</p>
<ol type="1">
<li>State the <span style="color:dodgerblue"><strong>null and alternative hypotheses</strong></span> in terms of population parameter(s).</li>
<li>Compute <span style="color:dodgerblue"><strong>test statistic(s)</strong></span> from random sample(s).</li>
<li>Calculate the <span style="color:dodgerblue"><strong>p-value</strong></span> to help assess which claim is more likely to be true.</li>
<li>What <span style="color:dodgerblue"><strong>conclusions</strong></span> (if any) can we make about the two competing claims?</li>
</ol>
<p>See <a href="./21-Intro-Hypothesis-Tests.html">Introduction to Hypothesis Tests</a> for a refresher on Steps 1 and 2. We also informally explored the concept of <a href="./21-Intro-Hypothesis-Tests.html#sec-informal-p">statistical significance</a>. Today, we focus on Step 3 and discuss a resampling method, called a <span style="color:dodgerblue"><strong>permutation test</strong></span>, that we can use to calculate p-values to assess significance.</p>
<section id="the-null-distribution-and-p-values" class="level2">
<h2 class="anchored" data-anchor-id="the-null-distribution-and-p-values">The Null Distribution and p-values</h2>
<hr>
<p>Recall the logic of hypothesis test. We want to assess which of two competing claims, the null hypothesis <span class="math inline">\(H_0\)</span> or the alternative hypothesis <span class="math inline">\(H_a\)</span>, are more likely to be true. We assume <span class="math inline">\(H_0\)</span> is true and consider whether the sample data supports or refutes the null claim.</p>
<ul>
<li>The <span style="color:dodgerblue"><strong>null distribution</strong></span> is the distribution of the test statistic <strong>if the null hypothesis is true</strong>. We use the null distribution to calculate the p-value.</li>
<li>The <span style="color:dodgerblue"><strong>p-value</strong></span> is the <strong>probability that we would get a random sample</strong> with a test statistic as or more extreme as the observed test statistic <strong>if the null hypothesis were true</strong>.</li>
</ul>
<p><span class="math display">\[{\large {\color{dodgerblue}{p\mbox{-value} = P( \mbox{test statistic as or more extreme than observed} \ | \ H_0 \mbox{ is true} )}}}.\]</span></p>
<ul>
<li>The <strong>smaller the <span class="math inline">\(p\)</span>-value</strong>, the <strong>less likely the sample</strong> is assuming <span class="math inline">\(H_0\)</span> is true.</li>
<li>There is evidence that <strong>contradicts <span class="math inline">\(H_0\)</span> and supports <span class="math inline">\(H_a\)</span></strong>.</li>
<li>The <strong>smaller the <span class="math inline">\(p\)</span>-value</strong>, the <strong>more statistically significant</strong> the result.</li>
</ul>
</section>
</section>
<section id="case-study-the-unscrupulous-diners-dilemma" class="level1">
<h1>Case Study: The Unscrupulous Diner’s Dilemma</h1>
<hr>
<p>We previously considered the <a href="./21-Intro-Hypothesis-Tests.html#sec-diner">unscrupulous diner’s dilemma</a><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<blockquote class="blockquote">
<p>The unscrupulous diner’s dilemma is a problem faced frequently in social settings. When a group of diners jointly enjoys a meal at a restaurant, often an unspoken agreement exists to divide the check equally. A selfish diner could thereby enjoy exceptional dinners at bargain prices. This dilemma typifies a class of serious social problems<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> from environmental protection and resource conservation to eliciting charity donations and slowing arms races.</p>
</blockquote>
<p>Researchers wanted to test whether people order more food and beverages when they know the bill is going to be split evenly compared to when each person only pays for what they ordered.</p>
<section id="step-1-state-the-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="step-1-state-the-hypotheses">Step 1: State the Hypotheses</h2>
<hr>
<ul>
<li><span class="math inline">\(H_0\)</span>: There is no difference in how much people order regardless of how the bill is split. <span class="math inline">\({\color{dodgerblue}{\mu_{\rm even} - \mu_{\rm control}=0}}.\)</span></li>
<li><span class="math inline">\(H_a\)</span>: People order more when the bill is split evenly as opposed to when each person pays for what they order. <span class="math inline">\({\color{dodgerblue}{\mu_{\rm even} - \mu_{\rm control}&gt;0}}.\)</span></li>
</ul>
</section>
<section id="step-2-collect-sample-data-and-define-a-test-statistic" class="level2">
<h2 class="anchored" data-anchor-id="step-2-collect-sample-data-and-define-a-test-statistic">Step 2: Collect Sample Data and Define a Test Statistic</h2>
<hr>
<p>8 people volunteered to take part in the study.</p>
<ul>
<li>4 people were randomly assigned to sit at a table where they were told the bill would be evenly split between the 4 people.</li>
<li>4 people were randomly assigned to sit at a table where they were told each person would pay only for what they order themselves.</li>
</ul>
<p>The results of the study are given in the tables below:</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Even Split Group</th>
<th>Pay for what you order (control) Group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\$15.00\)</span>, <span class="math inline">\(\$8.00\)</span>, <span class="math inline">\(\$8.75\)</span>, <span class="math inline">\(\$13.17\)</span></td>
<td><span class="math inline">\(\$8.50\)</span> , <span class="math inline">\(\$7.90\)</span> , <span class="math inline">\(\$10.85\)</span>, <span class="math inline">\(\$7.43\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\bar{x}_{\rm even} = \$11.23\)</span></td>
<td><span class="math inline">\(\bar{x}_{\rm control} = \$8.67\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><strong>We can use the difference in the two sample means as a test statistic:</strong></li>
</ul>
<p><span class="math display">\[{\color{dodgerblue}{T= \bar{x}_{\rm even} - \bar{x}_{\rm control} = 2.56}}\]</span></p>
</section>
<section id="step-3-how-extreme-is-the-observed-difference" class="level2">
<h2 class="anchored" data-anchor-id="step-3-how-extreme-is-the-observed-difference">Step 3: How Extreme Is the Observed Difference?</h2>
<hr>
<p>The p-value is the probability of getting a difference in sample means between the even-split and self-pay groups as or more extreme than the observed test statistic, <span class="math inline">\(\bar{x}_{\rm even} - \bar{x}_{\rm control} = 2.56\)</span>. In this case (one-tailed test), more extreme implies a difference that is even bigger than <span class="math inline">\(\$2.56\)</span>.</p>
<p><span class="math display">\[{\color{dodgerblue}{\mbox{p-value} = P(\bar{x}_{\rm even} - \bar{x}_{\rm control} \geq 2.56 \ | \ H_0 \mbox{ is true} )}}\]</span></p>
<p>If <span class="math inline">\(H_0\)</span> is true, then <span class="math inline">\(\mu_{\rm even} - \mu_{\rm control} =0\)</span>. Under this assumption, the center of the sampling distribution for the difference in sample means would be <span class="math inline">\(0\)</span>. However, we do not know how much variability there is due to the sampling. <strong>Is a difference in sample means equal to <span class="math inline">\(\$2.56\)</span> a “big” difference, or is the difference within the margins we would expect due to the uncertainty of sampling?</strong></p>
<blockquote class="blockquote">
<p>How can we calculate the p-value if we do not know the underlying probability distribution for the test statistic <span class="math inline">\(T = \mu_{\rm{even}} - \mu_{\rm{control}}\)</span> if <span class="math inline">\(H_0\)</span> is true?</p>
</blockquote>
</section>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<hr>
<p>If people order the same amount of food no matter how the bill is split (assuming <span class="math inline">\(H_0\)</span> is true), we assume each person would order the same amount of food regardless of the table they were seated at. <strong>Splitting by groups based on how the bill is paid is no different than if the eight values were just randomly divided into two groups of four people.</strong> If each person would have ordered the same regardless of which table they were seated at, then another possible sample could have been:</p>
<table class="table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Even Split Group</th>
<th>Pay for what you order (control) Group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mathbf{\color{dodgerblue}{\$7.43}}\)</span> , <span class="math inline">\(\$8.00\)</span>, <span class="math inline">\(\$8.75\)</span>, <span class="math inline">\(\$13.17\)</span></td>
<td><span class="math inline">\(\$8.50\)</span> , <span class="math inline">\(\$7.90\)</span> , <span class="math inline">\(\$10.85\)</span>, <span class="math inline">\(\mathbf{\color{dodgerblue}{\$15.00}}\)</span></td>
</tr>
</tbody>
</table>
<section id="question-1a" class="level3">
<h3 class="anchored" data-anchor-id="question-1a">Question 1a</h3>
<hr>
<p>What would be the test statistic for the two samples above?</p>
<section id="solution-to-question-1a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-1a">Solution to Question 1a</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find the test statistic for another possible sample</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-1b" class="level3">
<h3 class="anchored" data-anchor-id="question-1b">Question 1b</h3>
<hr>
<p>How many different ways can we divide the eight participants into two groups of four?</p>
<section id="solution-to-question-1b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-1b">Solution to Question 1b</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># how many possible ways can we create two groups of 4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="sec-perm-test" class="level1">
<h1>Two-Sample Permutation Tests</h1>
<hr>
<p>To perform a <span style="color:dodgerblue"><strong>two-sample permutation test</strong></span> on data collected from two samples size <span class="math inline">\(m\)</span> and <span class="math inline">\(n\)</span>:</p>
<ol type="1">
<li>Pool the <span class="math inline">\(m+n\)</span> values together.</li>
<li>Draw a <span style="color:dodgerblue"><strong>permutation resample</strong></span> of size <span class="math inline">\(m\)</span> (size of first sample), <strong>without replacement</strong>.</li>
<li>Use the remaining <span class="math inline">\(n\)</span> (size of second sample) observations for the other sample.</li>
<li>Calculate the difference in means or another statistic to compares samples.</li>
<li>Repeat the resampling process many times and construct the distribution of test statistics.</li>
</ol>
<p><span style="color:dodgerblue"><strong>The p-value is the proportion of times the randomized statistics are as or more extreme than the observed difference.</strong></span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/CU-Denver-MathStats-OER/Statistical-Theory/main/Images/22fig-meal-perm.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption class="figure-caption">Permutation resamples of the Unscrupulous Diners Dilemma Data</figcaption>
</figure>
</div>
</section>
<section id="case-study-melanoma-lesion-thickness" class="level1">
<h1>Case Study: Melanoma Lesion Thickness</h1>
<hr>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/d/d0/Superficial_spreading_melanoma_in_situ_on_dermoscopy%2C_reflectance_confocal_microscopy_and_histopathology_2.jpg" class="img-fluid figure-img" style="width:55.0%" alt="Superficial spreading melanoma"></p>
<figcaption class="figure-caption">Credit: Braga, Macedo, Pinto, et. al., <a href="https://creativecommons.org/licenses/by/4.0">CC BY 4.0</a>, via Wikimedia Commons</figcaption>
</figure>
</div>
<p>Skin is the largest organ in the human body. In the United States, skin cancer is the most common cancer. Current estimates are that one in five Americans will develop skin cancer in their lifetime<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. There are different types of skin cancers, and melanoma is one form of skin cancer that is particularly dangerous if not detected early. However, if a skin lesion is detected early, it can be surgically removed before it spreads, and a patient generally has good long-term outcomes.</p>
<p>The data set <code>melanoma</code> in the <code>boot</code> package contains measurements from a random sample of <span class="math inline">\(205\)</span> patients with malignant melanoma at the University Hospital of Odense in Denmark. Each patient had a skin lesion (or tumor) surgically removed and various attributes of the patient and tumors are recorded. Run the code cell below to load the <code>boot</code> package and summarize the variables in the <code>melanoma</code> data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(melanoma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      time          status          sex              age             year     
 Min.   :  10   Min.   :1.00   Min.   :0.0000   Min.   : 4.00   Min.   :1962  
 1st Qu.:1525   1st Qu.:1.00   1st Qu.:0.0000   1st Qu.:42.00   1st Qu.:1968  
 Median :2005   Median :2.00   Median :0.0000   Median :54.00   Median :1970  
 Mean   :2153   Mean   :1.79   Mean   :0.3854   Mean   :52.46   Mean   :1970  
 3rd Qu.:3042   3rd Qu.:2.00   3rd Qu.:1.0000   3rd Qu.:65.00   3rd Qu.:1972  
 Max.   :5565   Max.   :3.00   Max.   :1.0000   Max.   :95.00   Max.   :1977  
   thickness         ulcer      
 Min.   : 0.10   Min.   :0.000  
 1st Qu.: 0.97   1st Qu.:0.000  
 Median : 1.94   Median :0.000  
 Mean   : 2.92   Mean   :0.439  
 3rd Qu.: 3.56   3rd Qu.:1.000  
 Max.   :17.42   Max.   :1.000  </code></pre>
</div>
</div>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<hr>
<p>Based on the <code>summary(melanoma)</code> output, give a possible statistical question that could be analyzed using a hypothesis test. Which variable(s) in the <code>melanoma</code> data set would be involved in your analysis?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Run <code>?melanoma</code> to access the help documentation and learn more about the data.</p>
</div>
</div>
<section id="solution-to-question-2" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-2">Solution to Question 2</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<hr>
<p>Which variables in <code>melanoma</code> are categorical? Are those variables being stored as categorical variables? If so, explain how you can tell. If not, in the code cell below, convert the categorical variables to a <code>factor</code>.</p>
<section id="solution-to-question-3" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-3">Solution to Question 3</h3>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># if needed, convert each categorical variable to a factor</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="creating-a-pooled-sample" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-pooled-sample">Creating a Pooled Sample</h2>
<hr>
<p>One possible question we could ask: <em>“Is the mean tumor thickness greater for all people with fatal melanoma compared to the mean tumor thickness for all people that survive melanoma?”</em> The two variables of interest are <code>status</code> and <code>thickness</code>.</p>
<ul>
<li><code>status</code>: The patients status at the end of the study. <code>1</code> indicates that they had died from melanoma, <code>2</code> indicates that they were still alive and <code>3</code> indicates that they had died from causes unrelated to their melanoma.</li>
<li><code>thickness</code>: Tumor thickness in millimeters (mm).</li>
</ul>
<p>For our study, we are comparing two independent populations:</p>
<ul>
<li>People that have a melanoma tumor removed and survive. This is <code>status</code> group <code>2</code>.</li>
<li>People that have a melanoma tumor removed and died from melanoma. This is <code>status</code> group <code>1</code>.</li>
<li>The people in <code>status</code> group <code>3</code> we exclude from this analysis.</li>
</ul>
</section>
<section id="question-3-1" class="level2">
<h2 class="anchored" data-anchor-id="question-3-1">Question 3</h2>
<hr>
<p>Answer the questions below to state our hypotheses, organize our data, and calculate a test statistic to help determine whether the mean tumor thickness is greater for all people with fatal melanoma compared to the mean tumor thickness for all people that survive melanoma?</p>
<section id="question-3a" class="level3">
<h3 class="anchored" data-anchor-id="question-3a">Question 3a</h3>
<hr>
<p>Create side-by-side box plots to display the distribution of tumor thickness for each of the three <code>status</code> groups <code>1</code> (died from melanoma), <code>2</code> (survived), and <code>3</code> (died from other causes).</p>
<section id="solution-to-question-3a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3a">Solution to Question 3a</h4>
<hr>
<p>Fill in the <code>boxplot()</code> command to answer the question.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(??)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-3b" class="level3">
<h3 class="anchored" data-anchor-id="question-3b">Question 3b</h3>
<hr>
<p>The function <code>tapply(data, index, function)</code> has three inputs:</p>
<ul>
<li>The <code>data</code> is the data you want to summarize.</li>
<li>The <code>index</code> is a categorical feature that will split the data into two or more different classes or factors.</li>
<li>The <code>function</code> is some function that you want to apply to the data.</li>
</ul>
<p>Interpret the output from the code cell below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run code and interpret output below</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(melanoma<span class="sc">$</span>thickness, melanoma<span class="sc">$</span>status, length)  <span class="co"># nothing to edit</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  1   2   3 
 57 134  14 </code></pre>
</div>
</div>
<section id="solution-to-question-3b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3b">Solution to Question 3b</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-3c" class="level3">
<h3 class="anchored" data-anchor-id="question-3c">Question 3c</h3>
<hr>
<p>We would like to use the data in <code>melanoma</code> to test the if the mean tumor thickness is greater for all people with fatal melanoma compared to the mean tumor thickness for all people that survive melanoma? State the corresponding null and alternative hypotheses for this test. Be sure to state each hypothesis both in words and using mathematical notation.</p>
<section id="solution-to-question-3c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3c">Solution to Question 3c</h4>
<hr>
<ul>
<li><p><span class="math inline">\(H_0\)</span>:</p></li>
<li><p><span class="math inline">\(H_a\)</span>:</p></li>
</ul>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-3d" class="level3">
<h3 class="anchored" data-anchor-id="question-3d">Question 3d</h3>
<hr>
<p>Using the code cell below, subset the <code>melanoma</code> data to create three different vectors:</p>
<ol type="1">
<li>The vector <code>died</code> is the <code>thickness</code> values for <code>status</code> group 1.</li>
<li>The vector <code>survived</code> is the <code>thickness</code> values for <code>status</code> group 2.</li>
<li>The vector <code>pooled</code> is the <code>thickness</code> values for both <code>status</code> groups 1 and 2 (excluding group 3).</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The logical operator <code>==</code> means “is equal to” while the logical operator <code>!=</code> means “is not equal to”.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The option <code>drop = TRUE</code> means the output will be a vector of numerical values as opposed to a data frame that has a variable with the name <code>thickness</code>. For example, if we want to calculate the sample mean for the <code>pooled</code> data:</p>
<ul>
<li>Since the data is stored as a vector, we use <code>mean(pooled)</code>. There are no headers in vectors.</li>
<li>If the data is stored as a data frame, we do need to use headers and have <code>mean(pooled$thickness)</code>.</li>
</ul>
<p>The output of the code cell below are vectors, so we do not use the <code>$var_name</code> convention when referring to the sample data which helps simplify the code a little.</p>
</div>
</div>
<section id="solution-to-question-3d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3d">Solution to Question 3d</h4>
<hr>
<p>Replace each of the 9 <code>??</code> with an appropriate value or variable name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>died <span class="ot">&lt;-</span> <span class="fu">subset</span>(melanoma, <span class="at">select =</span> ??, ?? <span class="sc">==</span> <span class="st">"??"</span>, <span class="at">drop =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>survived <span class="ot">&lt;-</span> <span class="fu">subset</span>(melanoma, <span class="at">select =</span> ??, ?? <span class="sc">==</span> <span class="st">"??"</span>, <span class="at">drop =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>pooled <span class="ot">&lt;-</span> <span class="fu">subset</span>(melanoma, <span class="at">select =</span> ??, ?? <span class="sc">!=</span> <span class="st">"??"</span>, <span class="at">drop =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-3e" class="level3">
<h3 class="anchored" data-anchor-id="question-3e">Question 3e</h3>
<hr>
<p>Using the vectors <code>died</code>, <code>survived</code>, and <code>pooled</code> from <a href="#question-3d">Question 3d</a>, calculate the sample size and the sample mean for each of the samples <code>died</code>, <code>survived</code>, and <code>pooled</code>.</p>
<section id="solution-to-question-3e" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3e">Solution to Question 3e</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>n.died <span class="ot">&lt;-</span> ??  <span class="co"># size of sample of melanoma deaths</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>n.survived <span class="ot">&lt;-</span> ??  <span class="co"># size of sample of survivors</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>n.pooled <span class="ot">&lt;-</span> ??  <span class="co"># size of both samples pooled together</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>xbar.died <span class="ot">&lt;-</span> ??  <span class="co"># mean thickness of sample that died</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>xbar.survived <span class="ot">&lt;-</span> ??  <span class="co"># mean thickness of sample that survived</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>xbar.pooled <span class="ot">&lt;-</span> ??  <span class="co"># mean thickness of pooled sample</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># print each result to screen</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>n.died </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>n.survived </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>n.pooled </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>xbar.died </span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>xbar.survived </span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>xbar.pooled   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-3f" class="level3">
<h3 class="anchored" data-anchor-id="question-3f">Question 3f</h3>
<hr>
<p>Based on the output in <a href="#question-3e">Question 3e</a>, calculate, store, and print the test statistic for this test to the screen.</p>
<section id="solution-to-question-3f" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3f">Solution to Question 3f</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>test.stat <span class="ot">&lt;-</span> ??  <span class="co"># compute test statistic</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>test.stat  <span class="co"># print test statistic to screen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="constructing-a-permutation-distribution" class="level1">
<h1>Constructing a Permutation Distribution</h1>
<hr>
<section id="step-1-create-a-vector-of-pooled-data" class="level2">
<h2 class="anchored" data-anchor-id="step-1-create-a-vector-of-pooled-data">Step 1: Create a Vector of Pooled Data</h2>
<hr>
<p>See the code used to create <code>pooled</code> in <a href="#question-3d">Question 3d</a>.</p>
</section>
<section id="step-2-create-resamples-for-each-treatment-group" class="level2">
<h2 class="anchored" data-anchor-id="step-2-create-resamples-for-each-treatment-group">Step 2: Create Resamples for Each Treatment Group</h2>
<hr>
<p>For this step, it is important to note the size of each original sample. From <a href="#question-3e">Question 3e</a> we know</p>
<ul>
<li>The sample <code>died</code> consists of 57 observations.</li>
<li>The sample <code>survived</code> consists of 134 observations.</li>
<li>The <code>pooled</code> sample consists of <span class="math inline">\(57 + 134= 191\)</span> observations.</li>
</ul>
<section id="create-an-index-vector" class="level4">
<h4 class="anchored" data-anchor-id="create-an-index-vector">Create an Index Vector</h4>
<hr>
<p>We first create a vector called <code>index</code> that selects (without replacement) 57 random integers out of the integers <span class="math inline">\(1, 2, \ldots , 191\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3021</span>)  <span class="co"># fix the randomization seeding</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>index <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">191</span>, <span class="at">size =</span> <span class="dv">57</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)  <span class="co"># these are the 57 observations chosen for resample 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The command <code>head(index)</code> shows the first 6 values in the vector <code>index</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(index)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  55 164  88 189 171  68</code></pre>
</div>
</div>
<p>The first <code>index</code> value 55 means observation 55 from the <code>pooled</code> vector is the first thickness value randomly assigned to the <code>died</code> sample. From the code cell below, we see the 55th observation in <code>pooled</code> is a thickness of <span class="math inline">\(0.81\)</span> mm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>pooled[<span class="dv">55</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.81</code></pre>
</div>
</div>
<p>The next <code>index</code> value 164 means observation 164 from the <code>pooled</code> vector is the second thickness value randomly assigned to the <code>died</code> sample. From the code cell below, we see the 164th observation in <code>pooled</code> is a thickness of <span class="math inline">\(0.65\)</span> mm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pooled[<span class="dv">164</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.65</code></pre>
</div>
</div>
</section>
<section id="use-index-to-select-resample-of-group-1" class="level4">
<h4 class="anchored" data-anchor-id="use-index-to-select-resample-of-group-1">Use <code>index</code> to Select Resample of Group 1</h4>
<hr>
<p>The <code>index</code> vector is a vector of integers that tells us which values in <code>pooled</code> are randomly assigned to the <code>died</code> resample. However, <code>index</code> does not contain the corresponding thicknesses of the selected observations. The vector <code>pooled[index]</code> will contain the tumor thicknesses for all 57 randomly selected observations picked in <code>index</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>died.resample <span class="ot">&lt;-</span> pooled[index]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="use--index-to-select-the-remaining-values-for-resample-group-2" class="level4">
<h4 class="anchored" data-anchor-id="use--index-to-select-the-remaining-values-for-resample-group-2">Use <code>-index</code> to Select the Remaining Values for Resample Group 2</h4>
<hr>
<ul>
<li>The vector <code>index</code> consists of 57 randomly selected integers out of the integers <span class="math inline">\(1, 2, \ldots , 191\)</span>.</li>
<li>The vector <code>-index</code> contains the remaining 134 integers that were not selected for <code>index</code>.</li>
<li>The vector <code>pooled[-index]</code> will contain thicknesses for the remaining 134 observations in resample group 2.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>survived.resample <span class="ot">&lt;-</span> pooled[<span class="sc">-</span>index]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="step-3-calculate-the-test-statistic-for-the-resamples" class="level2">
<h2 class="anchored" data-anchor-id="step-3-calculate-the-test-statistic-for-the-resamples">Step 3: Calculate the Test Statistic for the Resamples</h2>
<hr>
<p>Calculate the difference in the sample means between the two resamples.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>perm.stat <span class="ot">&lt;-</span> <span class="fu">mean</span>(died.resample) <span class="sc">-</span> <span class="fu">mean</span>(survived.resample)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>perm.stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1487287</code></pre>
</div>
</div>
</section>
<section id="step-4-repeat-this-many-times-to-construct-a-permutation-distribution" class="level2">
<h2 class="anchored" data-anchor-id="step-4-repeat-this-many-times-to-construct-a-permutation-distribution">Step 4: Repeat this Many Times to Construct a Permutation Distribution</h2>
<hr>
<ul>
<li>In practice, it takes a lot of time and energy (and money) to generate all possible resamples (without any duplicate resamples).
<ul>
<li>Instead we’ll generate a lot of resamples rather than all possible resamples.</li>
</ul></li>
<li>We’ll use <span class="math inline">\(N=10^5-1=99,\!999\)</span> as the default number of resamples. <span style="color:tomato"><strong>Why use 99,999 resamples?</strong></span>
<ul>
<li>We may not generate the original sample as one of the resamples.</li>
<li>We want to be sure that we do include the original sample when we calculate the p-value.</li>
<li>We will add the original sample back in with the <span class="math inline">\(99,\!999\)</span> resamples giving <span class="math inline">\(100,\!000\)</span> samples.</li>
</ul></li>
<li>The resulting distribution of test statistics of the permutation resamples is called a <span style="color:dodgerblue"><strong>permutation distribution</strong></span>.</li>
<li>We use the permutation distribution as an estimate for the null distribution to compute the p-value.</li>
</ul>
</section>
<section id="question-4" class="level2">
<h2 class="anchored" data-anchor-id="question-4">Question 4</h2>
<hr>
<p>Complete the first code cell below to create a permutation distribution for the difference in sample mean tumor thickness. Be sure you have already created the vector <code>pooled</code> in <a href="#question-3d">Question 3d</a> and stored <code>test.stat</code> in <a href="#question-3f">Question 3f</a>.</p>
<p>After generating a permutation distribution, run the second code cell below to create a histogram to display the distribution of resample statistics along with a red vertical line through the observed test statistic. There is nothing to edit in the second code cell.</p>
<section id="solution-to-question-4" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-4">Solution to Question 4</h3>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="do">##########################################</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># save all 99,999 permutation resample </span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># statistics to the vector perm.stat</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="do">##########################################</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span> <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>perm.stat <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  index <span class="ot">&lt;-</span> <span class="fu">sample</span>(??, <span class="at">size =</span> ??, <span class="at">replace =</span> ??)  <span class="co"># create index vector</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  x.died <span class="ot">&lt;-</span> ??  <span class="co"># use index to select died resample</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  x.survived <span class="ot">&lt;-</span> ??  <span class="co"># the rest of the values go to survived resample</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  perm.stat[i] <span class="ot">&lt;-</span> ??  <span class="co"># calc difference in sample means</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="do">##################################################</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># plot permutation distribution as a histogram</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># mark observed test stat with red vertical line</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="do">##################################################</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(perm.stat, <span class="at">xlab =</span> <span class="st">"xbar.died - xbar.survived"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Permutation Distribution"</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> test.stat, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="p-values-with-permutation-distributions" class="level1">
<h1>p-values with Permutation Distributions</h1>
<hr>
<p>We use the permutation distribution as an estimate for the null distribution. The p-value is the proportion of all resampled test statistics that are as or more extreme than the observed test statistic. We can use a logical test to help compute this proportion.</p>
<section id="question-5" class="level2">
<h2 class="anchored" data-anchor-id="question-5">Question 5</h2>
<hr>
<p>How likely is it to get resamples with a difference in means as or more extreme than the observed test statistic? Explain what the code below is doing in practical terms.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>p.value <span class="ot">&lt;-</span> <span class="fu">sum</span>(perm.stat <span class="sc">&gt;=</span> test.stat)<span class="sc">/</span>N</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>p.value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="solution-to-question-5" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-5">Solution to Question 5</h3>
<hr>
<p>Interpret the code cell above.</p>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-6" class="level2">
<h2 class="anchored" data-anchor-id="question-6">Question 6</h2>
<hr>
<p>The calculation from <a href="#question-5">Question 5</a> used the <span class="math inline">\(N=10^5-1=99,\!999\)</span> permutation resamples, but recall we want to be sure to include the original, observed sample when computing the p-value. Explain how the code cell below accomplishes this goal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>p.value <span class="ot">&lt;-</span> (<span class="fu">sum</span>(perm.stat <span class="sc">&gt;=</span> test.stat) <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> (N <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>p.value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="solution-to-question-6" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-6">Solution to Question 6</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-7" class="level2">
<h2 class="anchored" data-anchor-id="question-7">Question 7</h2>
<hr>
<p>Interpret the practical meaning of the p-value from <a href="#question-6">Question 6</a> to a person who is not very familiar with statistics.</p>
<section id="solution-to-question-7" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-7">Solution to Question 7</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
<section id="permutation-test-for-a-difference-in-variances" class="level1">
<h1>Permutation Test for a Difference in Variances</h1>
<hr>
<section id="question-8" class="level2">
<h2 class="anchored" data-anchor-id="question-8">Question 8</h2>
<hr>
<p>Ulceration is a breakdown of the skin over the melanoma tumor. Using the data set <code>melanoma</code> from the <code>boot</code> package, perform a permutation test to see if the variance of the tumor thickness for ulcerated tumors is different from the variance of the tumor thickness for non-ulcerated tumors.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The variable <code>ulcer</code> indicates whether the removed tumor was ulcerated (<code>ulcer</code> group <code>1</code>) or not ulcerated (<code>ulcer</code> group <code>0</code>).</p>
</div>
</div>
<section id="question-8a" class="level3">
<h3 class="anchored" data-anchor-id="question-8a">Question 8a</h3>
<hr>
<p>Write out the null and alternative hypotheses using appropriate notation.</p>
<section id="solution-to-question-8a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-8a">Solution to Question 8a</h4>
<hr>
<ul>
<li><p><span class="math inline">\(H_0\)</span>:</p></li>
<li><p><span class="math inline">\(H_a\)</span>:</p></li>
</ul>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-8b" class="level3">
<h3 class="anchored" data-anchor-id="question-8b">Question 8b</h3>
<hr>
<p>What can we use as the test statistic? What is the value of the observed test statistic?</p>
<section id="solution-to-question-8b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-8b">Solution to Question 8b</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>test.stat2 <span class="ot">&lt;-</span> ??  <span class="co"># compute observed test statistic</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>test.stat2  <span class="co"># print output to screen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-8c" class="level3">
<h3 class="anchored" data-anchor-id="question-8c">Question 8c</h3>
<hr>
<p>Create a permutation distribution for the difference in sample variances.</p>
<section id="solution-to-question-8c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-8c">Solution to Question 8c</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nothing to edit in this cell</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>pooled2 <span class="ot">&lt;-</span> melanoma<span class="sc">$</span>thickness  <span class="co"># create pooled vector of all tumor thicknesses</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save resamples to vector called result</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span> <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create permutation distribution</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  index <span class="ot">&lt;-</span> <span class="fu">sample</span>(??, <span class="at">size =</span> ??, <span class="at">replace =</span> ??)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  result[i] <span class="ot">&lt;-</span> ??</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display permutation distribution and observed sample diff</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(result, <span class="at">xlab =</span> <span class="st">"diff in sample variances"</span>,</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Permutation Distribution"</span>)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">c</span>(<span class="sc">-</span>test.stat2, test.stat2), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-8d" class="level3">
<h3 class="anchored" data-anchor-id="question-8d">Question 8d</h3>
<hr>
<p>Calculate the p-value of the observed test statistic and interpret its meaning in practical terms.</p>
<section id="solution-to-question-8d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-8d">Solution to Question 8d</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the p-value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="permutation-test-for-a-difference-in-proportions" class="level1">
<h1>Permutation Test for a Difference in Proportions</h1>
<hr>
<section id="question-9" class="level2">
<h2 class="anchored" data-anchor-id="question-9">Question 9</h2>
<hr>
<p>Is the proportion of females with ulcerated tumors less than the proportion of males with ulcerated tumors?</p>
<section id="question-9a" class="level3">
<h3 class="anchored" data-anchor-id="question-9a">Question 9a</h3>
<hr>
<p>Write out the null and alternative hypotheses using appropriate notation.</p>
<section id="solution-to-question-9a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-9a">Solution to Question 9a</h4>
<hr>
<ul>
<li><p><span class="math inline">\(H_0\)</span>:</p></li>
<li><p><span class="math inline">\(H_a\)</span>:</p></li>
</ul>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-9b" class="level3">
<h3 class="anchored" data-anchor-id="question-9b">Question 9b</h3>
<hr>
<p>What can we use as the test statistic? What is the value of the observed test statistic?</p>
<section id="solution-to-question-9b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-9b">Solution to Question 9b</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># original ulceration data for female sample</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>female <span class="ot">&lt;-</span> <span class="fu">subset</span>(melanoma, <span class="at">select =</span> <span class="st">"ulcer"</span>, sex <span class="sc">==</span> <span class="st">"0"</span>, <span class="at">drop =</span> <span class="cn">TRUE</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># original ulceration data for male sample</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>male <span class="ot">&lt;-</span> <span class="fu">subset</span>(melanoma, <span class="at">select =</span> <span class="st">"ulcer"</span>, sex <span class="sc">==</span> <span class="st">"1"</span>, <span class="at">drop =</span> <span class="cn">TRUE</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co"># original ulceration data for both samples pooled together</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>pooled.sex <span class="ot">&lt;-</span> melanoma<span class="sc">$</span>ulcer </span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co"># enter a formula to compute the test statistic</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>test.diff.prop <span class="ot">&lt;-</span> ??</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-9c" class="level3">
<h3 class="anchored" data-anchor-id="question-9c">Question 9c</h3>
<hr>
<p>Create a permutation distribution for the difference in sample proportions.</p>
<section id="solution-to-question-9c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-9c">Solution to Question 9c</h4>
<hr>
<p>Complete the code cell below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span> <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>result.prop <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  index <span class="ot">&lt;-</span> <span class="fu">sample</span>(??, <span class="at">size =</span> ??, <span class="at">replace =</span> ??)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  result.prop[i] <span class="ot">&lt;-</span> ??</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(result.prop, <span class="at">xlab =</span> <span class="st">"phat1-phat2"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Permutation Distribution"</span>)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> test.diff.prop, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-9d" class="level3">
<h3 class="anchored" data-anchor-id="question-9d">Question 9d</h3>
<hr>
<p>Calculate the p-value of the observed test statistic and interpret its meaning in practical terms.</p>
<section id="solution-to-question-9d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-9d">Solution to Question 9d</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the p-value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="permutation-test-for-matched-pairs" class="level1">
<h1>Permutation Test for Matched Pairs</h1>
<hr>
<section id="question-10" class="level2">
<h2 class="anchored" data-anchor-id="question-10">Question 10</h2>
<hr>
<p>In this example, we use data collected from a matched pair designed study to determine whether smoking during pregnancy is associated with lower birth weight. In our study, we solicit volunteers that have already given birth to two babies. During one of the pregnancies, the parent smoked. During the other pregnancy, they did not smoke. Below is hypothetical data from such a study. A sample of <span class="math inline">\(n=10\)</span> people volunteer to share their data with the researchers from which we have 10 different pairs of birth weights (in grams) summarized in the table below.</p>
<table class="table">
<colgroup>
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No Smoking</td>
<td>2750</td>
<td>2920</td>
<td>3860</td>
<td>3402</td>
<td>2282</td>
<td>3790</td>
<td>3586</td>
<td>3487</td>
<td>2920</td>
<td>2835</td>
</tr>
<tr class="even">
<td>Smoked</td>
<td>1790</td>
<td>2381</td>
<td>3940</td>
<td>3317</td>
<td>2125</td>
<td>2665</td>
<td>3572</td>
<td>3156</td>
<td>2721</td>
<td>2225</td>
</tr>
</tbody>
</table>
<section id="question-10a" class="level3">
<h3 class="anchored" data-anchor-id="question-10a">Question 10a</h3>
<hr>
<p>If researchers are testing to see whether a baby born to a parent that smokes while pregnant is less, on average, at birth compared to a baby born by the same parent when they do not smoke while pregnant. Write out the null and alternative hypotheses using appropriate notation.</p>
<section id="solution-to-question-10a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-10a">Solution to Question 10a</h4>
<hr>
<ul>
<li><p><span class="math inline">\(H_0\)</span>:</p></li>
<li><p><span class="math inline">\(H_a\)</span>:</p></li>
</ul>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-10b" class="level3">
<h3 class="anchored" data-anchor-id="question-10b">Question 10b</h3>
<hr>
<p>What can we use as the test statistic? What is the value of the observed test statistic?</p>
<section id="solution-to-question-10b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-10b">Solution to Question 10b</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data from study</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>no <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2750</span>, <span class="dv">2920</span>, <span class="dv">3860</span>, <span class="dv">3402</span>, <span class="dv">2282</span>, </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>        <span class="dv">3790</span>, <span class="dv">3586</span>, <span class="dv">3487</span>, <span class="dv">2920</span>, <span class="dv">2835</span>)  <span class="co"># non-smoking births weights</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>smoker <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1790</span>, <span class="dv">2381</span>, <span class="dv">3940</span>, <span class="dv">3317</span>, <span class="dv">2125</span>, </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>            <span class="dv">2665</span>, <span class="dv">3572</span>, <span class="dv">3156</span>, <span class="dv">2721</span>, <span class="dv">2225</span>)  <span class="co"># matching smoking birth weight</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>diff <span class="ot">&lt;-</span> no <span class="sc">-</span> smoker  <span class="co"># differences between matched pairs</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the observed test statistic</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-10c" class="level3">
<h3 class="anchored" data-anchor-id="question-10c">Question 10c</h3>
<hr>
<p>When we construct a permutation distribution for the sample mean difference between matched pairs, we want to be sure the resampling we use <strong>preserves each pairing</strong>.</p>
<ul>
<li>We do not randomize how the pairs are formed.</li>
<li>Each pair of values should remain paired after resampling.</li>
<li>Instead, we randomly assign values in each pair to the smoker and non-smoker positions.</li>
</ul>
<p>For example, our original sample of matched pair differences is</p>
<table class="table">
<colgroup>
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No Smoking</td>
<td>2750</td>
<td>2920</td>
<td>3860</td>
<td>3402</td>
<td>2282</td>
<td>3790</td>
<td>3586</td>
<td>3487</td>
<td>2920</td>
<td>2835</td>
</tr>
<tr class="even">
<td>Smoked</td>
<td>1790</td>
<td>2381</td>
<td>3940</td>
<td>3317</td>
<td>2125</td>
<td>2665</td>
<td>3572</td>
<td>3156</td>
<td>2721</td>
<td>2225</td>
</tr>
<tr class="odd">
<td>Difference</td>
<td>960</td>
<td>539</td>
<td>-80</td>
<td>85</td>
<td>157</td>
<td>1125</td>
<td>14</td>
<td>331</td>
<td>199</td>
<td>610</td>
</tr>
</tbody>
</table>
<p>One possible resample is given below.</p>
<table class="table">
<colgroup>
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No Smoking Resample</td>
<td><span style="color:tomato">1790</span></td>
<td>2920</td>
<td>3860</td>
<td><span style="color:tomato">3317</span></td>
<td>2282</td>
<td><span style="color:tomato">2665</span></td>
<td>3586</td>
<td>3487</td>
<td>2920</td>
<td>2835</td>
</tr>
<tr class="even">
<td>Smoked Resample</td>
<td><span style="color:tomato">2750</span></td>
<td>2381</td>
<td>3940</td>
<td><span style="color:tomato">3402</span></td>
<td>2125</td>
<td><span style="color:tomato">3790</span></td>
<td>3572</td>
<td>3156</td>
<td>2721</td>
<td>2225</td>
</tr>
<tr class="odd">
<td>Difference Resample</td>
<td><span style="color:tomato">-960</span></td>
<td>539</td>
<td>-80</td>
<td><span style="color:tomato">-85</span></td>
<td>157</td>
<td><span style="color:tomato">-1125</span></td>
<td>14</td>
<td>331</td>
<td>199</td>
<td>610</td>
</tr>
</tbody>
</table>
<p>To create a permutation distribution for the sample mean difference between matched pairs, <span style="color:dodgerblue"><strong>we randomly choose a sign (positive or negative) for each observed matched-pair difference.</strong></span> Complete the code cell below to generate a permutation distribution for the sample mean difference between matched pairs.</p>
<section id="solution-to-question-10c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-10c">Solution to Question 10c</h4>
<hr>
<p>Complete and run the code cell below to create a permutation distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5-1</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>perm.match <span class="ot">&lt;-</span><span class="fu">numeric</span>(N)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># for each pair, randomly assign the difference to be positive or negative.</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># then calculate the new mean of the paired differences</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  sign <span class="ot">&lt;-</span><span class="fu">sample</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>), <span class="at">size =</span> ??, <span class="at">replace =</span> ??) <span class="co"># random choose a sign -1 or 1</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  diff.resample <span class="ot">&lt;-</span> sign <span class="sc">*</span> diff</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  perm.match[i] <span class="ot">&lt;-</span> ??</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There is nothing to edit in the code cell below. Run the code cell below to plot the permutation distribution and test statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a histogram of the permutation distribution</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and add a vertical line at the observed test statistic</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(perm.match,  <span class="at">xlab =</span> <span class="st">"xbar-diff"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Permutation Distribution"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> test.match, <span class="at">col =</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-10d" class="level3">
<h3 class="anchored" data-anchor-id="question-10d">Question 10d</h3>
<hr>
<p>Calculate the p-value of the observed test statistic and interpret its meaning in practical terms.</p>
<section id="solution-to-question-10d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-10d">Solution to Question 10d</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the p-value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
<section id="question-11" class="level2">
<h2 class="anchored" data-anchor-id="question-11">Question 11</h2>
<hr>
<p><strong>Is there a difference in the price of groceries sold by Target and Walmart?</strong> The data set <code>Groceries</code> in the <code>resampledata</code> package contains a sample of <span class="math inline">\(n=24\)</span> different grocery items and a pair prices (price at Target and price at Walmart) advertised on their respective websites on a specific day.</p>
<ul>
<li>First we load the <code>resampledata</code> package.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(resampledata)  <span class="co"># load resampledata package</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Then we print the first six rows of the <code>Groceries</code> data.</li>
<li>Notice this is matched pairs data!</li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you received an error when running the code cell below, it is possible you do not have the <code>resampledata</code> package installed. From the R console, run the command <code>install.packages("resampledata")</code> to first install the <code>resampledata</code> packaged. Run the <code>library(resampledata)</code> command in the code cell above again. Then try running the code cell below again.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Groceries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                             Product    Size Target Walmart Units UnitType
1            Kellogg NutriGrain Bars  8 bars   2.50    2.78     8     bars
2 Quaker Oats Life Cereal  Original     18oz   3.19    6.01    18       oz
3         General Mills Lucky Charms 11.50oz   3.19    2.98    11       oz
4          Quaker Oats Old Fashioned    18oz   2.82    2.68    18       oz
5               Nabisco Oreo Cookies  14.3oz   2.99    2.98    14       oz
6                 Nabisco Chips Ahoy    13oz   2.64    1.98    13       oz</code></pre>
</div>
</div>
<ul>
<li>Next, we save corresponding Target and Walmart prices to separate vectors <code>target</code> and <code>walmart</code>.</li>
<li>The first six values in each vector are printed to the screen.</li>
<li>Notice the ordering of the values in each vector is very important to preserve.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>target <span class="ot">&lt;-</span> Groceries<span class="sc">$</span>Target</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>walmart <span class="ot">&lt;-</span> Groceries<span class="sc">$</span>Walmart</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(target)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.50 3.19 3.19 2.82 2.99 2.64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(walmart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.78 6.01 2.98 2.68 2.98 1.98</code></pre>
</div>
</div>
<p>Using the sample data stored in <code>target</code> and <code>walmart</code>, answer the questions below to perform a permutation test.</p>
<ol type="a">
<li><p>Set up hypotheses to test whether there a difference in the price of groceries sold by Target and Walmart?</p></li>
<li><p>What is the observed test statistic?</p></li>
<li><p>Create a permutation distribution for the sample mean difference between matched pairs.</p></li>
<li><p>Calculate the p-value.</p></li>
<li><p>Interpret the meaning of the p-value.</p></li>
</ol>
<section id="solution-to-question-11" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-11">Solution to Question 11</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
<hr>
<p><img src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" class="img-fluid" alt="Creative Commons License"> <nbsp></nbsp></p>
<p><em>Statistical Methods: Exploring the Uncertain</em> by <a href="https://github.com/CU-Denver-MathStats-OER/Statistical-Theory">Adam Spiegler</a> is licensed under a <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.</p>


</section>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Gneezy, U., E. Haruvy, and H. Yafe (2004), <a href="https://rady.ucsd.edu/_files/faculty-research/uri-gneezy/splitting-bill.pdf">“The Inefficiency of Splitting the Bill”</a>, <em>The Economic Journal</em> 114.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Glance, N., and B. Huberman, <a href="http://www.uvm.edu/~pdodds/files/papers/others/1994/glance1994a.pdf">“The Dynamics of Social Dilemmas”</a>, <em>Scientific American</em><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>American Academy of Dermatology, <a href="https://www.aad.org/media/stats-skin-cancer" class="uri">https://www.aad.org/media/stats-skin-cancer</a>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>