<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adam Spiegler, University of Colorado Denver">

<title>intro-to-vectors-dataframes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">



<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://githubtocolab.com/CU-Denver-MathStats-OER/Statistical-Theory/blob/main/Appendix/Intro-to-Vectors-Dataframes.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" class="img-fluid figure-img"></a></p>
<figcaption class="figure-caption">Open In Colab</figcaption>
</figure>
</div>
<section id="fundamentals-of-working-with-data" class="level1">
<h1>Fundamentals of Working with Data</h1>
<hr>
<p>Understanding the data types of the variables in our data set, and the structure of our data is crucial before we can identify what aspects might need to be cleaned and transformed so we can perform statistical analysis more efficiently.</p>
<p>This notebook is intended to be a brief overview of some fundamentals of working with data in R.</p>
<ul>
<li>How to save and display output of from commands?</li>
<li>What are the basic data types?</li>
<li>How to convert data types?</li>
<li>What are the data structures in R?</li>
<li>How to create or import a data frame?</li>
<li>How to slice and extract rows and columns of a data frame?</li>
</ul>
<p>These topics are important. This notebook just scratches the surface on many concepts. If you do not find a complete answer here, there are free resources online that dig deeper and more completely. Below are two such recommended references.</p>
<ul>
<li><p><a href="https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf">An Introduction to R</a> by the Developers of R</p></li>
<li><p><a href="https://swcarpentry.github.io/r-novice-inflammation/13-supp-data-structures/">Programming with R Guide to Data Types and Structures</a></p></li>
</ul>
<section id="loading-packages-with-the-library-command" class="level2">
<h2 class="anchored" data-anchor-id="loading-packages-with-the-library-command">Loading Packages with the <code>library()</code> Command</h2>
<hr>
<p>To explore some fundamentals of working with data in R, we will use the <code>storms</code> data set which is located in the package <code>dplyr</code>.</p>
<ul>
<li>The <code>dplyr</code> package is already installed in Google Colaboratory</li>
<li>We still need to use a <code>library</code> command to load the package.</li>
<li><span style="color:dodgerblue"><strong>Run the code cell below to load the <code>dplyr</code> package.</strong></span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the library of functions and data in dplyr</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="help-documentation" class="level2">
<h2 class="anchored" data-anchor-id="help-documentation">Help Documentation</h2>
<hr>
<p>The functions introduced in this document have robust help documentation with lots of options to customize. If you want to view help documentation for any of the functions used in this document, run commands such<code>?typeof</code>, <code>?is.numeric</code>, <code>?read.table</code>, and so on.</p>
</section>
</section>
<section id="getting-to-know-our-data" class="level1">
<h1>Getting to Know Our Data</h1>
<hr>
<p>The package <code>dplyr</code> contains a data set called <code>storms</code>. Let’s find some useful information about this data.</p>
<ul>
<li>The code cell below will provide a numeric summary of all variables in the <code>storms</code> data.</li>
<li>Recall we need to first run the command <code>library(dplyr)</code> in the code cell above to be able to access <code>storms</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get a numerical summary of all variables</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(storms)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     name                year          month             day       
 Length:19066       Min.   :1975   Min.   : 1.000   Min.   : 1.00  
 Class :character   1st Qu.:1993   1st Qu.: 8.000   1st Qu.: 8.00  
 Mode  :character   Median :2004   Median : 9.000   Median :16.00  
                    Mean   :2002   Mean   : 8.699   Mean   :15.78  
                    3rd Qu.:2012   3rd Qu.: 9.000   3rd Qu.:24.00  
                    Max.   :2021   Max.   :12.000   Max.   :31.00  
                                                                   
      hour             lat             long                         status    
 Min.   : 0.000   Min.   : 7.00   Min.   :-109.30   tropical storm     :6684  
 1st Qu.: 5.000   1st Qu.:18.40   1st Qu.: -78.70   hurricane          :4684  
 Median :12.000   Median :26.60   Median : -62.25   tropical depression:3525  
 Mean   : 9.094   Mean   :26.99   Mean   : -61.52   extratropical      :2068  
 3rd Qu.:18.000   3rd Qu.:33.70   3rd Qu.: -45.60   other low          :1405  
 Max.   :23.000   Max.   :70.70   Max.   :  13.50   subtropical storm  : 292  
                                                    (Other)            : 408  
    category          wind           pressure      tropicalstorm_force_diameter
 Min.   :1.000   Min.   : 10.00   Min.   : 882.0   Min.   :   0.0              
 1st Qu.:1.000   1st Qu.: 30.00   1st Qu.: 987.0   1st Qu.:   0.0              
 Median :1.000   Median : 45.00   Median :1000.0   Median : 110.0              
 Mean   :1.898   Mean   : 50.02   Mean   : 993.6   Mean   : 146.3              
 3rd Qu.:3.000   3rd Qu.: 65.00   3rd Qu.:1007.0   3rd Qu.: 220.0              
 Max.   :5.000   Max.   :165.00   Max.   :1024.0   Max.   :1440.0              
 NA's   :14382                                     NA's   :9512                
 hurricane_force_diameter
 Min.   :  0.00          
 1st Qu.:  0.00          
 Median :  0.00          
 Mean   : 14.81          
 3rd Qu.:  0.00          
 Max.   :300.00          
 NA's   :9512            </code></pre>
</div>
</div>
<section id="missing-data" class="level2">
<h2 class="anchored" data-anchor-id="missing-data">Missing Data</h2>
<hr>
<p>A <span style="color:dodgerblue"><strong>missing value</strong></span> occurs when the value of something isn’t known. R uses the special object <code>NA</code> to represent missing value. If you have a missing value, you should represent that value as <code>NA</code>. Note: The character string <code>"NA"</code> is not the same thing as <code>NA</code>.</p>
<ul>
<li>The <code>storms</code> data has properly coded 14,382 missing values for <code>category</code> since storms that are not hurricanes do not have a category.</li>
<li>The <code>storms</code> data has properly coded 9,512 missing values for each of <code>tropicalstorm_force_diameter</code> and <code>hurricane_force_diameter</code> since these value only began being recorded in 2004.</li>
</ul>
</section>
</section>
<section id="assignment-to-new-or-existing-objects" class="level1">
<h1>Assignment to New (or Existing) Objects</h1>
<hr>
<p>To store a data structure in the computer’s memory we must assign it a name.</p>
<p>Data structures can be stored using the assignment operator <code>&lt;-</code> or <code>=</code>.</p>
<p>Some comments:</p>
<ul>
<li>In general, both <code>&lt;-</code> and <code>=</code> <em>can</em> be used for assignment.</li>
<li><code>&lt;-</code> and <code>=</code> can be used identically most of the time, but not always.</li>
<li><span style="color:dodgerblue"><strong>It’s safer and more conventional to use <code>&lt;-</code> for assignment</strong></span>.</li>
</ul>
<p>In the following code, we compute the mean of a vector. <strong>Why can’t we see the result after running it</strong>?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> storms<span class="sc">$</span>wind  <span class="co"># wind is now stored in w</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>xbar.w <span class="ot">&lt;-</span> <span class="fu">mean</span>(w)  <span class="co"># compute mean wind speed and assign to xbar.w</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Once an object has been assigned a name, it can be printed by executing the name of the object.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>xbar.w  <span class="co"># print the mean wind speed to screen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50.01741</code></pre>
</div>
</div>
<ul>
<li>We can also print an object to screen using the <code>print()</code> function.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(xbar.w)  <span class="co"># print the mean with print() command</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50.01741</code></pre>
</div>
</div>
<ul>
<li>We can calculate, assign, and print the result by putting parenthesis around the assignment.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate, assign, and print standard deviation</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>(s <span class="ot">&lt;-</span> <span class="fu">sd</span>(w))  <span class="co"># note ( ) around the entire command</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25.50103</code></pre>
</div>
</div>
<ul>
<li><strong>Sometimes you want to see the result of a code cell, and sometimes you will not.</strong></li>
</ul>
</section>
<section id="basic-data-types" class="level1">
<h1>Basic Data Types</h1>
<hr>
<p>R has 6 basic <a href="https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Basic-types">data types</a>:</p>
<ol type="1">
<li><span style="color:dodgerblue"><strong>character</strong></span>: collections of characters. E.g., <code>"a"</code>, <code>"hello world!"</code></li>
<li><span style="color:dodgerblue"><strong>double</strong></span>: decimal numbers. e.g., <code>1.2</code>, <code>1.0</code></li>
<li><span style="color:dodgerblue"><strong>integer</strong></span>: whole numbers. In R, you must add <code>L</code> to the end of a number to specify it as an integer. E.g., <code>1L</code> is an integer but <code>1</code> is a double.</li>
<li><span style="color:dodgerblue"><strong>logical</strong></span>: Boolean values, <code>TRUE</code> and <code>FALSE</code></li>
<li><span style="color:dodgerblue"><strong>complex</strong></span>: complex numbers. E.g., <code>1+3i</code></li>
<li><span style="color:dodgerblue"><strong>raw</strong></span>: a type to hold raw bytes.</li>
</ol>
<section id="checking-data-type-using-typeof" class="level2">
<h2 class="anchored" data-anchor-id="checking-data-type-using-typeof">Checking Data Type Using <code>typeof()</code></h2>
<hr>
<ul>
<li>The <code>typeof()</code> function returns the R internal type or storage mode of any object.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(<span class="fl">1.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "double"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "double"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(3L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "integer"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(<span class="st">"hello"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(<span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "logical"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(storms<span class="sc">$</span>status)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "integer"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(storms<span class="sc">$</span>year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "double"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(storms<span class="sc">$</span>name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
</div>
</section>
<section id="investigating-data-types-with-is.numeric" class="level2">
<h2 class="anchored" data-anchor-id="investigating-data-types-with-is.numeric">Investigating Data Types with <code>is.numeric()</code></h2>
<hr>
<ul>
<li>The <code>is.numeric(x)</code> function tests whether or not an object <code>x</code> is numeric.</li>
<li>The <code>is.character(x)</code> function tests whether <code>x</code> is a character or not.</li>
<li>The <code>is.factor(x)</code> function tests whether <code>x</code> is a factor or not.</li>
<li><span style="color:dodgerblue"><strong>Note: Categorical data is typically stored as a <code>factor</code> in R.</strong></span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.numeric</span>(storms<span class="sc">$</span>year)  <span class="co"># year is numeric</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.numeric</span>(storms<span class="sc">$</span>category)  <span class="co"># category is also numeric</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.numeric</span>(storms<span class="sc">$</span>name)  <span class="co"># name is not numeric</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.character</span>(storms<span class="sc">$</span>name)  <span class="co"># name is character string</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.numeric</span>(storms<span class="sc">$</span>status)  <span class="co"># status is not numeric</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.character</span>(storms<span class="sc">$</span>status)  <span class="co"># status is not a character</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(storms<span class="sc">$</span>status)  <span class="co"># status is a factor which is categorical</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<ul>
<li>The function <code>str(x)</code> provides information about the levels or classes of <code>x</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(storms<span class="sc">$</span>status)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 9 levels "disturbance",..: 7 7 7 7 7 7 7 7 8 8 ...</code></pre>
</div>
</div>
</section>
<section id="changing-data-types" class="level2">
<h2 class="anchored" data-anchor-id="changing-data-types">Changing Data Types</h2>
<hr>
<section id="converting-to-categorical-data-with-factor" class="level3">
<h3 class="anchored" data-anchor-id="converting-to-categorical-data-with-factor">Converting to Categorical Data with <code>factor()</code></h3>
<hr>
<ul>
<li>Sometimes we think a variable is one data type, but it is actually being stored (and thus interpreted by R) as a different data type.</li>
<li>One common issue is categorical data is stored as characters. We would like observations with the same values to be group together.</li>
<li>The <code>status</code> variable in <code>storms</code> is being properly stored as a <code>factor</code>!</li>
<li>The <code>category</code> variable in <code>storms</code> is being stored as a <code>numeric</code> since it is ordinal.</li>
<li>With ordinal categories, we may choose to keep it stored as <code>numeric</code>, or we may prefer to treat them as factors.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(storms<span class="sc">$</span>category)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  1.000   1.000   1.000   1.898   3.000   5.000   14382 </code></pre>
</div>
</div>
<ul>
<li>The summary of <code>category</code> computes statistics such as mean and median.</li>
<li>Typically with categorical data, we prefer to count how many observations are in each class of the variable.</li>
<li>In the code cell below, we convert <code>category</code> to a factor, and then observe the resulting summary.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>storms<span class="sc">$</span>category <span class="ot">&lt;-</span> <span class="fu">factor</span>(storms<span class="sc">$</span>category)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(storms<span class="sc">$</span>category)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3     4     5  NA's 
 2478   973   579   539   115 14382 </code></pre>
</div>
</div>
</section>
<section id="converting-data-types-with-as.numeric-as.integer-etc." class="level3">
<h3 class="anchored" data-anchor-id="converting-data-types-with-as.numeric-as.integer-etc.">Converting Data Types with <code>as.numeric()</code>, <code>as.integer()</code>, etc.</h3>
<hr>
<p>From the summary of the <code>storms</code> data set we first found above, we see that the variables <code>year</code> and <code>month</code> are being stored as <code>double</code>. These variables actually are integer values.</p>
<p>We can convert another variable of one format into another format using <code>as.[new_datatype]()</code></p>
<ul>
<li>For example, to convert to year to <code>integer</code>, we use <code>as.integer(storms$year)</code>.</li>
<li>To convert a data type to character, we can use <code>as.character(x)</code>.</li>
<li>To convert to a decimal (<code>double</code>), we can use <code>as.numeric(x)</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(storms<span class="sc">$</span>year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "double"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(storms<span class="sc">$</span>month)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "double"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>storms<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(storms<span class="sc">$</span>year)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>storms<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(storms<span class="sc">$</span>month)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(storms<span class="sc">$</span>year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "integer"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(storms<span class="sc">$</span>month)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "integer"</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="data-structures" class="level1">
<h1>Data structures</h1>
<hr>
<p>R operates on <span style="color:dodgerblue"><strong>data structures</strong></span>. A data structure is simply some sort of “container” that holds certain kinds of information</p>
<p>R has 5 basic data structures:</p>
<ul>
<li><span style="color:dodgerblue"><strong>vector</strong></span>: One dimensional object of a single data type.</li>
<li><span style="color:dodgerblue"><strong>matrix</strong></span>: Two dimensional object of a single data type.</li>
<li><span style="color:dodgerblue"><strong>array</strong></span>: <span class="math inline">\(n\)</span> dimensional object of a single data type.</li>
<li><span style="color:dodgerblue"><strong>data frame</strong></span>: Two dimensional object where each column can be a different data type.</li>
<li><span style="color:dodgerblue"><strong>list</strong></span>: An object that contains elements of different types like (and possibly another list inside it).</li>
</ul>
<p><a href="https://cran.r-project.org/doc/manuals/r-release/R-lang.html#List-objects">See R documentation</a> for more info.</p>
<section id="vectors" class="level2">
<h2 class="anchored" data-anchor-id="vectors">Vectors</h2>
<hr>
<p>A <span style="color:dodgerblue"><strong>vector</strong></span> is a single-dimensional set of data of the same type.</p>
<section id="creating-vectors-from-scratch" class="level3">
<h3 class="anchored" data-anchor-id="creating-vectors-from-scratch">Creating Vectors from Scratch</h3>
<hr>
<p>The most basic way to create a vector is the combine function <code>c</code>. The following commands create vectors of type numeric, character, and logical, respectively.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="fl">5.3</span>, <span class="dv">6</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">4</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"one"</span>, <span class="st">"two"</span>, <span class="st">"three"</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>x3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>, <span class="cn">TRUE</span>)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>x4 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="fl">3.4</span>, <span class="st">"hello"</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(x1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "double"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(x2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(x3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "logical"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(x4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
</div>
<ul>
<li>We can check the data structure of an object using commands such as <code>is.vector()</code>, <code>is.list()</code>, <code>is.matrix()</code>, and so on.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.list</span>(x1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.vector</span>(x1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.list</span>(x4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.vector</span>(x4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
</section>
<section id="data-frames" class="level2">
<h2 class="anchored" data-anchor-id="data-frames">Data Frames</h2>
<hr>
<p><span style="color:dodgerblue"><strong>Data frames</strong></span> are two-dimensional data objects and are the <strong>fundamental</strong> data structure used by most of R’s libraries of functions and data sets.</p>
<ul>
<li>Tabular data is <span style="color:dodgerblue"><strong>tidy</strong></span> if each row corresponds to a different observation and column corresponds to a different variable.</li>
</ul>
<p>Each column of a data frame is a <span style="color:dodgerblue"><strong>variable</strong></span> (stored as a <strong>vector</strong>). If the variable:</p>
<ul>
<li>Is measured or counted by a number, it is a <span style="color:dodgerblue"><strong>quantitative</strong></span> or <span style="color:dodgerblue"><strong>numerical</strong></span> variable.</li>
<li>Groups observations into different categories or rankings, it is a <span style="color:dodgerblue"><strong>qualitative</strong></span> or <span style="color:dodgerblue"><strong>categorical</strong></span> variable.</li>
</ul>
<section id="creating-data-frames-from-scratch" class="level3">
<h3 class="anchored" data-anchor-id="creating-data-frames-from-scratch">Creating Data Frames from Scratch</h3>
<hr>
<p>Data frames are created by passing vectors into the <code>data.frame()</code> function.</p>
<p>The names of the columns in the data frame are the names of the vectors you give the <code>data.frame</code> function.</p>
<p>Consider the following simple example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create basic data frame</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"white"</span>, <span class="st">"blue"</span>, <span class="cn">NA</span>)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">TRUE</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(d,e,f)</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  d     e     f
1 1   red  TRUE
2 2 white  TRUE
3 3  blue  TRUE
4 4  &lt;NA&gt; FALSE</code></pre>
</div>
</div>
</section>
<section id="naming-column-headers" class="level3">
<h3 class="anchored" data-anchor-id="naming-column-headers">Naming Column Headers</h3>
<hr>
<p>The columns of a data frame can be renamed using the <code>names()</code> function on the data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># name columns of data frame</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ID"</span>, <span class="st">"Color"</span>, <span class="st">"Passed"</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ID Color Passed
1  1   red   TRUE
2  2 white   TRUE
3  3  blue   TRUE
4  4  &lt;NA&gt;  FALSE</code></pre>
</div>
</div>
<p>The columns of a data frame can be named when you are first creating the data frame by using <code>[new_name] = [orig_vec_name]</code> for each vector of data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create data frame with better column names</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ID =</span> d, <span class="at">Color =</span> e, <span class="at">Passed =</span> f)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>df2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ID Color Passed
1  1   red   TRUE
2  2 white   TRUE
3  3  blue   TRUE
4  4  &lt;NA&gt;  FALSE</code></pre>
</div>
</div>
</section>
</section>
<section id="checking-data-structure" class="level2">
<h2 class="anchored" data-anchor-id="checking-data-structure">Checking Data Structure</h2>
<hr>
<ul>
<li>The <code>is.matrix(x)</code> function tests whether or not an object <code>x</code> is a matrix.</li>
<li>The <code>is.vector(x)</code> function test whether <code>x</code> is a vector.</li>
<li>The <code>is.data.frame(x)</code> function test whether <code>x</code> is a data frame.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.matrix</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.vector</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.data.frame</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
</section>
<section id="extracting-and-slicing-data-frames" class="level1">
<h1>Extracting and Slicing Data Frames</h1>
<hr>
<section id="extracting-a-column-by-name" class="level2">
<h2 class="anchored" data-anchor-id="extracting-a-column-by-name">Extracting a Column By Name</h2>
<hr>
<p>The column vectors of a data frame may be extracted using <code>$</code> and specifying the name of the desired vector.</p>
<ul>
<li><code>df$Color</code> would access the <code>Color</code> column of data frame <code>df</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Color  <span class="co"># prints column of data frame df named Color</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "red"   "white" "blue"  NA     </code></pre>
</div>
</div>
</section>
<section id="slicing-rows-and-columns-by-indexing" class="level2">
<h2 class="anchored" data-anchor-id="slicing-rows-and-columns-by-indexing">Slicing Rows and Columns By Indexing</h2>
<hr>
<p>Part of a data frame can also be extracted by thinking of at as a general matrix and specifying the desired rows or columns in square brackets after the object name.</p>
<ul>
<li><span style="color:dodgerblue"><strong>Note R starts with index 1 which is different from Python which indexes starting from 0.</strong></span></li>
</ul>
<p>For example, if we had a data frame named <code>df</code>:</p>
<ul>
<li><code>df[1,]</code> would access the first row of <code>df</code>.</li>
<li><code>df[1:2,]</code> would access the first two rows of <code>df</code>.</li>
<li><code>df[,2]</code> would access the second column of <code>df</code>.</li>
<li><code>df[1:2, 2:3]</code> would access the information in rows 1 and 2 of columns 2 and 3 of <code>df</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>df[,<span class="dv">2</span>]  <span class="co"># second column is Color</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "red"   "white" "blue"  NA     </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>df[<span class="dv">2</span>,]  <span class="co"># second row of df</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ID Color Passed
2  2 white   TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>df[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>]  <span class="co"># first and second rows of columns 2 and 3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you need to select multiple columns of a data frame by name, you can pass a character vector with column names in the column position of <code>[]</code>.</p>
<ul>
<li><code>df[, c("ID", "Passed")]</code> would extract the <code>ID</code> and <code>Passed</code> columns of <code>df</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>df[, <span class="fu">c</span>(<span class="st">"ID"</span>, <span class="st">"Passed"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ID Passed
1  1   TRUE
2  2   TRUE
3  3   TRUE
4  4  FALSE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>df[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)]  <span class="co"># another we to pick columns 1 and 3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ID Passed
1  1   TRUE
2  2   TRUE
3  3   TRUE
4  4  FALSE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># another we to pick columns 1 and 3</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>df[, <span class="sc">-</span><span class="dv">2</span>]  <span class="co"># exclude column 2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ID Passed
1  1   TRUE
2  2   TRUE
3  3   TRUE
4  4  FALSE</code></pre>
</div>
</div>
</section>
</section>
<section id="importing-an-external-file-as-a-data-frame" class="level1">
<h1>Importing an External File as a Data Frame</h1>
<hr>
<p>The <code>read.table</code> function imports data from file into R as a data frame.</p>
<p>Usage: <code>read.table(file, header = TRUE, sep = ",")</code></p>
<ul>
<li><code>file</code> is the file path and name of the file you want to import into R.
<ul>
<li>If you don’t know the file path, set <code>file = file.choose()</code> will bring up a dialog box asking you to locate the file you want to import.</li>
</ul></li>
<li><code>header</code> specifies whether the data file has a header (variable labels for each column of data in the first row of the data file).
<ul>
<li>If you don’t specify this option in R or use <code>header = FALSE</code>, then R will assume the file doesn’t have any headings.</li>
<li><code>header = TRUE</code> tells R to read in the data as a data frame with column names taken from the first row of the data file.</li>
</ul></li>
<li><code>sep</code> specifies the delimiter separating elements in the file.
<ul>
<li>If each column of data in the file is separated by a space, then use <code>sep = " "</code></li>
<li>If each column of data in the file is separated by a comma, then use <code>sep = ","</code></li>
<li>If each column of data in the file is separated by a tab, then use <code>sep = "\t"</code>.</li>
</ul></li>
</ul>
<p>Here is an example reading a csv (comma separated file) with a header:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import data as data frame</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>bike.store <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file=</span><span class="st">"https://raw.githubusercontent.com/CU-Denver-MathStats-OER/Statistical-Theory/main/Data/Transactions.csv"</span>,</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">header =</span> <span class="cn">TRUE</span>,  <span class="co"># Keep column headers as names</span></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">sep =</span> <span class="st">","</span>)  <span class="co"># comma as separator of columns</span></span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(bike.store)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 20,000
Columns: 13
$ transaction_id          &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,…
$ product_id              &lt;int&gt; 2, 3, 37, 88, 78, 25, 22, 15, 67, 12, 5, 61, 3…
$ customer_id             &lt;int&gt; 2950, 3120, 402, 3135, 787, 2339, 1542, 2459, …
$ transaction_date        &lt;chr&gt; "25-02-2017", "21-05-2017", "16-10-2017", "31-…
$ online_order            &lt;lgl&gt; FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, F…
$ order_status            &lt;chr&gt; "Approved", "Approved", "Approved", "Approved"…
$ brand                   &lt;chr&gt; "Solex", "Trek Bicycles", "OHM Cycles", "Norco…
$ product_line            &lt;chr&gt; "Standard", "Standard", "Standard", "Standard"…
$ product_class           &lt;chr&gt; "medium", "medium", "low", "medium", "medium",…
$ product_size            &lt;chr&gt; "medium", "large", "medium", "medium", "large"…
$ list_price              &lt;dbl&gt; 71.49, 2091.47, 1793.43, 1198.46, 1765.30, 153…
$ standard_cost           &lt;dbl&gt; 53.62, 388.92, 248.82, 381.10, 709.48, 829.65,…
$ product_first_sold_date &lt;int&gt; 41245, 41701, 36361, 36145, 42226, 39031, 3416…</code></pre>
</div>
</div>
<ul>
<li>The <code>glimpse()</code> function provides a nice summary of the structure.</li>
<li>Run the code cell below to see the various options of <code>read.table()</code>.</li>
<li>There are other functions and packages that may be better at reading in tabular data. <code>read.table()</code> is a good place to start!</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>?read.table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="logical-statements" class="level1">
<h1>Logical Statements</h1>
<hr>
<p>Sometimes we need to know if the elements of an object satisfy certain conditions. This can be determined using the logical operators <code>&lt;</code>, <code>&lt;=</code>, <code>&gt;</code>, <code>&gt;=</code>, <code>==</code>, <code>!=</code>.</p>
<ul>
<li><code>==</code> means equal to.</li>
<li><code>!=</code> means NOT equal to.</li>
</ul>
<p>Execute the following commands in R and see what you get.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">2</span>, <span class="dv">16</span>, <span class="at">by =</span> <span class="dv">2</span>) <span class="co"># creating the vector a</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2  4  6  8 10 12 14 16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>a <span class="sc">&gt;</span> <span class="dv">10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>a <span class="sc">&lt;=</span> <span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>a <span class="sc">==</span> <span class="dv">10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>a <span class="sc">!=</span> <span class="dv">10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE</code></pre>
</div>
</div>
<section id="and-and-or-statements" class="level2">
<h2 class="anchored" data-anchor-id="and-and-or-statements">And and Or Statements</h2>
<hr>
<p>More complicated logical statements can be made using <code>&amp;</code> and <code>|</code>.</p>
<ul>
<li><code>&amp;</code> means “and”
<ul>
<li>Both statements must be true for <code>state1 &amp; state2</code> to return <code>TRUE</code>.</li>
</ul></li>
<li><code>|</code> means “or”
<ul>
<li>Only one of the the two statements must be true for <code>state1 | state2</code> to return <code>TRUE</code>.</li>
<li>If both statements are true in an “or” statement, the statement is also <code>TRUE</code>.</li>
</ul></li>
</ul>
<p>Below is a summary of “and” and “or” logic:</p>
<ul>
<li><code>TRUE &amp; TRUE</code> returns <code>TRUE</code></li>
<li><code>FALSE &amp; TRUE</code> returns <code>FALSE</code></li>
<li><code>FALSE &amp; FALSE</code> returns <code>FALSE</code></li>
<li><code>TRUE | TRUE</code> returns <code>TRUE</code></li>
<li><code>FALSE | TRUE</code> returns <code>TRUE</code></li>
<li><code>FALSE | FALSE</code> returns <code>FALSE</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># relationship between logicals &amp; (and), | (or)</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">&amp;</span> <span class="cn">TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">&amp;</span> <span class="cn">TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">&amp;</span> <span class="cn">FALSE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">|</span> <span class="cn">TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">|</span> <span class="cn">TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">|</span> <span class="cn">FALSE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>Execute the following commands in R and see what you get.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="dv">3</span>  <span class="co"># b is equal to the number 3</span></span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a><span class="co"># complex logical statements</span></span>
<span id="cb121-4"><a href="#cb121-4" aria-hidden="true" tabindex="-1"></a>(b <span class="sc">&gt;</span> <span class="dv">6</span>) <span class="sc">&amp;</span> (b <span class="sc">&lt;=</span> <span class="dv">10</span>)  <span class="co"># FALSE and TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>(b <span class="sc">&lt;=</span> <span class="dv">4</span>) <span class="sc">|</span> (b <span class="sc">&gt;=</span> <span class="dv">12</span>)  <span class="co"># TRUE or FALSE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="logical-indexing" class="level2">
<h2 class="anchored" data-anchor-id="logical-indexing">Logical Indexing</h2>
<hr>
<p>We can use a logical statement as an index to extract certain entries from a vector or data frame. For example, if we want to to know the <code>product_id</code> (column 2), <code>brand</code> (column 7), <code>product_line</code> (column 8), and <code>list_price</code> (column 11) of all transactions that have a <code>list_price</code> greater than $2,090, we can run the code cell below.</p>
<ul>
<li>We use a logical index for the row to extract just the rows that have a <code>list_price</code> value strictly greater than 2090.</li>
<li>We indicate we want to keep just columns 2, 7 through 8, and 11 with the column index <code>c(2, 7:8, 11)</code>.</li>
<li>We store the results to a new data frame named <code>expensive</code>.</li>
<li>Finally, we print the first 6 rows of our new data frame with the <code>head()</code> function to check the results.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>expensive <span class="ot">&lt;-</span> bike.store[bike.store<span class="sc">$</span>list_price <span class="sc">&gt;</span> <span class="dv">2090</span>, <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">7</span><span class="sc">:</span><span class="dv">8</span>, <span class="dv">11</span>)]</span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(expensive)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    product_id         brand product_line list_price
2            3 Trek Bicycles     Standard    2091.47
16           3 Trek Bicycles     Standard    2091.47
69          38 Trek Bicycles     Standard    2091.47
154          3 Trek Bicycles     Standard    2091.47
165          3 Trek Bicycles     Standard    2091.47
188          3 Trek Bicycles     Standard    2091.47</code></pre>
</div>
</div>
</section>
</section>
<section id="creative-commons-license-information" class="level1">
<h1>Creative Commons License Information</h1>
<hr>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Creative Commons License</figcaption>
</figure>
</div>
<p><em>Statistical Methods: Exploring the Uncertain</em> by <a href="https://github.com/CU-Denver-MathStats-OER/Statistical-Theory">Adam Spiegler (University of Colorado Denver)</a> is licensed under a <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>. This work is funded by an <a href="https://cdhe.colorado.gov/educators/administration/institutional-groups/open-educational-resources-in-colorado">Institutional OER Grant from the Colorado Department of Higher Education (CDHE)</a>.</p>
<p>For similar interactive OER materials in other courses funded by this project in the Department of Mathematical and Statistical Sciences at the University of Colorado Denver, visit <a href="https://github.com/CU-Denver-MathStats-OER" class="uri">https://github.com/CU-Denver-MathStats-OER</a>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>